### ISSUE TITLE
Question: How to implement IBuffer and IBufferByteAccess interfaces correctly?

### ISSUE THREAD

**Issue by lhak** [microsoft/CsWinRT#1013]
In my application I use a custom buffer class that derives from IBuffer and IBufferByteAccess like this:

```csharp

[ComImport]
[Guid("905a0fef-bc53-11df-8c49-001e4fc686da")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface IBufferByteAccess
{
	unsafe Byte* Buffer { get; }
}

public class CustomBuffer : IBuffer, IBufferByteAccess
{
...
}

```

This works fine in .net core 3.1 and I can pass such objects to win2d methods which expect an IBuffer as a parameter. However, using .net 5/winui 3 my code crashes with a System.InvalidCastException: "Specified cast is not valid" exception.

**Comment by angelazhangmsft** [comment]
@lhak, you should be able to use the workaround in #827 for any COM interface.

**Comment by DjArt** [comment]
@angelazhangmsft, hi!
I'm not able to use proposed workaround for `IBufferByteAccess` with exception:
`System.Runtime.InteropServices.InvalidComObjectException: "COM object that has been separated from its underlying RCW cannot be used."` when calling `MediaStreamSample.CreateFromBuffer`.
Is somewhat changed from that time?
