### ISSUE TITLE
Creating a sideloading App Package with WinUI 3 for ARM64 fails

### ISSUE THREAD

**Issue by pontin-pdftron** [microsoft/CsWinRT#1023]
**Describe the bug**
I'm trying to publish a WinUI 3 sideload project (App Packages) for ARM64 using my NuGet package that contains my x64, x86 and ARM64 WinRT projection components but it fails due a *mismatch between the processor architecture*

**To Reproduce**
1. Right click on WinUI 3 App (Package), select Publish and Create App Package
2. Select Sideloading and then only check ARM64 (Release)
3. Build fails with the error message below:

```
There was a mismatch between the processor architecture of the project being built "" and the processor architecture of the reference "_private_path_\0.1.10-prerelease\lib\net5.0\WinRT_projection.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
```

**Expected behavior**
I should be able to create the sideload for all x64, x86 and ARM64 targets like a normal UWP app.

**Version Info**
*Projection*
- Microsoft.Windows.CsWinRT: 1.3.5
- Microsoft.ProjectReunion.WinUI: 0.8.5

*WinUI 3 app*
- Microsoft.ProjectReunion: 0.8.5
- CommunityToolkit.Mvvm: 7.0.3
- Microsoft.Extensions.DependencyInjection: 5.0.1
- Microsoft.Xaml.Behaviors.WinUI.Managed 2.0.4

*Visual Studio Pro 2019*
- version: 16.11.1

**Additional context**

I followed this sample project to ensure the projection/nuget is properly created:
https://github.com/angelazhangmsft/ProjectReunionSimpleMathProjection/tree/main/ProjectReunionSimpleMathProjection

I can create the sideload project for x64 and x86.

Some similar issue: https://github.com/microsoft/CsWinRT/issues/835, https://github.com/microsoft/CsWinRT/issues/811

**Comment by pontin-pdftron** [comment]
@angelazhangmsft sorry for the late reply.

The error occurs when I'm building a WinUI 3 App that consumes my nuget/projection package (x86, x64 and arm64).

I'm creating a NuGet package for x86, x64 and ARM64 archs - until this point everything works and I can create the NuGet package properly.
But when I'm consuming this package from a WinUI 3 App it will raise the error below saying the `WinRT.Interop.dll` (which should be arch-neutral) causes a mismatch.

```
error MSB3270: There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference :
"...\.nuget\packages\winrt\0.2.1-prerelease\lib\net5.0\WinRT.Interop.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
```

In my NuGet package creation I'm copying the x86 Interop dll since it should not matter (neutral) - but on my WinUI 3 app if I'm targeting either x64 or ARM64 I will get the error above. Targeting x86 works fine.

This is how I set the file in the nuget spec :

``` 
    <!--Architecture-netural assemblies--> 
    <file src="..\..\output\Win32\Release\winrtLib.winmd" target="lib\netcoreapp3.0\winrtLib.winmd" />
    <file src="..\..\output\Win32\Release\winrtLib.winmd" target="lib\uap10.0\winrtLib.winmd" />
    <file src="..\..\output\Win32\Release\winrtLib.winmd" target="lib\net46\winrtLib.winmd" />
    
    <file src="..\..\_build\x86\Release\WinRT.Interop\bin\WinRT.Interop.dll" target="lib\net5.0\WinRT.Interop.dll" />
    
    <!--Architecture-specific implementation DLLs should be copied into RID-relative folders-->
    <file src="..\..\output\x64\Release\winrtLib.dll" target="runtimes\win10-x64\native\winrtLib.dll" />
    <file src="..\..\output\Win32\Release\winrtLib.dll" target="runtimes\win10-x86\native\winrtLib.dll" />
    <file src="..\..\output\ARM64\Release\winrtLib.dll" target="runtimes\win10-arm64\native\winrtLib.dll" />
```

**Comment by angelazhangmsft** [comment]
@pontin-pdftron, I've investigated this issue - instead of building the projection for a specific architecture, you should set the platform to AnyCPU:

```xml
<Platform>AnyCPU</Platform>
```

It looks like when building the projection project for a specific architecture (e.g., x86), it cannot be consumed from an x64 targeting app. We are going to update the existing [sample](https://github.com/microsoft/CsWinRT/tree/master/src/Samples/NetProjectionSample) + docs to reflect this guidance.  

You might also need this property in your C# projection project to workaround an error on "processor architecture mismatch" (I've filed an issue for this #1097):

```xml
<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
```
Let me know if this solves your issue!

**Comment by pontin-pdftron** [comment]
@angelazhangmsft It worked on my side now.

I really appreciate it!
