### ISSUE TITLE
Taking a WeakReference to a C# object that inherits a native WinRT object crashes the app.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/CsWinRT#1025]
**Describe the bug**
WeakReferences to managed objects inheriting native objects causes InvalidCastExceptions and/or access violations.

**To Reproduce**
1. Open the attached project in VS: [WeakRefRepro.zip](https://github.com/microsoft/CsWinRT/files/7369759/WeakRefRepro.zip)
2. Click "Click Me" repeatedly.

**Expected behavior**
No crash/exception.

**Version Info**
CsWinRT 1.3.5

**Comment by AaronRobinsonMSFT** [comment]
@manodasanW This appears to be a .NET bug. @jkoritzinsky will be looking into a fix. We chatted offline and I believe we understand the problem&mdash;it is limited to aggregation scenarios.

**Comment by jlaanstra** [comment]
@jkoritzinsky is there a .NET build I can use to verify this is fixed?
