### ISSUE TITLE
Question: Using CsWinRT to use WinRT APIs on .NET 5

### ISSUE THREAD

**Issue by A-Ovchinnikov-mx** [microsoft/CsWinRT#1031]
Hi,

I would like to use CsWinRT to generate wrappers for specific WinRT APIs we use in our library. The reason why I don't want to use TFMs like `net5.0-windows10.0.19041.0` is because I don't want to have a dependency on **Microsoft.Windows.SDK.NET.dll** that is 25 MB in size (for comparison, with CsWinRT our DLL is <300K and that's it).

I've already defined `<CsWinRTWindowsMetadata>sdk</CsWinRTWindowsMetadata>` in csproj and also `CsWinRTFilters`, but I would like to use `Microsoft.Windows.SDK.Contracts` NuGet package. Unfortunately, when I reference it, it complains about incompatible `TargetPlatformVersion` value.

What is the correct and supported approach to accomplish this?

Thanks!

**Comment by angelazhangmsft** [comment]
@A-Ovchinnikov-mx glad you got that working. Thee embedded support work will provide official support for embedding the Windows SDK projections in your library to address the 25 MB size issue as well.

Can you provide a binlog/repro of the 2nd issue? I wasn't able to see what you are seeing with the same setup.

**Comment by A-Ovchinnikov-mx** [comment]
Hi @angelazhangmsft ,

Here's a minimal project:

[CsWinRTIssue.zip](https://github.com/microsoft/CsWinRT/files/7447039/CsWinRTIssue.zip)

`WinRT.Host.Shim.dll` gets copied always. We're also setting `Platforms = x64` and (not in this sample) `RuntimeIdentifier = win10-x64` which also makes it copy `WinRT.Host.dll`. In this sample it's in the `runtime` subfolder, but it still gets copied.

**Comment by angelazhangmsft** [comment]
@A-Ovchinnikov-mx thanks for the repro, I opened an issue to track this. One thing I tried was setting `<PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.3.5" PrivateAssets="all"/>` in the library project, but this also blocks `WinRT.Runtime.dll`, which is needed by the app.

**Comment by A-Ovchinnikov-mx** [comment]
@angelazhangmsft Thanks a lot! I suppose what I could do for now is use `PrivateAssets="all"` together with `GeneratePathProperty="true"`, and then add a manual reference to `WinRT.Runtime.dll` 🙂
