### ISSUE TITLE
IIDOptimizer crashes when run on an ARM64 device

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/CsWinRT#1070]
**Describe the bug**
IIDOptimizer crashes when a CsWinRT referencing project is built on an ARM64 device.

**To Reproduce**
1. Install .NET 6 ARM64 SDK on an ARM64 device, e.g. Surface Pro X
2. Create a classlib project
3. Add CsWinRT reference
4. Add .winmd reference
5. Setup `CsWinRTIncludes` and `CsWinRTWindowsMetadata`
6. Build the project

**Expected behavior**
Project compiles without warnings.

**Actual behavior**
Project compiles but the following warning/error is displayed:
```
  Failed to load the dll from [C:\Program Files\dotnet\host\fxr\6.0.1\hostfxr.dll], HRESULT: 0x800700C1
  The library hostfxr.dll was found, but loading it from C:\Program Files\dotnet\host\fxr\6.0.1\hostfxr.dll failed
    - Installing .NET prerequisites might help resolve this problem.
       https://go.microsoft.com/fwlink/?linkid=798306
```
Windows Event Viewer shows that a crash occurs in `packages\microsoft.windows.cswinrt\1.4.1\build\tools\IIDOptimizer\IIDOptimizer.exe`.

**Version Info**
CsWinRT: 1.4.1
.NET SDK: 6.0.101
Windows SDK: Microsoft.Windows.SDK.CPP NuGet package, version 10.0.22000.196
OS: Windows 11 ARM64

**Additional context**
This is likely because IIDOptimizer.exe is x64 itself and tries to load ARM64 hostfxr.dll. It should probably redistribute a private version of hostfxr.dll instead.

**Comment by manodasanW** [comment]
Testing with the latest 6.0.6 showed the issue still repros.  Looks like we will need to rebuild with that version to get the fix as the apphost exe comes from .NET.

**Comment by manodasanW** [comment]
IIDOptimizer now is built using .NET 6 in CsWinRT 2.0 which should address this.
