### ISSUE TITLE
Unpackaged scenarios with WinAppSDK broken

### ISSUE THREAD

**Issue by j0shuams** [microsoft/CsWinRT#1116]
Using a C#/WinRT component with WinUI 3 types from unpackaged apps has some issues. In the C++ case, a runtime error is thrown "No package identity". In the C# case, a WinAPPSDK error is thrown "No match for key in index"

**To Reproduce**

1. Follow the steps [here ](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?pivots=winui3-unpackaged-cpp#unpackaged-create-a-new-project-for-an-unpackaged-c-or-c-winui-3-desktop-app)to make an unpackaged app 
2. Create a C#/WinRT component 
3. Add a project reference in the C++ app to the C# component

*Expected behavior**
App runs normally

**Version Info**
Windows APP SDK - 1.1.0-20220215.0-CI-experimental
VS2022 
net6.0-windows10.0.19041

**Additional context**
Here's a repo with a repro - https://github.com/j0shuams/CsWinRTAuthoringWinUI/tree/alpha/CppUnpackaged

**Comment by j0shuams** [comment]
We may be holding it wrong, the docs are not entirely correct. Track these issues for this work:
- https://github.com/MicrosoftDocs/windows-uwp/issues/3691
- https://github.com/MicrosoftDocs/windows-uwp/issues/3695

**Comment by angelazhangmsft** [comment]
@j0shuams should this be closed? Seems like a doc issue, not a cswinrt issue.

**Comment by angelazhangmsft** [comment]
Can't repro.
