### ISSUE TITLE
netstandard2.0 and net48 targets don't build outside of the embedded scenario

### ISSUE THREAD

**Issue by talagrand** [microsoft/CsWinRT#1129]
When attempting to build a project targeting either the netstandard2.0 or net48 framework versions, and *not* using CsWinRTEmbedded, the project fails to build with missing references to the "WinRT" namespace. Poking around, I believe this is due to the published CsWinRT NuGet not containing assemblies for those targets. It appears it only contains a WinRT.Runtime.dll for net5.0.

The only sample in the repository targeting these framework versions uses the embedded configuration.
The embedded configuration is not suitable for our project, because we want re-export types defined in WinRT into our assembly's API surface area and the embedded configuration marks all WinRT types as "internal". If "embedded" could be disassociated from "internal", that would work for us as well.

This was attempted on CsWinRT 1.5.0. Happy to provide a repro if requested although it's not much more than a hello world.

**Comment by angelazhangmsft** [comment]
Hi @talagrand, we'd like to better understand your scenario - currently we only support .NET Standard 2.0 for embedded scenarios (where WinRT type usage is all internal). 

Are you able to use .NET 5 or later for your scenario? A repro would be helpful here as well.

**Comment by talagrand** [comment]
We cannot use .NET 5 - we'd like to integrate into a large, existing Server application built on .NET 4.8 which we do not control, as a mechanism to bridge from native (Rust) code to .NET. The managed assembly is a small passthrough to expose the WinRT API surface to client.
I can provide a repro early next week.

**Comment by talagrand** [comment]
Discussed in person. .NET Framework (netstandard2, net48) has native support for WinRT interop (albeit with different call patterns). Use of CsWinRT on .NET Framework is a bit touchy, because two different incompatible managed types may be created for the same underlying object - one via native WinRT interop and another via CsWinRT, so there's some resistance to growing support for CsWinRT on that platform to avoid footguns. Existing support is embedded only to localize this risk internally to a given assembly.

We're going to give the native integration support a shot on .NET Framework, and use multi-targeting to support .NET 5+ via CsWinRT.
