### ISSUE TITLE
Custom WinUI 3 C++/WinRT Control in C# WinUI project

### ISSUE THREAD

**Issue by nono3551** [microsoft/CsWinRT#1148]
I am trying to create WinUI C++/WinRT Component containing XAML control and iclude this custom control inside C# WinUI 3 project. Is this somehow possible? I had no luck yet. Could you please provide some examples if this is possible?

### Reason:
Since WinUI 3 does not offer media player I want to make media player like this:
https://github.com/asklar/WinAppSDK-MediaPlayer

### EDIT:
So far I found [WinRT APIs not supported in .NET 5 or later][1]. I found there *Windows.UI.Xaml (all classes in this namespace)* which seems to be needed for creating custom c++/winrt control. After I read this I assume that it is not possible to consume custom C++/WinRT WinUI 
control in C# WinUI project.

[![enter image description here][2]][2]

### Example:
Check [Git Repository][3] I made. Those are steps I created that repo.

- Check this topic [MS Docs][4]
- [Link to example][4]

1. Create C# Library
2. Create WinUI C++ Component
3. Setup accordingly to MS Docs and Example
4. Add WindowsSdk reference to library project
5. Add custom control to C++ project

What I found possible is to consume custom C# WinUI contron inside WinUI C++/WinRT project, which seems to be way to go for me but I would like to know if this approach is possible.

I also made [Stackoverflow][5] thread related to this issue. 

### Edit
CsWinRT version 1.6.1

  [1]: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#winrt-apis-not-supported-in-net-5-or-later
  [2]: https://i.stack.imgur.com/0bPyZ.png
  [3]: https://github.com/nono3551/WinUI-C-CustomControl
  [4]: https://github.com/microsoft/CsWinRT/tree/master/src/Samples/NetProjectionSample
  [5]: https://stackoverflow.com/posts/71590971/edit

**Comment by andreasjhkarlsson** [comment]
I have the exact same issue. Super strange that this  IXAMLMetaDataProviderMethods type is referenced as google gives zero results on what it is even.

**Comment by angelazhangmsft** [comment]
@nono3551, Can you confirm what version of C#/WinRT and Windows App SDK packages you are referencing? This may be a known issue where Windows App SDK hasn't updated to the latest version of C#/WinRT, causing it to not find some of the new functions we generate: #1051 

You may need to temporarily downgrade to a CsWinRT version < 1.4.1, until the Windows App SDK updates their projections.

**Comment by andreasjhkarlsson** [comment]
Not author but I can confirm that downgrading to 1.3.5 does fix the described issue. I also tried to upgrade the Windows App SDK version to 1.1.0-preview1 to see if that works with the latest C#/WinRT (1.6.1 as of writing), but I cannot build because of conflicting versions of Microsoft.Windows.SDK.Net that I have no idea how to fix.

Some questions: How is the version dependency supposed to work? How can I know which SDK version I need for a version of this library and how can I manage it across all the different packages that I could add to my project?

**Comment by nono3551** [comment]
I was using CsWinRT 1.6.1 which was latest at time of posting this issue.

**Comment by angelazhangmsft** [comment]
@nono3551 @andreasjhkarlsson - this issue should be addressed with the latest Windows App SDK 1.1.0-preview2. Feel free to reopen if you are still running into the errors with this version.

**Comment by kalizurawski** [comment]
I am experiencing this same issue using CsWinRT Version 2.0.0 on the Winui3 C# project with Windows App SDK 1.1.5.  For the C++/WinRT component I am using Cpp 2.0.210806.1.  Any suggestions on why I would still be getting a namespace issue? The component is included as a project reference to the Winui3 project.

**Comment by manodasanW** [comment]
@kalizurawski Are you getting the error for the same namespace and class (IXamlMetadataProviderMethods) or for a different namespace / class?

**Comment by kalizurawski** [comment]
> @kalizurawski Are you getting the error for the same namespace and class (IXamlMetadataProviderMethods) or for a different namespace / class?

I'm getting the error for a different namespace because my custom class is different.  I'm trying to do:
`xmlns:renderer=using:MyCustomControlComponent` in my .xaml file.  My control component is built with C++/WinRT and included as a project reference to the WinUI 3 project. It is defined in the .idl file as `runtimeclass MyCustomControl : Microsoft.UI.Xaml.Controls.ContentControl`

**Comment by manodasanW** [comment]
@kalizurawski Can you share the error you are getting?

**Comment by kalizurawski** [comment]
> @kalizurawski Can you share the error you are getting?

`Undefined namespace. The 'using' URI refers to a namespace 'MyCustomControlComponent' that could not be found.`. When referencing the same namespace from the xaml.cs the error it `The type or namespace name 'MyCustomControlComponent' could not be found (are you missing a using directive or an assembly reference?)`
