### ISSUE TITLE
WindowsAppSDK authoring project build fails on command line (error with PublishReadyToRun)

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#1151]
**Describe the bug**

Authoring with Windows App SDK and a project reference to the component causes an error on command line build. 

This is being tracked internally: [task.ms/39285537](https://task.ms/39285537)

**To Reproduce**

1. See https://github.com/microsoft/WindowsAppSDK-Samples/pull/174
2. Build pipeline error: `C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets#L1370
C:\Users\cloudtest\.nuget\packages\microsoft.windowsappsdk\1.0.0\build\Microsoft.Build.Msix.Packaging.targets(1370,5): Error APPX1101: Payload contains two or more files with the same destination path 'WinRT.Host.Shim.dll'. Source files: 
D:\a\_work\1\s\Samples\CustomControls\CsApp\obj\x86\Release\net6.0-windows10.0.19041.0\win10-x86\R2R\WinRT.Host.Shim.dll
C:\Users\cloudtest\.nuget\packages\microsoft.windows.cswinrt\1.6.1\lib\net5.0\WinRT.Host.Shim.dll`

**Expected behavior**

Build with no errors

**Version Info**

CsWinRT 1.6.1
.NET 6

**Comment by angelazhangmsft** [comment]
Current workaround is to set PublishReadyToRun to False in each pubxml file: 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/69016571/166842306-7427e3ab-2209-4fae-b770-5ecb76f2c872.png">

**Comment by manodasanW** [comment]
Will be addressed in WinAppSDK.

**Comment by evelynwu-msft** [comment]
This was fixed in WinAppSdk 1.1.

**Comment by j0shuams** [comment]
Yep, @angelazhangmsft confirmed when she merged her Samples PR IIRC

**Comment by angelazhangmsft** [comment]
> Yep, @angelazhangmsft confirmed when she merged her Samples PR IIRC ([microsoft/WindowsAppSDK-Samples#174](https://github.com/microsoft/WindowsAppSDK-Samples/pull/174))

I merged in the samples with 1.1 Preview 3, but they can be updated to 1.1 GA removing the PublishReadyToRun=False workaround
