### ISSUE TITLE
Structs can't have enum fields

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#1201]
**Describe the bug**
Structs cannot have fields of enum types, even though they should be able to

**To Reproduce**
```cs
namespace CSWinRT_AuthoringPlayground
{
    public enum MyEnum
    {
        A=1,
        B
    }

    public struct MyStruct
    {
        public MyEnum x;
    }
}
```

Get an error:
`error CsWinRT1013: Structure Struct1 has field of type x; x is not a valid Windows Runtime field type. Each field in a Windows Runtime structure can only be UInt8, Int16, UInt16, Int32, UInt32, Int64, UInt64, Single, Double, Boolean, String, Enum, or itself a structure.`

**Expected behavior**
Code  builds

**Version Info**
CsWinRT 1.6.4

**Comment by j0shuams** [comment]
Fixed by #1235
