### ISSUE TITLE
Build succeeds even when generator fails

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#1202]
**Describe the bug**
The build should fail when the generator encounters an error

**To Reproduce**
```csharp
namespace CSWinRT_AuthoringPlayground
{
    public enum MyEnum
    {
        A=1,
        B
    }

    public struct MyStruct
    {
        public Enum x;
    }
}
```

Build output:
![image](https://user-images.githubusercontent.com/22989529/173772010-5742e5a5-cf5b-4d54-9c92-4cc1aae57aa0.png)

**Expected behavior**
Build fails

**Version Info**
CsWinRT 1.6.4

**Comment by manodasanW** [comment]
This is kind of a known issue with Rosyln source generators in general.  If I recall, there was an issue in the dotnet repo discussing this but will need to double check if anything changed since then.

**Comment by asklar** [comment]
regardless, the cswinrt generator should detect this and set an error exit code so that the build can fail
