### ISSUE TITLE
Evaluate making function pointers in generated projections blittable

### ISSUE THREAD

**Issue by manodasanW** [microsoft/CsWinRT#1242]
See https://github.com/microsoft/CsWinRT/pull/1240.  We should consider doing the same in our generated and manual projections of types where we have function pointers using out / ref.

**Comment by Sergio0694** [comment]
In case we wanted to turn this issue into a tracking meta-issue, so far we have:
- [ ] https://github.com/microsoft/CsWinRT/issues/1315
- [ ] https://github.com/microsoft/CsWinRT/issues/1316
- [ ] https://github.com/microsoft/CsWinRT/issues/1317
