### ISSUE TITLE
App_UnhandledException's UnhandledExceptionEventArgs.Exception can only be fetched once - should be cached

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#1258]
**Describe the bug**
The App.UnhandledException UnhandledExceptionEventArgs.Exception is volatile and can only be retrieved once, whether by user code or debug visualization. Subsequent accesses result in empty properties.  The Exception property should be cached so it can be accessed multiple times.

**To Reproduce**
1. Clone [WinUI3_UnhandledExceptionTestAppd](https://github.com/k563/WinUI3_UnhandledExceptionTestApp)
2. Build, set a BP in the App.UnhandledException handler, and debug
3. Click the button to cause an unhandled exception to be raised
4. When the BP hits, view the UnhandledExceptionEventArgs.Exception and its properties
5. Step through code to fetch the StackTrace property

**Expected behavior**
The StackTrace property should not be empty.  Instead, it's empty, the stowed exception having been fetched once and then removed from the thread.  This is true of all properties - only Hresult and Message are preserved (for some reason).

**Workarounds**
There are a few workarounds:
1. Fetch the exception and store it in a local, so properties are not lost:
```
var ex = e.Exception;
var ts = ex.TargetSite;
var st = ex.StackTrace;
var ie = ex.InnerException;
var m = ex.Message;
var hr = ex.HResult;
var s = ex.Source;
var message = String.Format(
@"Message: {0}
HResult: 0x{1:X8}
Source: {2}
TargetSite: {3}
Stack Trace: 
{4}", m, hr, s, ts, st);

```
2. Inspect **$exception** (if only viewing properties).

**Comment by asierpn** [comment]
I've tried the workaround but after storing the exception in a local, the symbolication information is lost:

![image](https://user-images.githubusercontent.com/9281751/195273282-efe6affb-a525-4975-b5c9-2d5847686575.png)

![image](https://user-images.githubusercontent.com/9281751/195273576-505b324a-c0ec-40b5-b78d-6ca209484aaa.png)

**Comment by Scottj1s** [comment]
@asierpn looks like you've found a workaround for your issue, https://github.com/microsoft/WindowsAppSDK/issues/3039

**Comment by asierpn** [comment]
@Scottj1s yes, and it's working fine in production, we are logging the stacktrace with all the details in App Center.
