### ISSUE TITLE
Do_Abi_* event/callback handlers should wrap invocations with RoReportUnhandledError

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#1259]
**Describe the bug**
The legacy C# WinRT projection support for UWP apps wrapped all synchronous calls back into C# code with a try/catch, calling RoOriginateLanguageException and then RoReportUnhandledError on any unhandled exceptions, ensuring they were then routed to the App.UnhandledException handler.  This behavior is missing from C#/WinRT projections, causing regressions in Microsoft.Windows.SDK.NET.dll (e.g., Window.Activated) and Microsoft.WinUI.dll (most everything else).  Thus, fixes might be required across several repos.

**To Reproduce**
For an override callback:
1. Clone [WinUI3_UnhandledExceptionTestAppd](https://github.com/k563/WinUI3_UnhandledExceptionTestApp)
2. Build, set a BP in OnLaunched and in the App.UnhandledException handler, and debug
3. When the OnLaunched BP hits, set next statement to throw the exception

For an event:
1. Clone [WinUI3_UnhandledExceptionTestAppd](https://github.com/k563/WinUI3_UnhandledExceptionTestApp)
2. Build, set a BP in the MainWindow's Activated handler and in the App.UnhandledException handler, and debug
3. When the Activated handler BP hits, set next statement to throw the exception

**Expected behavior**
In either case above, callback or event, the App.UnhandledException handler should be invoked as it is in a UWP app.

**Workarounds**
There are a couple workarounds:
1. User callbacks can be marked 'async' (whether or not they contain any awaits).  This causes the CLR to wrap invocations in a try/catch, propagating any caught exceptions through the DispatcherQueueSynchronizationContext.
`this.Activated += **async** (s, e) => { ... };`
2. User callback code can itself be wrapped in a try/catch to propagate errors:
```
this.Activated += (s, e) => {
  try
  {
    // ...
  }
  catch (System.Exception e)
  {
    ExceptionHelpers.ReportUnhandledError(e);
  }
}

```

**Comment by Scottj1s** [comment]
This issue is better addressed lower in the stack, in Microsoft.UI.Xaml.dll.  Fixing under original issue: https://github.com/microsoft/microsoft-ui-xaml/issues/5221

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK.1.2.221209.1` has been released which fixes this issue.

Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2.221209.1/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221209.1)
