### ISSUE TITLE
Add .net7 to dependencies on nuget.org

### ISSUE THREAD

**Issue by paulober** [microsoft/CsWinRT#1284]
**Describe the bug**
It currently only supports .net6 (says the version in the nuget.org store).

**Version Info**
2.0.1

**Additional context**
Also since i switched to .net7 with my .net6 Windows App SDK 1.2 project it starts crashing with kernelbase.pdb errors so this might be related to CsWinRT support of .net7.

**Comment by manodasanW** [comment]
@paulober The .NET 6.0 tag on NuGet represents the minimum version supported.  If you hover over it, you will notice it says "This package is compatible with this framework **or higher**".

Do you happen to have a call stack for when it crashes with .NET 7?  That might help determine why it is crashing.

**Comment by paulober** [comment]
> @paulober The .NET 6.0 tag on NuGet represents the minimum version supported. If you hover over it, you will notice it says "This package is compatible with this framework **or higher**".
> 
> Do you happen to have a call stack for when it crashes with .NET 7? That might help determine why it is crashing.

Ok, sorry for asking. And no the problem was due to trimming not working with my application...
