### ISSUE TITLE
Add arm64 to <Platforms> in Projections/*.csproj

### ISSUE THREAD

**Issue by paulober** [microsoft/CsWinRT#1285]
**Describe the bug**
Currently they only contains the platforms x64 and x86 for compilation.

**Version Info**
2.0.1

**Additional context**
`<Platforms>x64;arm64;x86</Platforms>

**Comment by manodasanW** [comment]
@paulober The projection projects under the Projections folder are just used for test purposes.  The actual projections that we distribute are typically built for _AnyCPU_ making them also compatible with ARM64.  Does that address the concern you had, or did you have another concern?
