### ISSUE TITLE
Setting DataContext to a self-referential instance throws StackOverflowException

### ISSUE THREAD

**Issue by darenm** [microsoft/CsWinRT#1291]
**Describe the bug**

Assigning a self-referential instance to DataContext results in a StackOverflowException due to recursion in the `WinRT.Projections` class.

View:
```xml
<Window
    x:Class="VMNet6Generic.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:VMNet6Generic"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
        <ContentControl x:Name="MyContent" />

    </StackPanel>
</Window>
```

Code-behind:
```csharp
using Microsoft.UI.Xaml;

using System.Collections.Generic;


namespace VMNet6Generic
{
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            this.Activated += MainWindow_Activated;
        }

        private void MainWindow_Activated(object sender, WindowActivatedEventArgs args)
        {
            MyContent.DataContext = new MyComponent();
        }
        private void myButton_Click(object sender, RoutedEventArgs e)
        {
            myButton.Content = "Clicked";
        }
    }

    public class MyComponent : List<MyComponent>
    {
    }
}
```

![image](https://user-images.githubusercontent.com/1674843/217882632-f0ca373f-5136-4b53-8064-384d89a303c1.png)

![image](https://user-images.githubusercontent.com/1674843/217861832-b48ee67e-51e7-4914-ad93-bae6b47bd4f6.png)

**To Reproduce**
1.  In Visual Studio 2022, create a new "Blank App, Packaged (WinUI 3 in Desktop)"
2.  Add a `ContentControl`  to the `MainWindow.xaml`  file as shown in the "View" code above.
3. Update the `MainWindow.xaml.cs` code-behind to include the `MyComponent` class definition and assign to the `MyContent.DataContext` property as shown in the "Code-Behind" above.
4. Compile and run.

**Expected behavior**
The runtime successfully assigns the instance of `MyComponent` to the DataContext property as experienced in WPF and UWP.

**Version Info**

- `<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.221109.1" />`
- `<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.755" />`
- ![image](https://user-images.githubusercontent.com/1674843/217867429-18812735-4651-4b3a-a958-c346247939b7.png)

**Additional context**

In our debugging, we found that the `Projection.TryGetCompatibleWindowsRuntimeTypesForVariantType` method iterates through the `genericArguments`, calling `Projection.GetCompatibleTypes`, which in turn, recurses back to  `Projection.TryGetCompatibleWindowsRuntimeTypesForVariantType` trying to fully resolve the variants related to `List<MyComponent>`. The same recursive issue is present if the class is defined as:

```csharp
public class MyComponent : IEnumerable<MyComponent>
{
   // IEnumerable<MyComponent> implementation...
}
```

Repro solution:
[VMNet6Generic.zip](https://github.com/microsoft/CsWinRT/files/10699601/VMNet6Generic.zip)

**Comment by darenm** [comment]
@manodasanW Hi there. Have you been able to reproduce the issue?

**Comment by manodasanW** [comment]
@darenm I was able to reproduce this and I do see what is happening.  I did some comparisons to what .NET Native's behavior here is and once I confirm a couple more scenarios, I should have a fix.
