### ISSUE TITLE
Member Events cannot be used on nullable versions of a type

### ISSUE THREAD

**Issue by vineeththomasalex** [microsoft/CsWinRT#1306]
**Describe the bug**
A nullable version of an object of an interface type defined in an IDL does not allow subscribing to a member event. CS0079 error is shown.
A non-nullable version of the object works fine.

**To Reproduce**

Consider an IDL file with type defined as below:
`interface ISomeInterface{       event Windows.Foundation.EventHandler<Some type> EventA;    }`
From a C# file, the following does not compile:
```
ISomeInterface someObject;
someObject?.EventA += () => {}; // CS0079 
```
However, the following does compile:
`someObject.EventA += () => {};`

**Expected behavior**
Following code should not show CS0079, and work similar to non-nullable version.
`someObject?.EventA += () => {};`

**Version Info**
PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.0.1"

**Comment by manodasanW** [comment]
This sounds like https://github.com/dotnet/csharplang/issues/6045 which is a proposal to support this syntax in C#.
