### ISSUE TITLE
Authoring component with a class implementing a projected interface breaks source generation with incorrect function

### ISSUE THREAD

**Issue by roxk** [microsoft/CsWinRT#1339]
**Describe the bug**
When authoring a component, if a public class implements a projected interface, source generator hard-error and emits `It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'Win32Exception' with message 'Incorrect function'`.

**To Reproduce**
1. Clone https://github.com/roxk/packaged-oop-winrt-server-app-extension/commit/d03f24e9c261a05bf49470d17269e2f1917013fc. The commit is currently the head of the `csharp` branch.
2. Open `PackagedOOPWinRTServerAppExtension.sln` and build `AppExtensionCSharp`
3. Observe warning `CS8785` and compile error.

![image](https://github.com/microsoft/CsWinRT/assets/16918354/fa1b1f07-8484-4591-aedc-3fe134be3a94)

**Expected behavior**
It builds successfully. `AppExtensionCSharp.WidgetProvider` should implement `SDK.IWidgetProvider` in the generated winmd.

**Version Info**
```
  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net6.0-windows10.0.22621.0</TargetFramework>
	<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
	<Platforms>x64</Platforms>
	<RuntimeIdentifier>win10-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.0.3" />
  </ItemGroup>
```

**Additional context**
1. Adding another _internal_ class that implements projected interface works fine. It's only when the class is public (i.e. included in the generated winmd) source generator would freak out.
2. I'm working on a sample of implementing app extension point via OOP WinRT Server, to replace OOP COM Server. This bug is a show-stopper for C#. C++ as found in the repo above is working as expected.

**Comment by manodasanW** [comment]
@roxk Thanks for the repro.  The issue is the WinRT authoring source generator needs to be able to find the WinMDs for any dependent components.  In this case, it is failing to find the SDK component's WinMD due to it is not included in the referenced NuGet.  If you include it in the referenced NuGet by doing something like below, you should see it build without issues.  Feel free to reopen if you still run into issues.

`
	<file src="..\..\x64\Release\SDK\SDK.winmd" target="lib\net6.0-windows10.0.22000.0\SDK.winmd" />
`
