### ISSUE TITLE
.NET 8 RC1 can not compile with Windows app sdk and CsWinRT

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/CsWinRT#1358]
**Describe the bug**
.NET 8 RC1 can not compile with Windows app sdk and CsWinRT

**To Reproduce**
In.net8 RC1, the Marshal.QueryInterface() method is defined from
public static int QueryInterface (IntPtr pUnk, ref Guid iid, out IntPtr ppv);
Become a
public static int QueryInterface (IntPtr pUnk, in Guid iid, out IntPtr ppv);
Please update the content in WinRT.cs immediately, otherwise the application will not compile

**Expected behavior**
In describe bug

**Version Info**
Windows App SDK 1.4.0: 1.4.230822000
CSWINRT 2.0.3

**Additional context**
None,please fix this bug as soon as possible
![image](https://github.com/microsoft/WindowsAppSDK/assets/49179966/a0e8430e-0bc9-42eb-a110-4f5a606658d0)

**Comment by Gaoyifei1011** [comment]
> Are you using embedded C#/WinRT?

embedded cswinrt? My project uses Microsoft.Management.Deployment.winmd, so I need to install cswinrt nuget package separately. At the same time, after modifying tfm, the project has problems. You can also refer to this issue.
https://github.com/dotnet/runtime/issues/91981

**Comment by dongle-the-gadget** [comment]
The bug is fixed in .NET's side, so I don't think there's any work to be done. In addition, if say we modify it to `in` to C#/WinRT, it would break in the next .NET 8 release, so I don't think it's worth it.

**Comment by Gaoyifei1011** [comment]
> The bug is fixed on .NET's side, so I don't think there's any work to be done. In addition, if say we modify it to `in` in C#/WinRT, it would break in the next .NET 8 release, so I don't think it's worth it.

Well, thank you for your reply. Through the feedback with DotNet, cswinrt, and wasdk, I learned that DotNet's radical modification really caused this problem, and they also made a fix for it. This should be fixed in the rc2 release about a month from now.If you don't have anything else, you can close the issue.

**Comment by manodasanW** [comment]
@Gaoyifei1011 Thanks for catching this breaking change.

**Comment by Psychlist1972** [comment]
@Gaoyifei1011 
I didn't see this bug when I searched on the warning number / text, and so I filed my own #1365  Are you getting a proper error or a warning? I'm trying to understand if it was changed to a warning as the fix, or if there's something else still coming.

**Comment by Gaoyifei1011** [comment]
> @Gaoyifei1011 I didn't see this bug when I searched on the warning number / text, and so I filed my own #1365 Are you getting a proper error or a warning? I'm trying to understand if it was changed to a warning as the fix, or if there's something else still coming.

This bug has been fixed in the.NER 8 rc2 nightly release, however rc2 is not currently available on the official website, the current solution is to downgrade to preview7 and try to update rc2 after it is released
