### ISSUE TITLE
CS9191 Ref/In warning in WinRT.cs with .NET 8 project

### ISSUE THREAD

**Issue by Psychlist1972** [microsoft/CsWinRT#1365]
**Describe the bug**
You know how we generally have to treat warnings as errors here, so this warning should ideally go away.

`CS9191	The 'ref' modifier for argument 2 corresponding to 'in' parameter is equivalent to 'in'. Consider using 'in' instead.	\Generated Files\WinRT.cs`

That points to this code:

```cs
        public void InitalizeReferenceTracking(IntPtr ptr)
        {
            eventInvokePtr = ptr;
            Guid iid = IReferenceTrackerTargetVftbl.IID;
            int hr = Marshal.QueryInterface(ptr, ref iid, out referenceTrackerTargetPtr);
            if (hr != 0)
            {
                referenceTrackerTargetPtr = default;
            }
            else
            {
                // We don't want to keep ourselves alive and as long as this object
                // is alive, the CCW still exists.
                Marshal.Release(referenceTrackerTargetPtr);
            }
        }
```
Specifically, it's the `ref iid` this line:

```cs
int hr = Marshal.QueryInterface(ptr, ref iid, out referenceTrackerTargetPtr);
```

So I recommend either pragma away the warning, or go with the advice. Given that `Marshal.QueryInterface` takes that param as `in` it would seem reasonable to change it.

Thanks.

CSWinrt NuGet 2.0.3
.NET 8 rc1
Visual Studio 2022 17.8.0 Preview 2.0

**Comment by dongle-the-gadget** [comment]
Duplicate of #1358

**Comment by Psychlist1972** [comment]
Thanks. I had searched on the warning text, but that wasn't in that bug. The person in that one said it wouldn't compile at all. I'll follow-up on that thread with my question.
