### ISSUE TITLE
SingleInterfaceOptimizedObject looks like it could be optimized (also, it's not trim/AOT friendly)

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/CsWinRT#1385]
**Describe the bug**

Was looking at `SingleInterfaceOptimizedObject` and noticed the constructor:

https://github.com/microsoft/CsWinRT/blob/71169932920500310921b4c3fadba1e5a99c6138/src/WinRT.Runtime/SingleInterfaceOptimizedObject.net5.cs#L26-L46

It would seem like there's several opportunities for improvement here:
- At least when used from generated projections (eg. for `IDisposable`), the callsite would already know the IID that's being used. There's no need to just pass the projection type and then requiring this to resolve the helper type and use `GuidGenerator` to get the IID. Could we have eg. an overload that also takes the input IID, so callers can just pass that?
- Again at least for generated projections, it seems like callsites would already know which code path will be taken here (ie. whether there will be a vtable type or not from the helper type). Should there be different overloads so the projections could just call those directly, with no need to check the path at runtime? Or perhaps just pass the vtable type directly as a constructor parameter, or something akin to that?
- The second path is completely not AOT friendly (it's still there in the AOT branch too), as it's doing an invoke on `MakeGenericMethod`. Not immediately clear what a proper fix for this would be here (or at least, it would probably require some more general changes that are not just adding or removing a parameter here).

**Comment by manodasanW** [comment]
I will need to review the list of interfaces still using `SingleInterfaceOptimizedObject`, but for the most part, I think there aren't any interfaces remaining still using it as of my PR other than for `IWeakReference` which goes into the else code path for `requireQI`.  For instance, `IDisposable` shouldn't be using it with the changes in PR.

**Comment by Sergio0694** [comment]
Fixed by #1429.
