### ISSUE TITLE
MarshalInspectable<T>.CopyAbiArray is missing

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#1409]
For some WinRT definitions (repro coming), the projection fails to compile:
Error	CS0117	'MarshalInspectable<object>' does not contain a definition for 'CopyAbiArray'

**Comment by Scottj1s** [comment]
see also: https://github.com/microsoft/CsWinRT/commit/b89f261f19dc7eaff19677175cb0754c721bd089

**Comment by manodasanW** [comment]
This is already addressed in the staging branch for the next assembly version change.  Can confirm with repro once available.

https://github.com/microsoft/CsWinRT/blob/28f09d7d94dccdf4fc34efbdd1c573cafe16dad7/src/WinRT.Runtime/Marshalers.cs#L1388

commit: https://github.com/microsoft/CsWinRT/pull/1377/commits/568dd6fc685ec17a608f8734626fdbc6135063c4#diff-7836a0eac5d45d74504408d479fe5233e974dc9953cce1c9664e7ccf9d136945R1357
