### ISSUE TITLE
IID optimizer causes build error for libraries/applications (not projections)

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/CsWinRT#1478]
**Describe the bug**

![image (36)](https://github.com/microsoft/CsWinRT/assets/10199417/520daf45-825b-4f62-9626-47a5f632bb0d)

**To Reproduce**

1. Reference CsWinRT from a library (not projections) or an app.

**Expected behavior**

Should build fine.

**Comment by hez2010** [comment]
You can set `<DebugType>full</DebugType>` to mitigate this issue.

**Comment by manodasanW** [comment]
IIDOptimizer doesn't run in most scenarios anymore, so there shouldn't be a pdb to copy over and fail.
