### ISSUE TITLE
Whether we have necessary to continue to use NativeHandle. GetWindowHandle (parameter: Window) to retrieve a handle to the Window?

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/CsWinRT#1488]
**Describe the bug**

Whether we have necessary to continue to use NativeHandle. GetWindowHandle (parameter: Window) to retrieve a handle to the Window?
我们是否有必要继续使用NativeHandle.GetWindowHandle(parameter:Window) 去检索窗口句柄？

**To Reproduce**
In the early days of the WinUI 3, the Window class and no built-in AppWindow attribute, so had to use WinRT. Interop. WindowNative. GetWindowHandle(parameter: Windows) to retrieve a handle to the Window. However, in Windows app sdk 1.3, the Window class built-in AppWindow property, we can use (IntPtr)AppWindow.Id.Value to get the window handle, through this property, Unnecessary WinRT.Interop interoperability can be avoided. Future versions can consider delete WinRT.Interop.WindowNative.GetWindowHandle (Window) parameter: retrieve Window handle, Use (IntPtr)AppWindow.Id.Value to get the window handle of the current window directly in the documentation?

在早期的 WinUI 3 中，Window类并没有内置AppWindow属性，所以不得不用 WinRT.Interop.WindowNative.GetWindowHandle(parameter:Window)去检索窗口句柄。然而在 Windows app sdk 1.3 中，Window类内置了 AppWindow 属性，我们可以通过 (IntPtr)AppWindow.Id.Value来获取窗口句柄，通过这个属性，可以避免掉不必要的WinRT.Interop互操作。未来版本是否考虑可以删除 WinRT.Interop.WindowNative.GetWindowHandle(parameter:Window) 检索窗口句柄，直接在文档中注明使用 (IntPtr)AppWindow.Id.Value 来获取当前窗口的窗口句柄？

文档（Microsoft docs）https://learn.microsoft.com/zh-cn/windows/apps/develop/ui-input/retrieve-hwnd

**Expected behavior**
None

**Version Info**
Windows app sdk 1.4.2

**Additional context**
None

**Comment by dongle-the-gadget** [comment]
It's still the recommended way to get a window handle, even in C++, so I don't think so.
While yes, the current implementation of `WindowId` for Win32 WinUI 3 windows is just the handle reinterpreted, it might not be for other types of windows, such as system `AppWindow` (well not really applicable here since there's no "official" support for them but it's still a possibility).

**Comment by Gaoyifei1011** [comment]
> It's still the recommended way to get a window handle, even in C++, so I don't think so. While yes, the current implementation of `WindowId` for Win32 WinUI 3 windows is just the handle reinterpreted, it might not be for other types of windows, such as system `AppWindow` (well not really applicable here since there's no "official" support for them but it's still a possibility).

Ok, thank you very much for your answer
