### ISSUE TITLE
Generated code WinRT.IActivationFactoryMethods missing global

### ISSUE THREAD

**Issue by wherewhere** [microsoft/CsWinRT#1496]
**Describe the bug**
Generated code `WinRT.IActivationFactoryMethods` missing `global::`, which course `error CS0234: 命名空间“FullTrustUWP.WinRT”中不存在类型或命名空间名“IActivationFactoryMethods”(是否缺少程序集引用?)`.

![image](https://github.com/microsoft/CsWinRT/assets/27689196/882106ee-67fd-4633-9309-c71607c163ad)

**To Reproduce**
1. Create a winrt class which namespace ending with `.WinRT`
2. Reference it by a C#/WinRT project

**Expected behavior**
Generate `global::WinRT.IActivationFactoryMethods`.

**Version Info**
cswinrt.exe 2.0.6.240201.1

**Comment by Sergio0694** [comment]
Already fixed in `staging/AOT by #1489 🙂

**Comment by manodasanW** [comment]
Addressed in 2.0.7.
