### ISSUE TITLE
Add support for generated COM interfaces

### ISSUE THREAD

**Issue by dongle-the-gadget** [microsoft/CsWinRT#1533]
# Proposal: Add support for generated COM interfaces

## Summary
.NET 8 introduces source generated COM wrappers, which provides a friendly, AOT-safe way to use COM in .NET. Currently for C#/WinRT users, the only way to query into custom COM types is to use the built-in COM interop, which is not AOT-safe at all.

## Rationale
* Better AOT support for custom COM types.

## Important Notes
Sample usage code, using `As<T>`:
```cs
[GeneratedComInterface]
[Guid("3faca0d2-e7f1-4e9c-82a6-404fd6e0aab8")]
internal partial interface IFooNative
{
    void Method(int i);
}

Foo fooObject = new Foo(); // Foo is a WinRT class, in this case.
IFooNative nativeObject = fooObject.As<IFooNative>(); // Casting the Foo object to an "IFooNative" object.
nativeObject.Method(0); // Calling a Method exposed in IFooNative
```
## Open Questions
There are several strategies that I could think of to implement this:
- Reuse `StrategyBasedComWrappers` from the runtime.
- Remodel our existing COM Wrappers implementation.
- Create or remodel an existing `IDynamicInterfaceCastable` implementation, considering that we don't actually need to handle CCWs here 🤔?

**Comment by manodasanW** [comment]
Related #1337
