### ISSUE TITLE
System.NotSupportedException when PublishAot is set to true

### ISSUE THREAD

**Issue by hez2010** [microsoft/CsWinRT#1623]
**Describe the bug**
The below exception occurred in `TypeNameSupport.ResolveGenericType` when `PublishAot` is set to `true` but not running under NativeAOT.

```
System.NotSupportedException: 'Cannot provide generic type from 'Windows.Foundation.IAsyncOperation`1'.'
```

**To Reproduce**

1. Checkout the `aot` branch of https://github.com/hez2010/WinRTServer/tree/aot
2. Run the project directly in VS

**Expected behavior**
No exception.

**Version Info**
Package built from staging/AOT branch.

**Additional context**

`RuntimeFeature.IsDynamicCodeCompiled` will be set to `true` if `PublishAot` is set to `true` in csproj, regardless of whether the executable is published with NativeAOT or not.

**Comment by manodasanW** [comment]
I assume this is a first chance exception you are seeing and that things still work or does it also crash?

**Comment by hez2010** [comment]
You are right. It's a first chance exception. It doesn't crash.

**Comment by manodasanW** [comment]
Yea that is known, I will keep this open to track this until I decide if I want to leave it as is or put in some logic to handle that which in theory isn't really needed as we got type information later on which we use.

**Comment by Gaoyifei1011** [comment]
> Yea that is known, I will keep this open to track this until I decide if I want to leave it as is or put in some logic to handle that which in theory isn't really needed as we got type information later on which we use.

I've seen this happen with a few methods as well
![e8a8632a93f879de2270268f96a97b75](https://github.com/microsoft/CsWinRT/assets/49179966/09096589-e1d6-42f0-b719-c14de2fe1ea8)
