### ISSUE TITLE
Did you forget to generate a 26100 Windows SDK Projection for CsWinRT 2.1.0?

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/CsWinRT#1629]
**Describe the bug**

Did you forget to generate a 26100 Windows SDK Projection for CsWinRT 2.1.0?
是否忘记生成 26100 适配 CsWinRT 2.1.0 的 Windows SDK Projection？

**To Reproduce**

See screenshots

**Expected behavior**

Generating a 26100 Windows SDK Projection for CsWinRT 2.1.0

**Version Info**

CsWinRT 2.1.0-preview
NET SDK 9
Windows SDK 26100

**Additional context**

Screenshots
![image](https://github.com/microsoft/CsWinRT/assets/49179966/66f62e61-1e97-4c91-9bb2-66c8232aa872)

**Comment by manodasanW** [comment]
Shipped with today's preview: https://www.nuget.org/packages/Microsoft.Windows.SDK.NET.Ref/10.0.26100.37-preview
