### ISSUE TITLE
Attached property of type Thickness in a C++/WinRT not working in C# projection

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/CsWinRT#1633]
Attached property of type Thickness in a C++/WinRT Windows Runtime component throwing exception while consuming it from a C# WinUI3 project.
The detailed issue is posted here.
microsoft/microsoft-ui-xaml#9763

**Version Info**
CsWinRT 2.0.7

Any help is greatly appreciated.
Thanks.

**Comment by manodasanW** [comment]
As far as I can tell, a call is being made to `IsContructible` and that is throwing `NotImplementedException`.  And the function implementing `IsConstructible` seems to be generated by the XAML compiler.  Resolving this bug given it doesn't seem to be a CsWinRT issue and there is already a XAML bug to track this issue.

    bool XamlSystemBaseType::IsConstructible() const
    {
        throw ::winrt::hresult_not_implemented {};
    }
