### ISSUE TITLE
NativeAOT with WinUI doesn't work with current instructions

### ISSUE THREAD

**Issue by charlesroddie** [microsoft/CsWinRT#1639]
This documents two failed attempts to get a blank or template app to work with NativeAOT:

## Repro 1
https://github.com/FoggyFinder/AOTRepro

```
dotnet publish -c Release -p:Platform=x64
...\AOTRepro\bin\x64\Release\net8.0-windows10.0.19041.0\win-x64\native>AOTRepro

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'Microsoft.WindowsAppRuntime.dll' or one of its dependencies: Не найден указанный модуль.
   at System.Runtime.InteropServices.NativeLibrary.LoadLibErrorTracker.Throw(String) + 0x6f
   at Internal.Runtime.CompilerHelpers.InteropHelpers.FixupModuleCell(InteropHelpers.ModuleFixupCell*) + 0xfd
   at Internal.Runtime.CompilerHelpers.InteropHelpers.ResolvePInvokeSlow(InteropHelpers.MethodFixupCell*) + 0x2f
   at Microsoft.Windows.Foundation.UndockedRegFreeWinRTCS.NativeMethods.WindowsAppRuntime_EnsureIsLoaded() + 0x24
   at Microsoft.Windows.Foundation.UndockedRegFreeWinRTCS.AutoInitialize.AccessWindowsAppSDK() + 0x3e
   at Internal.Runtime.CompilerHelpers.StartupCodeHelpers.RunInitializers(TypeManagerHandle, ReadyToRunSectionType) + 0x39
   at Internal.Runtime.CompilerHelpers.StartupCodeHelpers.RunModuleInitializers() + 0x36
   at AOTRepro!<BaseAddress>+0x254fc3
```

## Repro 2, trying to keep close to online instructions
https://github.com/charlesroddie/WinUITemplate

The code is given by:

1. Use Visual Studio Version 17.11.0 Preview 2.0
2. new Packaged WinUI project
3. Add, as per instructions in https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#required-c-project-changes-for-16-experimental1 :
```
<TargetFramework>net8.0-windows10.0.22621.0</TargetFramework>
<WindowsSdkPackageVersion>10.0.22621.35-preview</WindowsSdkPackageVersion>
<PublishAot Condition="'$(ExcludeRestorePackageImports)'=='true'">true</PublishAot>
<PublishAot Condition="'$(Configuration)'=='Release'">true</PublishAot>

<PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.1.0-prerelease.240602.1" />
```
4. This gives errors, so also update (as https://github.com/FoggyFinder/AOTRepro does)

```
<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.3233" />
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240531000-experimental1" />
```

This gives the current state of the repo.

Then:
 ```
dotnet publish -c Release -p:Platform=x64
...\WinUITemplate\WinUITemplate\bin\Release\net8.0-windows10.0.22621.0\win-x64\publish\WinUITemplate.exe

```

Expected: window shows with "Click me" button.
Actual: Nothing happens

**Comment by manodasanW** [comment]
Both errors look related.  Are you trying to do an unpackaged app or a packaged app?  If unpackaged, then you would need to make sure the WindowsAppSDK native bits are also in the output which can be done by setting the `WindowsAppSDKSelfContained` property to true.  If packaged, then I will need to follow up to figure out the exact `dotnet publish` command to get a packaged app generated.

**Comment by charlesroddie** [comment]
Thanks. Next we'll try a visual studio build instead of `dotnet publish` although if `dotnet publish` could work that would be great. We want a packaged app.

**Comment by FoggyFinder** [comment]
> https://github.com/FoggyFinder/AOTRepro

@manodasanW I think I relied too much on my past experience with Avalonia + NativeAot where exe from native folder was ready to use without any additional steps. It seems it's not true for WinUi3 and one have to copy bunch of dll. Exe from publish folder works but it's unclear how many files there are safe to remove.

But on attempt to start app from VS with aot enabled I get - `The system cannot find the file specified` error:

![image](https://github.com/microsoft/CsWinRT/assets/16510738/ec61d9f6-cf91-4b57-b6fe-1942bce10300)

**Comment by dongle-the-gadget** [comment]
I think something's wrong with your VS installation.

In addition, your DLL problem comes from your build settings: by default, the project configurations instruct MSBuild Framework (which VS uses) to build your app packaged and framework-dependent (meaning you use MSIX, and users must install the Windows App SDK framework packages).

However, you're using `dotnet publish` which uses MSBuild Core (unsupported by Windows App SDK), the right targets aren't being invoked and you don't get an MSIX package. This causes your EXE to fail since it relies on MSIX's dependency system.

**Comment by FoggyFinder** [comment]
> I think something's wrong with your VS installation.

If this is the case then why non-aot version just works?

**Comment by dongle-the-gadget** [comment]
Does your program open if you open it from Start?

**Comment by FoggyFinder** [comment]
> Does your program open if you open it from Start?

yes, but only non-aot version
aot one does nothing

does both aot & non-aot work on your system ?

**Comment by dongle-the-gadget** [comment]
Yup both works here.

**Comment by charlesroddie** [comment]
I can get AOT compilation on my system now. So closing this.
