### ISSUE TITLE
Windows.ApplicationModel.Package.Current.Id.ProductId throws System.InvalidCastException

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [microsoft/CsWinRT#1653]
## **Describe the bug**
When I try to access `Windows.ApplicationModel.Package.Current.Id.ProductId` in a .NET 9.0 Preview 5 MAUI app on Windows/WinUI 3, I get an exception.

### Output → Debug
Output → Debug window says:
```
Exception thrown: 'System.InvalidCastException' in WinRT.Runtime.dll
Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
```

### Immediate Window
Immediate Window with `Windows.ApplicationModel.Package.Current.Id` says for `ProductId`:
`'Windows.ApplicationModel.Package.Current.Id.ProductId' threw an exception of type 'System.InvalidCastException'`

## **To Reproduce**
1. Create a new .NET MAUI App with .NET 9.0 Preview 5.
2. Try one of the following:
    a) In code, try to access `Windows.ApplicationModel.Package.Current.Id.ProductId`. (You need to put `#if WINDOWS` around it.)
    b) Type `Windows.ApplicationModel.Package.Current.Id` in the Immediate Window while debugging and see what happens for `ProductId`.

## **Expected behavior**
No exception is thrown and ProductId is returned.

## **Version Info**
- WinRT.Runtime.dll Version: 2.0.4.44211
- .NET SDK 9.0 Preview 5
- .NET MAUI 9.0 Preview 5

**Comment by Gaoyifei1011** [comment]
> ## **Describe the bug**
> When I try to access `Windows.ApplicationModel.Package.Current.Id.ProductId` in a .NET 9.0 Preview 5 MAUI app on Windows/WinUI 3, I get an exception.
> 
> ### Output → Debug
> Output → Debug window says:
> 
> ```
> Exception thrown: 'System.InvalidCastException' in WinRT.Runtime.dll
> Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
> ```
> 
> ### Immediate Window
> Immediate Window with `Windows.ApplicationModel.Package.Current.Id` says for `ProductId`: `'Windows.ApplicationModel.Package.Current.Id.ProductId' threw an exception of type 'System.InvalidCastException'`
> 
> ## **To Reproduce**
> 1. Create a new .NET MAUI App with .NET 9.0 Preview 5.
> 2. Try one of the following:
>    a) In code, try to access `Windows.ApplicationModel.Package.Current.Id.ProductId`. (You need to put `#if WINDOWS` around it.)
>    b) Type `Windows.ApplicationModel.Package.Current.Id` in the Immediate Window while debugging and see what happens for `ProductId`.
> 
> ## **Expected behavior**
> No exception is thrown and ProductId is returned.
> 
> ## **Version Info**
> * WinRT.Runtime.dll Version: 2.0.4.44211
> * .NET SDK 9.0 Preview 5
> * .NET MAUI 9.0 Preview 5

Did you forget the platform requirements? Windows phone only
![Screenshot_2024-06-29-19-47-37-168_mark via](https://github.com/microsoft/CsWinRT/assets/49179966/5a818b67-0bce-44fb-b92a-add59676d164)

**Comment by TommiGustafsson-HMP** [comment]
Thanks. I did not see that it was Windows Phone only, because I was working in Visual Studio and the exception was a bit weird.
