### ISSUE TITLE
Conversion to generic interface breaks CCWs for collection types

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/CsWinRT#1663]
**Describe the bug**

**To Reproduce**

Triggered by [this `ItemsSource` binding](https://github.com/Sergio0694/ComputeSharp/blob/b05a118d24f3b26457c9220c551e5bef5849d1c7/samples/ComputeSharp.SwapChain.WinUI/Views/MainWindow.xaml#L80). The viewmodel property is [this one](https://github.com/Sergio0694/ComputeSharp/blob/b05a118d24f3b26457c9220c551e5bef5849d1c7/samples/ComputeSharp.SwapChain.WinUI/ViewModels/MainViewModel.cs#L87).

```csharp
public ShaderRunnerViewModel[] ComputeShaderOptions { get; } = ...
```

Works.

```csharp
public IReadOnlyList<ShaderRunnerViewModel> ComputeShaderOptions { get; } = ...
```

Crashes.

> [!NOTE]
> I've tried using an array expression instead of a collection expression, I still get the same exact crash.

**Stack trace**

![image](https://github.com/microsoft/CsWinRT/assets/10199417/f6c268d0-c411-4ebd-9af6-49e43fb46ea3)

**Expected behavior**

Should work fine

**Version Info**

Latest from staging/AOT (016e9ecc0b130d066a18860098e5fa92fa0e9177)

**Additional context**

Possibly related to #1661.

**Comment by manodasanW** [comment]
Ignoring the collection expression issue which is tracked separately, this looks to be because we are failing to detect the get property initializer it seems.  Doing the below instead does work.

    public IReadOnlyList<ShaderRunnerViewModel> ComputeShaderOptions { get; } =
->
    public IReadOnlyList<ShaderRunnerViewModel> ComputeShaderOptions = new ShaderRunnerViewModel[]
