### ISSUE TITLE
IDynamicInterfaceCastable is not supported exception when List.AddRange() is called with AOT compilation

### ISSUE THREAD

**Issue by lhak** [microsoft/CsWinRT#1671]
**Describe the bug**

The windows community toolkit contains the equivalent to this code (see https://github.com/CommunityToolkit/Windows/blob/c532c1128de4fcb6bb0cb6f5f0918e96fbfdcaf4/components/Helpers/src/NetworkHelper/ConnectionInformation.cs#L53-L58) 

```csharp
var profile = NetworkInformation.GetInternetConnectionProfile();

var names = profile.GetNetworkNames();

List<string> networkNames = new();

if (names?.Count > 0)
{
  networkNames.AddRange(names);
}

```

The AddRange() method throws an exception with the message "IDynamicInterfaceCastable is not supported for generic type 'System.Collections.Generic.ICollection`1[System.String]" when used with AOT compilation

**To Reproduce**

1. Use the code snippet above

**Expected behavior**

**Version Info**

CsWinRT compiled from staging/AOT branch

**Additional context**

**Comment by dongle-the-gadget** [comment]
This is probably due to NativeAOT's inability to generate generic types AFAIK (at least, without using unsupported methods like runtime directives). That said, can you try to cast the `names` variable to `IEnumerable` (not `IEnumerable<T>`) and use that?

**Comment by lhak** [comment]
@dongle-the-gadget I am not sure if I understand you correctly but `names` is already of type `IReadOnlyList<string>`. Adding an explicit cast does not change anything

I have looked a bit closer and the exception from calling List.AddRange() is actually caused by code in the dotnet runtime which corresponds to (and can be used to reproduce this crash):

```csharp
if (names is ICollection<string> c)
{
	...
}
```

I do not believe that IReadOnlyList<T> can be cast to ICollection<T>, but I guess this line should not throw any exceptions.

**Comment by dongle-the-gadget** [comment]
It throws currently as C#/WinRT tries to see if it’s `IDictionary<TKey, TValue>` or `IList<T>`, however `MakeGenericType` is not allowed under NativeAOT.

**Comment by lhak** [comment]
Is this something that might be fixed in cswinrt or should the toolkit code be updated to use a foreach() loop? I guess that happens anyway when not using AOT because IReadOnlyList should not be castable to ICollection.

**Comment by dongle-the-gadget** [comment]
It does not happen in JIT, as C#/WinRT generates dynamic code to handle that scenario. In AOT, however, dynamic code generation is not allowed, and as such C#/WinRT throws an exception when .NET tries to determine whether it works.
