### ISSUE TITLE
NuGet release 2.1.1 isn't tagged in this repo and isn't shown as a release with release notes

### ISSUE THREAD

**Issue by echoix** [microsoft/CsWinRT#1714]
**Describe the bug**

On this package's NuGet page, https://www.nuget.org/packages/Microsoft.Windows.CsWinRT/2.1.1?_src=template#releasenotes-body-tab, the latest version 2.1.1 refers to https://github.com/microsoft/CsWinRT/releases to see release notes, but the new version isn't present yet.

**To Reproduce**

1. Go to https://www.nuget.org/packages/Microsoft.Windows.CsWinRT/2.1.1?_src=template#releasenotes-body-tab
2. Follow the release notes link https://github.com/microsoft/CsWinRT/releases
3. Try finding release 2.1.1 (not present)
4. Go to the tags page.
5. Try finding the 2.1.1 tag (not present)

**Expected behavior**

Binary NuGet package releases are based on the same tag as the ones in this repo, and the packages in GitHub release artifacts match the ones on NuGet.

**Version Info**

About CsWinRT 2.1.1

**Additional context**

**Comment by manodasanW** [comment]
Release notes / tags will be published soon.

**Comment by manodasanW** [comment]
Published.
