### ISSUE TITLE
Dictionary fails to cast to IReadOnlyDictionary

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/CsWinRT#1726]
**Describe the bug**
CsWinRT throws when passing a Dictionary<TKey, TValue> to a WinRT method that expects a `IReadOnlyDictionary<TKey, TValue>` as parameter.
Wrapping the dictionary in its own non-generic type works around the issue.

**Version Info**
2.1.1

**Comment by manodasanW** [comment]
@FrayxRulez are you able to provide a minimal repro for this issue.  I tried to repro it with a simple function that takes a `IReadOnlyDictionary<string, int>` and passed a `Dictionary<string, int>` instance, but that seems to work.

**Comment by FrayxRulez** [comment]
Here you go, specifically `Microsoft.UI.Xaml.Controls.IAnimatedVisualSource2.Markers` used by `Microsoft.UI.Xaml.Controls.AnimatedIcon`
[App1.zip](https://github.com/user-attachments/files/16907240/App1.zip)

**Comment by manodasanW** [comment]
@FrayxRulez Thanks for the repro, I tried it out.  When I launched it, I did notice a bunch of InvalidCastException.  I also noticed that there were 2 warnings for types not marked partial which is required for the source generator to be able to make them AOT compatible.  Once I made both of them partial, the crash seems to have gone away.

 warning CsWinRT1028: Class '**PowerSaving_AnimatedVisual_UAPv15**' implements WinRT interfaces but isn't marked partial.  Type should be marked partial for trimming and AOT compatibility if passed across the ABI. (https://github.com/microsoft/CsWinRT/tree/master/src/Authoring/WinRT.SourceGenerator/AnalyzerReleases.Shipped.md)
 
 warning CsWinRT1028: Class '**PowerSaving_AnimatedVisual_UAPv7**' implements WinRT interfaces but isn't marked partial.  Type should be marked partial for trimming and AOT compatibility if passed across the ABI. (https://github.com/microsoft/CsWinRT/tree/master/src/Authoring/WinRT.SourceGenerator/AnalyzerReleases.Shipped.md)

**Comment by FrayxRulez** [comment]
Ops, sorry, I actually didn’t test the repro before sending and I just assembled it on the spot by dropping the animation from the main code base that’s actually UWP. 
I forgot however to set the State property to the AnimatedIcon in the XAML, setting it to any value will cause the Markers property to be evaluated and you’ll be able to reproduce the crash.

**Comment by FrayxRulez** [comment]
Ops, sorry, I actually didn’t test the repro before sending and I just assembled it on the spot by dropping the animation from the main code base that’s actually UWP. 
I forgot however to set the State property to the AnimatedIcon in the XAML, setting it to any value will cause the Markers property to be evaluated and you’ll be able to reproduce the crash.
