### ISSUE TITLE
Some shutdown issues with WinUIDesktopSample (launching without the wapproj)

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#175]
If you close the app without clicking the button, the debugging session never terminates.  Output windows shows a couple dozen threads terminate and this :
  Exception thrown at 0x00007FFCECEF3E49 (KernelBase.dll) in WinUIDesktopSample.exe: WinRT originate error - 0x80000013 : 'The given object has already been closed / disposed and may no longer be used.'.
But the app stays running.

If you close the app after clicking the button, you get the same 0x80000013 and then an AV with App.Start at the top of the stack:
Exception thrown at 0x00007FFCECEF3E49 (KernelBase.dll) in WinUIDesktopSample.exe: WinRT originate error - 0x80000013 : 'The given object has already been closed / disposed and may no longer be used.'.
Exception thrown at 0x00007FFC4DC0981D (Microsoft.UI.Xaml.dll) in WinUIDesktopSample.exe: 0xC0000005: Access violation reading location 0x00000000000000B0.

Microsoft.UI.Xaml.dll!00007ffc4dc0981d()
...
[Managed to Native Transition]	
WinUIProjection.dll!ABI.Microsoft.UI.Xaml.IApplicationStatics.Start(Microsoft.UI.Xaml.ApplicationInitializationCallback callback)

**Comment by Scottj1s** [comment]
no longer repros

**Comment by dajbych** [comment]
@Scottj1s I'm experiencing the same issue. App window opens just fine, but when it closes it raises an exception.

Single-project MSIX Packaging Tools for VS 2019: 0.9.10.2110211
Windows App SDK: 1.0.0.50489432
Microsoft.WindowsAppSDK: 1.0.0-preview3

`Exception thrown at 0x00007FFBAFD84F99 (KernelBase.dll) in WinUI3App.exe: WinRT originate error - 0x80000013 : 'The given object has already been closed / disposed and may no longer be used.'.`

Version: 10.0.19041.1288 (WinBuild.160101.0800)
Original Location: C:\Windows\System32\combase.dll
