### ISSUE TITLE
Perf: Minimize Heap Allocations: use disposable ref structs

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#184]
Minimize heap allocations for marshalers by eliminating explicit try/finally and adopting ref structs with non-IDisposable Dispose and 'using var ...' pattern, as well as passing marshalers to FromAbi by ref so they can be conditionally disposed.

**Comment by BenJKuhn** [comment]
This has largely been implemented, though there may still be some corner cases that could benefit from this optimization. Since the bulk of the work is done, we're closing this issue and can revisit additional improvements if data suggests a need to.
