### ISSUE TITLE
Bug: Usage of System.Runtime.InteropServices.GuidAttribute in WinMD

### ISSUE THREAD

**Issue by shmuelie** [microsoft/CsWinRT#1852]
### Description

When setting a GUID on public types, CsWinRT will include the GUID on the type in the WinMD. While a very nice feature that IDL based WinMDs can't do, because the GUID is added using the `System.Runtime.InteropServices.GuidAttribute` type, the WinMD isn't valid and causes warnings when referenced by things that don't understand it (like .NET Native). I would vote for keeping the GUID, just using `Windows.Foundation.Metadata.GuidAttribute` instead.

### Steps To Reproduce

1. Create a public type in a CsWinRT Authoring project
2. Add an explicit GUID for the public class
3. Reference the generated WinMD in a UWP project

### Expected Behavior

Either:
1. Don't include the GUID
2. Use `Windows.Foundation.Metadata.GuidAttribute` instead of `System.Runtime.InteropServices.GuidAttribute`

### Version Info

CsWinRT: 2.1.6
.NET SDK: 9.0.100-rc.2.24474.11
Windows SDK: 10.0.26100.0

**Comment by dongle-the-gadget** [comment]
My own thoughts on this issue:
1. CsWinRT shouldn't have put the System type in, you're right about that.
2. I don't think replacing the System type to Windows type would be great, since this has shipped in production and the System type is the more "canonical" way of defining the type's GUID.
3. If we were to keep both as valid ways, what happens if they disagree (that is, the Windows GUID and System GUID are different)

**Comment by shmuelie** [comment]
My main reason for wanting to keep the GUID in there is that when using the WinMD for MBM with COM activation the IID needed will be in the WinMD but the CLSID won't, meaning you need another way to share it.

**Comment by manodasanW** [comment]
I will need to take a look at this to see how we are doing the custom mapping, but one thought is we could support both (specifying `Windows.Foundation.Metadata.GuidAttribute` and `System.Runtime.InteropServices.GuidAttribute` which we map to `Windows.Foundation.Metadata.GuidAttribute`).  If both GUIDs are specified and are different, we could detect that and issue a diagnostic for it.  Thoughts?

**Comment by shmuelie** [comment]
Issue is that `System.Runtime.InteropServices.GuidAttribute` shouldn't be in WinMDs

**Comment by dongle-the-gadget** [comment]
> My main reason for wanting to keep the GUID in there is that when using the WinMD for MBM with COM activation the IID needed will be in the WinMD but the CLSID won't, meaning you need another way to share it.

In that case I suppose we don't need any further changes other than excluding the System GUID, since currently CsWinRT just ignores System GUID in classes.

**Comment by shmuelie** [comment]
At minimum removing `System.Runtime.InteropServices.GuidAttribute` will fix the issue. Adding support for converting to `Windows.Foundation.Metadata.GuidAttribute` in the WinMD is just a nice to have
