### ISSUE TITLE
Generator misses `List<Type>` expressions produced by some LINQ calls

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/CsWinRT#1864]
### Description

It seems the generator is missing `List<Type>` expressions in some scenarios, which then fail when assigned to `ItemsSource` properties.

### Steps To Reproduce

```csharp
public sealed partial class ItemsViewModel : ObservableObject
{
    public IReadOnlyList<GenreItem> Items { get; }

    public ItemsViewModel()
    {
        Items = GetItems();
    }

private IReadOnlyList<Item> GetItems()
{
    var items =
    SomeCollection
        .Select((item, index) => new Item
        {
            SomeProp = item.Prop
        })
        .ToList();

    return items;
}
```

### Expected Behavior

CCW vtable info for `List<Item>` should be generated.

### Version Info

No CCW vtable is generated, so you get `ArgumentException` when assigning to `ItemsSource`.

### Additional Context

- CsWinRT 2.1.6

**Comment by manodasanW** [comment]
The source generator correctly detects the simplified version above without issue.  It only becomes an issue when new Item initialization makes use of other source generated variables as in the original repo and then symbol resolution doesn't seem to have info.  Replacing var with the actual type or using the new opt-in attributes would workaround this issue when source generated variables are used during initialization.

**Comment by Sergio0694** [comment]
Can confirm using explicit types worked, thank you! Closing this as by design then 🙂
