### ISSUE TITLE
Bug: Runtime error occurred for scenario "Create a C#/WinRT component, and consume it from C++/WinRT"

### ISSUE THREAD

**Issue by LegendaryBlair** [microsoft/CsWinRT#1874]
### Description

Following this doc step by step https://learn.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/create-windows-runtime-component-cswinrt, the build was successful. But it does not work in the runtime, an error occurred when the code executes to the line `"AuthoringDemo::Example ex;"` in the following C++ console app.

```
#include "pch.h"
#include "iostream"

using namespace winrt;
using namespace Windows::Foundation;

int main()
{
    init_apartment();

    AuthoringDemo::Example ex;
    ex.SampleProperty(42);
    std::wcout << ex.SampleProperty() << std::endl;
    std::wcout << ex.SayHello().c_str() << std::endl;
}
```

Exception message:
Exception thrown at 0x00007FF882C1831A in CppConsoleApp.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000BB353CF388.

Some inner hresult:
HRESULT_FROM_WIN32(ERROR_BAD_EXE_FORMAT) : %1 is not a valid Win32 application.

### Steps To Reproduce

1. Follow the doc https://learn.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/create-windows-runtime-component-cswinrt
2. using project reference to consume Cs component.
3. Build successfully
4. Runtime exception occurred

### Expected Behavior

Run successfully

### Version Info

VS Version 17.11.6
Authoring Demo csproj looks like this
![Image](https://github.com/user-attachments/assets/270fde52-93b1-47ed-9487-887c06d683d9)

**Comment by LegendaryBlair** [comment]
I figured out that we need to configure the solution to target to both x64 or x86 platform, then it works.

**Comment by hoshiizumiya** [comment]
I met the same error when I try to use WinUI3 C# class library project(use xaml UserControl) for C++/WinRT WinUI3 project. Could you please give more detials about it? I also met xaml intellisense error tip for _XLS0503  Cannot add a value of type 'xxxUserControl' to a collection or dictionary of type 'UIElementCollection'._ .But I noticed that all C# class lib (include nuget paks for it) automatically added to the final build folder(AppX)

**Comment by manodasanW** [comment]
@hoshiizumiya Can you clarify what is the error you got and the call stack?  The IntelliSense error might be related to https://github.com/microsoft/microsoft-ui-xaml/issues/8284
