### ISSUE TITLE
Validate VS Debugger UX for WinRT using CsWinRT generated source

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [microsoft/CsWinRT#201]
Debugging UX checklist:

- [ ] viewing properties in the Locals/Auto/Watch windows for RCW WinRT components.
- [ ] viewing properties in the Locals/Auto/Watch window for objects that previously were managed WinRT objects and now are something else.
- [ ] showing an exception for WinRT APIs that failed and provided `IRestrictedErrorInfo`.
- [ ] post-mortem crash viewing for failures that created a stowed exception.

**Comment by tommcdon** [comment]
FYI @caslan

**Comment by BenJKuhn** [comment]
We believe most of these issues, if not all, have been addressed since this issue was filed. Closing this issue. Please create new (separate) issues for any lingering concerns.
