### ISSUE TITLE
Evaluate behavior of existing products that provide WinRT interop features

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#217]
Brought up in recent sync.  First step is to identify third-party apps/libraries that provide WinRT interop features of some kind, and evaluate their behavior with C#/WinRT.

**Comment by Scottj1s** [comment]
Examples: 
https://github.com/windows-toolkit/Lottie-Windows/

**Comment by AdamBraden** [comment]
No ask. already working with folks like Lottie
