### ISSUE TITLE
Reflection APIs return CSWinRT projected artifacts

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#265]
The below code is valid in UWP, but breaks in .NET5:

```csharp
foreach (var color in typeof(Microsoft.UI.Colors).GetRuntimeProperties())
{
   _colorNames[(Windows.UI.Color)color.GetValue(null)] = color.Name;
}
```

A fix/workaround was to change the code to:

```csharp
foreach (var color in typeof(Microsoft.UI.Colors).**GetProperties(BindingFlags.Public | BindingFlags.Static)**
{
   _colorNames[(Windows.UI.Color)color.GetValue(null)] = color.Name;
}
```

The reason being `GetRuntimeProperties` returns the `ThisPtr`, which is a property generated in the cs/winrt projection. I think this is somewhat related to #263.

/cc @mikehillberg @azchohfi

**Comment by AdamBraden** [comment]
using ThisPtr as a field would fail when you are enumerating fields.

**BreakingChange** for reflection code that needs to be doc'd.

**Comment by angelazhangmsft** [comment]
doc'ed in [rc2 breaking changes](https://github.com/microsoft/CsWinRT/blob/master/docs/breakingchanges-rc2.md)
