### ISSUE TITLE
Can't assign a C# type derived from a projected type to a projected type's property

### ISSUE THREAD

**Issue by llongley** [microsoft/CsWinRT#276]
See [this repro app](https://github.com/microsoft/CsWinRT/files/4625242/CsWinRtProjectionTest.zip) for an example.  If we assign an instance of the projected type VirtualizingLayout to the Layout property on ItemsRepeater, everything is fine.  However, if we assign an instance of a type derived from VirtualizingLayout that otherwise changes nothing, we crash when we call `pInstance->GetRuntimeClassName(&hRuntimeClassName)`.

**Comment by AdamBraden** [comment]
@llongley - believe this is fixed in latest changes.

**Comment by Scottj1s** [comment]
most likely a dupe of #347
