### ISSUE TITLE
Can't set a property of type Windows.Foundation.Size in XAML

### ISSUE THREAD

**Issue by llongley** [microsoft/CsWinRT#277]
See [this repro app](https://github.com/microsoft/CsWinRT/files/4625457/CsWinRtProjectionTest.zip).  It crashes on startup when we try to assign a value of type Size to a property.

**Comment by Scottj1s** [comment]
@Stevenbrix any input on this?

**Comment by stevenbrix** [comment]
I'll take a look now

**Comment by stevenbrix** [comment]
[WinUIDesktopCsPreview1.zip](https://github.com/microsoft/CsWinRT/files/4653869/WinUIDesktopCsPreview1.zip)

I created a repro app based off the Preview1, and am running into a compiler error:
> WMC0026    Cannot add 'CustomType' into the dictionary property 'Resources', type must be 'Object'  

We'll need to address the issue with the compiler first

**Comment by AdamBraden** [comment]
@stevenbrix - is this our issue?

**Comment by stevenbrix** [comment]
I don't know, it would be worth keeping this open so that we can test/validate once we update our bits to be on the latest cswinrt and .net.

**Comment by AdamBraden** [comment]
@stevenbrix - can you confirm if this still repos?

**Comment by stevenbrix** [comment]
I couldn't build the repro app that @llongley attached as it was quite old. But I was able to build this:
```
        <local:UserControl1 MySize="30,30" x:Name="bar"/>
        <TextBlock Text="{x:Bind bar.MySize}"/>
```

Where `UserControl` is defined like this:

```csharp
    public sealed partial class UserControl1 : UserControl
    {
        public UserControl1()
        {
            this.InitializeComponent();
        }

        public Size MySize
        {
            get;
            set;
        }
    }
```

And it worked fine. @llongley do you know if this is what your repro was testing?

**Comment by llongley** [comment]
I believe that that was what I was testing here, yes - assigning a value to a property of type Size caused a crash.
