### ISSUE TITLE
Microsoft.Windows.SDK.Contracts

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/CsWinRT#283]
How does C#/WinRT relate to the [Microsoft.Windows.SDK.Contracts nuget packages](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts)?

**Comment by manodasanW** [comment]
The Microsoft.Windows.SDK.Contracts nuget package works with projects using compilers / runtimes that have knowledge of WinRT / WinMDs.  The [Microsoft.Windows.SDK.NET nuget package](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET) provides the same APIs as the contracts nuget package (excluding XAML as it has been undocked as WinUI) but as assemblies instead and works with any project targeting .NET 5 or .NET Standard 2.0.  These assemblies were generated by running the CsWinRT tool on the WinRT WinMDs.

**Comment by mqudsi** [comment]
Thanks for this info. The new release w/ support for UWP via WinRT is kind of a black box.

Do we have to do anything to get `IAsyncOperation` working under .NET 5? In a new WinUI 3 Desktop project using microsoft.windows.sdk.net and CsWinRT, Roslyn keeps complaining that IAsyncAction/IAsyncOperation/etc. are all defined in an assembly that's not installed (suggesting a reference to Windows.winmd). However importing any other references causes a duplicate/ambiguous definition error because they're defined twice.

**Comment by Scottj1s** [comment]
@mqudsi - do you have a repro?  microsoft.windows.sdk.net provides the projection for all IAsync* interfaces, as well as AsTask extensions, so user code should never deal directly with the async interfaces.  Also, the cswinrt nuget contains a build target to explicitly remove the windows.winmd reference, to prevent duplicate type definitions.

**Comment by hansmbakker** [comment]
Will the [Microsoft.Windows.SDK.NET nuget package](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET) be provided for earlier Windows 10 releases as well? I see it is now only available for 19041? Or does this release work for older builds as well?

Will this nuget package also include warnings when using an api that you need to feature-check on older builds?

**Comment by hansmbakker** [comment]
Some more questions:
- Will the [Microsoft.Windows.SDK.NET nuget package](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET) be provided for earlier Windows 10 releases as well? I see it is now only available for 19041? Or does this release work for older builds as well?
- Will this nuget package also include warnings when using an api that you need to feature-check on older builds?
- If you create a `netstandard2.0` library using the `Windows.Devices.Bluetooth` APIs via the `Microsoft.Windows.SDK.NET` nuget package, will it allow you to reference it from an UWP head project?

**Comment by smourier** [comment]
Another simple question: why should I use Microsoft.Windows.SDK.NET instead of Microsoft.Windows.SDK.Contracts ? Why should I reference "as assemblies" instead of "as contract"? Is the reason related to .NET Core?

**Comment by hansmbakker** [comment]
@smourier: I believe with .Net 5.0 the compiler will not understand anymore what contract references are. That logic is put in a separate tool (CsWinRT) that creates assemblies ("dlls") from the contracts, that the compiler can still work with.

**Comment by smourier** [comment]
@hansmbakker  - I have that impression too (and this pretty recent article goes in that direction: https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/), but I'd like a confirmation. What I like with the current Contract nuget, is I don't have to ship anything aside my application. I'm wondering what that means in terms of deployment. It looks like in the future we'll have to ship half of Windows or so, aside our program...

**Comment by manodasanW** [comment]
> Will the [Microsoft.Windows.SDK.NET nuget package](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET) be provided for earlier Windows 10 releases as well? I see it is now only available for 19041? Or does this release work for older builds as well?

Currently we have released the package for 18362 and it has the projection for all the WinRT APIs released up to that version.  Applications built using it should be compatible with both previous and later versions of Windows with one caveat.  For previous versions of Windows for which your application is supported on, you need to ensure that the WinRT APIs you use are supported on it.  If they aren't, you will need to either do feature light up for those APIs as discussed [here](https://blogs.windows.com/windowsdeveloper/2015/09/15/dynamically-detecting-features-with-api-contracts-10-by-10/) or avoid using those APIs.  We haven't decided yet for what other versions we will be releasing the package for and when.

> Will this nuget package also include warnings when using an api that you need to feature-check on older builds?

There are currently no warnings for this case, but this is a good suggestion and I have opened #293 to track it.

> If you create a `netstandard2.0` library using the `Windows.Devices.Bluetooth` APIs via the `Microsoft.Windows.SDK.NET` nuget package, will it allow you to reference it from an UWP head project? I'm getting errors with it, and created #290 for it

I responded to this in the issue you created for it.

> Another simple question: why should I use Microsoft.Windows.SDK.NET instead of Microsoft.Windows.SDK.Contracts ? Why should I reference "as assemblies" instead of "as contract"? Is the reason related to .NET Core?

As mentioned in the other responses and in my initial response, the `Microsoft.Windows.SDK.NET` package is meant to be used with compilers / runtimes that don't have knowledge of WinRT (i.e .NET 5 as mentioned) and it currently distributes the projection with your app.  For compilers / runtimes that do have knowledge of WinRT, you can continue to use the `Microsoft.Windows.SDK.Contracts` package.

**Comment by manodasanW** [comment]
Closing as I believe all questions in this issue have been addressed.
