### ISSUE TITLE
Default values of custom type mappings are potentially problematic

### ISSUE THREAD

**Issue by benstevens48** [microsoft/CsWinRT#285]
Some WinRT types are projected onto built-in types in other languages, such as Windows.Foundation.DateTime is projected to System.DateTimeOffset in C#. However, one issue with this is that the default values of the types are different. This is quite unintuitive and can lead to bugs. For example, I have a FileTimeStamp property in my C++/WinRT component which is a Windows.Foundation.DateTime. I am happy with the default value of the year 1601 for this as it's earlier than any file I will be using, so I initialize it to its default value. I then use the component in my C# app. At some point I want to reset the FileTimeStamp  to its default value. So I do FileTimeStamp   = new DateTimeOffset or FileTimeStamp = default(DateTimeOffset), thinking that I've reset it to the default, but in fact I've reset it to 1AD or something, so then this FileTimeStamp is earlier than it should be, which causes issues.

If no better solution is found, I'd like to propose adding a static default property `Windows.Foundation.DateTime.Default` or something. This should not involve a call through the ABI boundary and the value should be available at compile time, so it would be no more expensive than new DateTimeOffset(). It should also be documented in the Windows.Foundation.DateTime documentation that you may run into difficulties if relying on default values.

I don't know if this issue arises for any other types. If it does, the same sort of suggestion should be considered.

**Comment by Scottj1s** [comment]
Yes, that's an impedance for mapped value types.  I like your suggestion, which is probably about the best we can do.  The projection simply doesn't know, in general, when a value type presented to it was constructed by default.  There could be some value types that have unique enough default values that we could safely assume they were default created.  But ideally, we'd have a consistent approach for all types - principle of least surprise.

**Comment by AdamBraden** [comment]
Each projection (C#/C++) will need to call out differences in WinRT types defaults.

**Comment by AdamBraden** [comment]
@angelazhangmsft - confirm if we are compatible with NetNative/Netcore3. If so, close

**Comment by Scottj1s** [comment]
The suggestion above has the drawback of being biased toward C++/WinRT.  That is, the zero-initialized state of a projected C++/WinRT value type determines the default value of the corresponding WinRT type.  Instead of picking a winner, a C# source analyzer could be used to flag default-initialized projected C# value types.

**Comment by angelazhangmsft** [comment]
The initialized DateTimeOffset value is consistent across NetCore3, Net5, and UWP/NetNative. {1/1/0001 12:00:00 AM +00:00}

**Comment by benstevens48** [comment]
@angelazhangmsft and @AdamBraden - this issue wasn't really about differences between C#/WinRT and .Net Native. It was about differences between the .Net projections and other language projections like C++/WinRT. (So it applies to .Net Native as well but I thought C#/WinRT could improve matters).

@Scottj1s - Perhaps it's best to start by considering the specific case of Windows.Foundation.DateTime - this was mainly what I was thinking about when I posted the issue, then I generalized it but that might have been premature.

In this case a source analyzer won't be able to do anything since you are just initializing an ordinary System.DateTimeOffset. Also, in this case I guess there must be a canonical representation of the date time to pass through the ABI layer (an int64 of ticks since January 1, 1601, I assume). This is mostly explained in docs, although in a slightly confusing way. So in this case it seems that there is a canonical default. In addition to this, I have come across situations where Windows APIs will return this default value for a date in the case where the date is not actually set. (For example, the System.Photo.DateTaken metadata property). Therefore I need to check against this value in some situations. If I was working in C#, then to represent an unset date value I'd use a nullable, but nullables are much less convenient in C++, so it's tempting to use the default value. For these reasons I think it would be nice to expose the default value for DateTime somehow. Although I can see the argument that the default value isn't really designed to represent an 'unset' value.

For the more general case, perhaps you are right and we don't need to do anything. Almost always structs will be zero-initialized and agree on the default. However, I do agree with @AdamBraden  that in the Windows SDK documentation,
`Each projection (C#/C++) will need to call out differences in WinRT types defaults.` I'm not 100% sure how a source analyzer would work...

By the way, here are some other minor problems that I can see that might arise when using DateTime:
-  Round-tripping DateTimeOffset through a C++/WinRT component will presumably not preserve the offset.
-  If I wrote a component in C# and used it from C++/WinRT, then I could pass the component dates in the BC era but the component wouldn't be able to handle them.

**Comment by Scottj1s** [comment]
@benstevens48 - the source analyzer would require more context than just seeing a default-initialized DateTimeOffset (e.g.).  It would have to observe it being passed to a projected interface, and then possibly alert to the risk of using language-specific default values.  Or see it returned from a projection and compared with a default-initialized value.  

Yes, roundtripping is certainly a concern - again, it all goes back to not being able to distinguish between "unset" and a value that equals a language-specific default.

**Comment by angelazhangmsft** [comment]
I've done an analysis on the projected default value of Windows.Foundation.DateTime and System.DateTimeOffset. It looks like the previous behavior raises an exception for the round-tripping scenario, and the different initialized values are consistent in .NETCore3.1/NetNative. 

Scenario 1 - what does C++ zero-initialized value look like in C#
Scenario 2 - what does C# zero-initialized value look like in C++
Scenario 3 - roundtrip from C++ back to C#

**.NET Core 3.1**
Scenario 1: UtcDateTime = {1/1/1601 12:00:00 AM}
Scenario 2: UtcDateTime = {1/1/0001 12:00:00 AM}
Scenario 3:
System.ArgumentException
  HResult=0x80070057
  Message=Specified argument was out of the range of valid values.
  Source=System.Private.CoreLib
  StackTrace:
   at System.DateTime.ToLocalTime(Boolean throwOnOverflow)
   at System.DateTimeOffset.ToLocalTime(Boolean throwOnOverflow)
   at System.StubHelpers.DateTimeOffsetMarshaler.ConvertToManaged(DateTimeOffset& managedLocalDTO, DateTimeNative& nativeTicks)
   at DefaultValues.Date.get_value()
   at UWPCSApp.MainPage..ctor() in C:\Users\angzhang\source\repos\DefaultValues\UWPCSApp\MainPage.xaml.cs:line 35

  This exception was originally thrown at this call stack:
    [External Code]
    UWPCSApp.MainPage.MainPage() in MainPage.xaml.cs

**NetNative**
Scenario 1: Ticks = 504910944000000000
Scenario 2: Ticks = 0
Scenario 3: Ticks = 0 

**.NET5**
Scenario 1: UtcDateTime = {1/1/1601 12:00:00 AM}
Scenario 2: UtcDateTime = {1/1/0001 12:00:00 AM}
Scenario 3:
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Not a valid Win32 FileTime.
  Source=System.Private.CoreLib
  StackTrace:
   at System.DateTime.ToFileTimeLeapSecondsAware(Int64 ticks)
   at System.DateTime.ToFileTimeUtc()
   at System.DateTimeOffset.ToFileTime()
   at ABI.System.DateTimeOffset.CreateMarshaler(DateTimeOffset value)
   at ABI.SimpleMathComponent.ISimpleMathStatics.global::SimpleMathComponent.ISimpleMathStatics.set_value(DateTimeOffset value) in C:\Users\angzhang\source\repos\SimpleMathDemo\_build\x64\Debug\SimpleMathProjection\bin\SimpleMathComponent.cs:line 370
   at SimpleMathComponent.SimpleMath.set_value(DateTimeOffset value) in C:\Users\angzhang\source\repos\SimpleMathDemo\_build\x64\Debug\SimpleMathProjection\bin\SimpleMathComponent.cs:line 87
   at ConsoleAppSample.Program.Main(String[] args) in C:\Users\angzhang\source\repos\SimpleMathDemo\ConsoleAppSample\Program.cs:line 13
