### ISSUE TITLE
Question: ObservableCollection for WinUI Win32

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#286]
@hshristov commented on [Wed May 20 2020](https://github.com/microsoft/microsoft-ui-xaml/issues/2490)

**Microsoft.UI.Xaml.Interop.INotifyCollectionChanged** is missing from **WinUI Win32** namespaces. Using the default **ObservableCollection** doesn't work with **ItemsControls** and implementing **Windows.UI.Xaml.Interop.INotifyCollectionChanged** throws _The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))_

So what is the correct to notify **ItemsControl** for a **CollectionChanged** and also which **INotifyPropertyChanged** works with **Binding**?

---

@robloo commented on [Wed May 20 2020](https://github.com/microsoft/microsoft-ui-xaml/issues/2490#issuecomment-631559493)

This is a duplicate of #1557 and originally #1981

This really should have been fixed before the preview though. ObservableCollection is fundamental to ALL user interfaces.

---

@StephenLPeters commented on [Wed May 20 2020](https://github.com/microsoft/microsoft-ui-xaml/issues/2490#issuecomment-631763100)

This is slightly different than the issues linked here.  This is for a Win32 app which is going through CSWinrt which should have a solution for this issue. Looks like a CSWinrt bug. @stevenbrix for FYI

---

@stevenbrix commented on [Wed May 20 2020](https://github.com/microsoft/microsoft-ui-xaml/issues/2490#issuecomment-631790215)

Can you share a repro app?

I'm not seeing a crash, but it doesn't seem to be working. I have a repro here that is using markup like this:

```xml
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
     <Button Click="myButton_Click" x:Name="myButton">Click me</Button>
    <ItemsControl ItemsSource="{x:Bind MyItems}"/>
    <ItemsControl ItemsSource="{Binding MyItems}"/>
</StackPanel>
```

```cs
public MainWindow()
{
    MyItems.Add("hi");
    MyItems.Add("goodbye");

    this.InitializeComponent();
}

private void myButton_Click(object sender, RoutedEventArgs e)
{
    MyItems.Add("clicked");
}

ObservableCollection<string> MyItems { get; } = new ObservableCollection<string>();
```

[WinUIDesktopCS0515-3.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4659714/WinUIDesktopCS0515-3.zip)

Not sure if this is related to https://github.com/microsoft/CsWinRT/issues/272

**Comment by stevenbrix** [comment]
This link is interesting: https://github.com/microsoft/microsoft-ui-xaml/issues/2490#issuecomment-645115057

**Comment by Scottj1s** [comment]
fixed
