### ISSUE TITLE
Guidance to consume UI API's on Non UWP apps

### ISSUE THREAD

**Issue by AngelMunoz** [microsoft/CsWinRT#287]
Hello there, Lovely project I'm diving in already to get my feet wet

I've previously used the WinRT API inside the UWP apps they work nicely and without issues, since they were designed for UWP in mind, that being said I want to share my exploration so far

I'm testing all of these inside an Avalonia app but I can also work them the same way in console apps, granted this might not be most of the use cases but I feel like the console and alike could have users wondering the same things now that the Win32/WinRT line blurs a little more in the sense that we're not constrained to use WinRT just in UWP anymore

So far I've toyed with a few Windows.Media/Windows.Storage APIs
- AppCaptureManager
- MediaCapture
- CameraCaptureUI
- FilePicker
- FolderPicker
- GeoLocation

my experience so far is that anything that relies on UI either crashes or fails silently (as I'd expect since the transition to WinUI is in progress)
and there are also threading issues with some of those API as well
for example 
trying to use `CameraCaptureUI` throws STA/MTA errors
FilePicker/FolderPicker doesn't seem to crash but they don't show anything either
StorageFolders work great, GeoLocation 
MediaCapture seems to work for the most part just great I was able to take pictures/video with my webcam. 
here's a small snippet
```fsharp
async {
    let capture = new MediaCapture()
    do! capture.InitializeAsync().AsTask()
        |> Async.AwaitTask

    let format =
        MediaEncodingProfile.CreateMp4(VideoEncodingQuality.Auto)

    let! tmp =
        StorageFolder.GetFolderFromPathAsync(Path.GetTempPath()).AsTask()
        |> Async.AwaitTask
    let! file =
        tmp.CreateFileAsync("TestVideo.mp4", CreationCollisionOption.GenerateUniqueName).AsTask()
        |> Async.AwaitTask

    do! capture.StartRecordToStorageFileAsync(format, file).AsTask()
        |> Async.AwaitTask

    do! Task.Delay(5000) |> Async.AwaitTask
    do! capture.StopRecordAsync().AsTask()
        |> Async.AwaitTask
    printfn "%s" file.Path
}
```

It'd be nice to know a few things either by warnings in code or documentation somewhere besides the current UWP docs (that already assume you are using UWP)

- How should I integrate WinUI (in case is possible) to let the UI dependent APIs work as they work in UWP
- Warnings about: Can I use this API without worrying about UI things?

I still have some API's to try that are not tied to UI like networking/power/bluetooth but so far so good I really love this project (I can finally write WinRT with F# 😁) and I'll try to share my experience once I play more with those (if you don't mind)

I know this might not be the ideal place to put this feedback but it would be nice if you could direct me to the correct place

Cheers on this amazing piece of work!

**Comment by Scottj1s** [comment]
@AngelMunoz - thanks for your positive feedback at this early stage.  

Most of your issues are related to requirements of the APIs you're calling:

- [CameraCaptureUI](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.cameracaptureui?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Windows.Media.Capture.CameraCaptureUI)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=winrt-18362#examples) requires an STA thread.  Add [STAThread] to your Main.
- The pickers require a hosting window, which is normally supplied by CoreWindow, but for a desktop app requires IInitializeWithWindow and IWindowNative implementations.  See the WinUI [DemoBuildCs](https://github.com/microsoft/WinUI-3-Demos/tree/master/DemoBuildCs/DemoBuildCs/DemoBuildCs) sample and Raymond Chen's article on the [IInitializeWithWindow pattern](https://devblogs.microsoft.com/oldnewthing/20190412-00/?p=102413).
- Similarly, a WinUI 3 desktop app currently requires an explicit synchronization context to be set for executing continuations back on the UI thread.  The WinUI 3 Nuget has an implementation of this, Microsoft.UI.Threading.DispatcherQueueSyncContext.  And the WinUI 3 preview VSIX project templates all call DispatcherQueueSyncContext.SetForCurrentThread() in OnLaunched.

Most of the above pain we hope to relieve with better diagnostics.

**Comment by AngelMunoz** [comment]
I imagined that would be the case, but I can't complain actually today I gave another try to other "UI-less" APIs 

specifically:
- Windows.Networking
- Windows.System.Power

and they just work, and I feel so great about that be sure I'll be promoting this anywhere I can :)

https://github.com/AngelMunoz/WinRTFs
I put my samples there and I'll see if I can get the first two bullets to work

Keep up the good work!
