### ISSUE TITLE
Proposal: Remove compat between .NET Standard 2.0 and .NET 5 output to enable scalability and versionability

### ISSUE THREAD

**Issue by jkoritzinsky** [microsoft/CsWinRT#306]
Currently, the output for C#/WinRT is the same for .NET Standard 2.0 and .NET 5. With the completion of #90 and #292, the output of the projection will differ between .NET Standard 2.0 and .NET 5. Since the original scenario for .NET Standard 2.0 (Mixed Reality APIs in Unity) exists very separately from the mainline scenario and would not utilize binary compat between .NET Standard 2.0 and .NET 5, I propose that we don't support roll forward from a .NET Standard 2.0 projection to a .NET 5 projection.

**PROS:**
If we break compatibility, we can get the following gains:

By not needing to keep compatibility, we can remove the concrete ABI types of the interfaces, significantly reducing code bloat from adding the `IDynamicInterfaceCastable` work.

The ABI namespace of the projection can become completely internal. Today, if you have an interface `IBar` that requires `IFoo`, the ABI type of `IBar` uses the ABI type of `IFoo` in its implementation. With the `IDynamicInterfaceCastable` interface, we can successfully avoid this situation by implementing the methods of `IFoo` on `IBar`s implementation interface by casting `this` to `IFoo` via `(IFoo)(object)this` to get the implementation through `IFoo`'s implementation interface.

If we also abstract marshalling a runtimeclass through a type like `MarshalGeneric<T>`, we should be able to make the entire ABI namespace internal and move the marshalers out of WinRT.Runtime and back to being internal and emitted by C#/WinRT. This will enable the C#/WinRT team to be able to evolve the marshalers more freely since each projection will have its types' marshalers embedded and they won't be a public API surface.

Also, we will be able to simplify the RCW activation scenario. If we discover an interface, we can just return an instance of `WinRT.IInspectable` since that will have an `IDynamicInterfaceCastable` implementation that will allow casting to any compatible interface. For classes and delegates we would still have to instantiate the real type.

Additionally, moving to using `IDynamicInterfaceCastable` for interface support will fix issues with versioning type mappings. Since the cast will go through `IDynamicInterfaceCastable` and look up the IID of the interface, both the pre-type mapping and post-type mapping types should work since both types will resolve to the same IID. Without `IDynamicInterfaceCastable` support, adding a new interface type mapping is a breaking change for all projections that used the old projection.

**CONS:**
If we break compatibility, we have the following losses:

We fully split the WinRT ecosystem in managed between the old WinMD-based way and the new C#/WinRT based way. There would be no way to use C#/WinRT pre-.NET 5 and you can't use WinMDs on .NET 5.

**Comment by clairernovotny** [comment]
> We fully split the WinRT ecosystem in managed between the old WinMD-based way and the new C#/WinRT based way. There would be no way to use C#/WinRT pre-.NET 5 and you can't use WinMDs on .NET 5.

A mitigation here is support for multi-targeting. A library can target both the old way and the new way with the same source. The toolchain could take care of the rest.

**Comment by hansmbakker** [comment]
How does this relate to https://github.com/microsoft/CsWinRT/issues/290?

**Comment by richlander** [comment]
I want to add on to what @clairernovotny says, but said a different way.

I think we should build the best system we can for .NET 5.0. If we have other scenarios, like the ones you've mentioned, I'd suggest that we can rely on a prescriptive pattern of multi-targeting. This means that `netstandard2.0` projections are a second-class citizen and need to be accompanied by a `net5.0-windows` asset to remain whole. Certainly, people could publish a `netstandard2.0` asset only, and either document that it is intended for narrow scenarios (not .NET 5.0) or don't document it and confuse their users.

These decisions, as I read them, are forever-style decisions. We should choose the best version of those that we won't regret later.

**Comment by MuleaneEve** [comment]
I don't fully understand the implications of this decision, but I can see how there are two sides: One that has investment in the "old" implementation, and the other side that wants the best long term solution.

Is it possible to have it kind-of both ways: Support both .NET Standard 2.0 with .NET 5.0. Then, drop it for .NET 6.0?

**Comment by StephenHodgson** [comment]
.NET Standard 2.0 support will be very import for projects using Unity. Not sure how important that is on a whole, but the Pros seem very favorable.

> Is it possible to have it kind-of both ways: Support both .NET Standard 2.0 with .NET 5.0. Then, drop it for .NET 6.0?

What's the future here? I have not been keeping up, but is .NET 6 supposed to encompass .NET Standard 2.0 and .NET 5.0?

I'm also for this as well since if that's the case, then there's plenty of time to plan for it. But then again, this is in preview, so why not just do it now? Personally, I wanna use this asap, so Standard support is something I'm very interested in, but I understand the desire to look ahead.

**Comment by AdamBraden** [comment]
@jkoritzinsky - does this go beyond the "-target" switch?

**Comment by jkoritzinsky** [comment]
Yes, this does. Part of this is not shipping the `WinRT.Runtime` netstandard2.0 assembly in the same package as the .NET 5.0 assembly since there will be a different public surface area between the two and someone targetting the netstandard2.0 assembly could use public surface area that doesn't exist in the .NET 5.0 projection (such as ABI types for interfaces).

**Comment by jkoritzinsky** [comment]
The .NET Standard 2.0 projection would ship separately for specific compat usage or for usage in a Unity scenario.
