### ISSUE TITLE
Confused strategy over time degrades adoption prospects and trust.

### ISSUE THREAD

**Issue by Noemata** [microsoft/CsWinRT#308]
The original selling point of the .Net Native compiler was performance, security, and protection of IP since reverse engineering of byte code was a non-issue for .Net Native binaries.

Lots of folks were onboard with the .Net Native compiler "promise" because of the prospect of ever better perf as the .Net Native compiler became more refined.  Having to go back to obfuscated, less stable byte code will literally force some folks to pull away from .Net and go back to C++.

It's a tragic move.  We understand that the .Net Native effort proved challenging.  It was a moon shot sort of effort that was well worth the risk given its promise.  A lot was achieved.  Now it looks like we are sliding backwards again.

It hasn't gone unnoticed that Microsoft develops all its products with C++, including the entire UI layer of WinUI.  Whatever happened to doing this work in C#?  Clearly, Microsoft is itself concerned about performance considerations in addition to compiler stability problems.

.Net Native was the right way forward.  The constant reboots and shifting initiatives from Microsoft are eroding trust and adoption.  Silverlight was a huge fiasco.  UWP is turning into another Silverlight.

If you are abandoning .Net Native, open source it so we can help ourselves.

**Comment by Scottj1s** [comment]
Thanks @noemata, I understand your frustration.  As you know, .Net has moved to an open, cross-platform strategy, which necessitated the decoupling of WinRT support in the compiler and runtime - the primary reason for the C#/WinRT initiative.  That has consequences down the line for UWP/NetNative support.  We're still working out that strategy, and will keep your concerns in mind.

**Comment by Noemata** [comment]
@Scottj1s, the trouble with a shift in strategy is that it breaks previous promises.  Much hoopla was made about the advantages of a .Net Native compiler initiative and its benefits long term.  Frustration is not the only result when one has to be witness to this sort of change in strategy, it's also a betrayal.  The whole WinUI, let's forget about our UWP promises and start promoting WPF and Winforms again ... is a startling reversal.  Many developers were forced to leave WPF because it had no access to the WinRT API or any of the "coolness" associated with the .Net Native compiler toolchain besides the fact that Microsoft stopped investing in WPF.

Please open source the WPF DirectX layer, and the .Net Native compiler toolchain as well as everything critical to building up UWP so we as a community of developers are no longer left holding the bag when Microsoft decides to change course.  These changes leave much destruction in their wake because Microsoft literally dumps the tech it was promoting as the path forward.

Your previous promises wind up looking very shallow indeed because you give us no way out of the box you placed us in.  The CoreRT native compiler story via "Microsoft.DotNet.ILCompiler" has no future.  Without the ability to generate a native binary, you will see many developers permanently depart from C# land as it offers no protection for ones intellectual property.  It is absolutely trivial to reverse engineer C# derived IL byte code.  No serious developer is going to go back to obfuscation these days.

Unity's shift to IL2CPP is now quite clear.  They knew well in advance that Microsoft was abandoning the .Net Native compiler.  Such inside knowledge is also extremely unfair.  I've said it elsewhere, this excruciating slide backwards is shameful.  I sometimes wonder what reality Microsoft occupies when decisions like this are made.  Microsoft's mobile initiatives died because Microsoft pushed it into oblivion.  You folks have run out of second chances.  I for one will not trust anything Microsoft has to say about any tech initiative.  And I'm a longtime Microsoft loyalist.

**Comment by StephenHodgson** [comment]
>  It is absolutely trivial to reverse engineer C# derived IL byte code. No serious developer is going to go back to obfuscation these days.

> Unity's shift to IL2CPP is now quite clear.

- If it ends back up in a native binary at the end of the build process, doesn't that offer some protection from reverse engineering?
- Does AOT offer any protection to the reverse engineering vulnerabilities of CIL if bypassing the JIT?
- Are there options to build native libraries using CIL based languages outside of products like Unity's IL2CPP generator?

While I agree, sympathize, and have been on the receiving end of broken promises with Microsoft, I think it's important to keep in mind that we're all trying to do our best here to figure it out, and why I've been such an advocate of Open Source. Bringing up issues like this is important for starting a serious conversation about them.

But I have to say that the power of languages that support CIL is the fact that they can be interoperable with many different libraries (many of which are open source, so reverse engineering isn't quite a big of an issue).

**Comment by Noemata** [comment]
CIL based languages do confer many benefits during the development cycle.  Being able to reflect on everything accelerates the dev cycle as does the near instantaneous compile cycle when JIT is used for a debug build.  Those benefits are not required for a release build, hence the many additional benefits of a .Net Native toolchain.

The .Net Native compiler effort was a huge step forward given how well it did handle the many issues associated with reflection.  It's tragic all this work is about to be jettisoned because the engineering effort to support a true .Net Native compiler is hard.  I suspect that is the real reason this is being abandoned, the challenges have proved to be difficult to overcome.

The Unity folks are about to introduce a simplified version of C# so they can easily produce valid, efficient CIL translations to C++ via IL2CPP, which will needlessly fragment C#.  Microsoft has the compiler chops to do this right, yet we are about to throw all of that away.  Microsoft, please open source the UWP Native compiler toolchain effort so it doesn't get lost like the wonderful WPF Surface SDK (another fantastic piece of tech trapped in Microsoft's closed source silo).

**Comment by Noemata** [comment]
Perhaps it is time governments introduce legislation that compels companies to open source technologies they've decided to walk away from when those technologies have extensive adoption in the market place.

**Comment by jkotas** [comment]
> please open source the UWP Native compiler toolchain

The core of the toolchain was open sourced as https://github.com/dotnet/corert project.

**Comment by raffaeler** [comment]
Just a few notes:
- As far as I can remember from discussions in 2014, the package created by .NET Native didn't get rid of IL, just produced AOT compilation for perf reasons, but metadata was still needed.
- AOT compilation is back with .NET Core and the level of optimizations are great. 
- Mixing the new AOT compilation with Tiered compilation is the best thing .NET ever had in the performance bootstrap space
- IL Trimming (in .NET Core) drastically reduce the amount of code needed to be deployed

Frankly .NET native was a great technology but it was "in the corner". The new innovations are moving further and better.

my 2 cents

**Comment by jkotas** [comment]
>  the package created by .NET Native didn't get rid of IL

That is not correct statement.

**Comment by raffaeler** [comment]
Thanks @jkotas, wrong memories, my fault.

**Comment by AaronRobinsonMSFT** [comment]
@Noemata Appreciate your feedback here. The frustration expressed above is fair and has been conveyed through multiple channels and we are listening - even if it seems like we aren't. That doesn't help the perception though since the assets/resources for companies to be successful seems locked away and developers are left hanging onto software stacks that were meant to be the future. We are slowing offering some of these software stacks via our [Open source](https://opensource.microsoft.com/) initiative (e.g. [WPF](https://github.com/dotnet/wpf)).

I want to offer some insight into the .NET direction. Please take a look at https://github.com/dotnet/designs/blob/master/accepted/2020/form-factors.md. This document discusses the various ways .NET can be consumed and how we think it fits into various scenarios. It specifically calls out .NET Native, what we learned, and how we are folding those learnings into .NET going forward. As @jkotas mentioned much of the .NET Native technology was exposed in the [CoreRT](https://github.com/dotnet/corert) project.

We absolutely hear your frustration with these shifts. They are not always easy to adapt to and can severely erode confidence when they contradict previous promises. None of these shifts have been made without considering impact and all have been with the desire to ensure we can offer solutions that developers can be confident building upon into the future. The current volatility reflects more our desire to allow future development in an open source world and in order to get there it is requiring us to make some of these painful breaks.

**Comment by Scottj1s** [comment]
@Noemata, I second everything Aaron said.  As most of your concerns are specific to the .NET toolchain, I encourage you to post these concerns to https://github.com/dotnet/sdk/issues/.  If there's anything specific to the C#/WinRT projection, please let me know.

**Comment by charlesroddie** [comment]
I'm interpreting this issue as AOT-related. Should we change the title to indicate that or create a new issue? It's important to track AOT support for WinRT somewhere and it would make some sense to do it in this repo. I'd like to track this because there is a danger that we will be stuck on netnative for UWP support for a long time to get AOT compilation, and if libraries start to take netstandard2.1 dependencies then we'll be in a difficult position.

Will CsWinRT help to allow UWP to be compiled with CoreRT? There is some work being done there on COM support.

**Comment by AaronRobinsonMSFT** [comment]
>Will CsWinRT help to allow UWP to be compiled with CoreRT? There is some work being done there on COM support.

@charlesroddie This is somewhat misleading if this is referring to the `ComWrappers` API - [here](https://github.com/dotnet/corert/issues/8248) and [here](https://github.com/dotnet/corert/issues/4219#issuecomment-623159691). The `ComWrappers` API is a low level building block and technically not needed to support COM. It is used to provide efficient `IUnknown` to managed object identity and help enable the [Reference Tracker API](https://docs.microsoft.com/windows/win32/api/windows.ui.xaml.hosting.referencetracker) that is used by the WinUI library (WinRT UI). C#/WinRT relies on the `ComWrappers` API for optimal efficiency in their scenarios. If the API existed in CoreRT this would mean that source generated by CsWinRT would have one less issue running on CoreRT - I don't know of all the other possible issues though.

I just want to make sure that the community doesn't assume `ComWrappers` means immediate COM support. The API is merely an efficient building block for source generated tooling like CsWinRT or [SharpGenTools](https://github.com/SharpGenTools/SharpGenTools) and doesn't technically need to be used.
