### ISSUE TITLE
Enable production (authoring) support of WinRT types

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#309]
This would replace the existing winmdexp tooling experience, to enable C# developers to define WinRT types (all kinds).  These types could be used internally by the app generating them, or externally from a packaged runtime component.  A source generator might be useful for reflecting on WinRT types as they're defined, and creating backing metadata and implementation.

**Comment by BenJKuhn** [comment]
Tagging for RC1, but work will start sooner, some pieces may deliver earlier.

**Comment by stevenbrix** [comment]
@AdamBraden, what is the MSBuild property that you need to set in the project for this?

**Comment by angelazhangmsft** [comment]
Authoring support is enabled in preview currently
