### ISSUE TITLE
[Discussion] Is it possible to make C#/WinRT projection generation semantics identical to Cpp/WinRT?

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#314]
I know we've generally settled on the fact that the C#/WinRT projection has to be generated by the provider of the component to solve the ~PIA~ identity problem. This is in contrast to how Cpp/WinRT does it, where the projection is generated on the client. **I'm wondering if it's possible to generate the projection assembly during app compilation and add it as a reference to the project.** The key difference here is that any C# project that references a WinRT component, would still reference the assembly by name, and not compile the interop code into their assembly. For libraries that ship on Nuget, the assembly is discarded and not bundled with their nuget, then when their Nuget is referenced by an app, the same WinRT interop assembly is generated at app compilation time and we don't have an ~PIA~ identity problem.

## Pros of this approach
- There is a single model for distributing WinRT components. They ship the winmd in the nuget, and the consumer adds a nuget reference to the projection generation technology of their choice:
   - `Microsoft.Windows.CppWinRT`
   - `Microsoft.Windows.AbiWinRT`
   - `Microsoft.Windows.CsWinRT`
   - `Microsoft.Windows.RustWinRT`
- Nugets are smaller because they don't have large interop assemblies embedded in them.
- We don't have to worry about the projection generation technology and the projection itself being out of sync. C#/WinRT can make breaking changes to the internal implementation of the generated projection and not worry about versioning issues.
- If Component A doesn't have an interop assembly, there's no worry about incompatibility between Library A and the App that both want to use Component A.

## Cons of this approach
- Assemblies can't be [strong name signed](https://github.com/dotnet/runtime/blob/master/docs/project/strong-name-signing.md) since this affects the assembly identity. However, it's unclear from the link if we really need or want them to be.
- It adds complexity to the build
- Potential dragons that I'm unaware of

## How it would work?
I'm thinking we'd run a target after `Restore` (or before/after `ResolveReferences`) that does something similar to what we do for generating the WinUI interop assembly: https://dev.azure.com/microsoft/winui/_git/microsoft-ui-xaml-lift?path=%2Feng%2Fcswinrt.targets

/cc @AaronRobinsonMSFT @jkoritzinsky

**Comment by Scottj1s** [comment]
So to summarize: at app build time, cswinrt msbuild support would collect the transitive closure of all referenced winmd files and generate a single set of projection sources?  A projection assembly would no longer be neede dthen - source could be compiled directly into the app.  

Nugets are smaller, but to be fair, these were shared to begin with (global nuget package cache) and would just be replaced by generated code.  And I assume this would override/obsolete any framework package distributions of interops?  So the build footprint and the app install footprint would both grow quite a bit.  

This is reminiscent of LTCG, and by deferring code gen until app build time, we do gain certain advantages.  With the closure, lots of reflection code could be omitted (as Jan Kotas suggested).  I think it would also enable culling unreferenced types (IL linking).  Cons would include increased build times, larger install images, more challenge with interop customizations (like DispatcherQueueSyncContext), but these are all solveable.

**Comment by Scottj1s** [comment]
This would also simplify cswinrt command line params.  It wouldn't be as necessary to carefully isolate type collections to ensure they don't overlap (Windows & WinUI).  It may still be necessary to filter a bit, and a winrt component nuget could provide custom targets to collect that data.  But in general, just gathering all referenced winmds and projecting everything should just work.

**Comment by AaronRobinsonMSFT** [comment]
> the same WinRT interop assembly is generated at app compilation time and we don't have a PIA problem.

I don't see how this solves the PIA problem. There is no guarantee that the assembly is the same. Flags that are passed to CsWinRT would need to be described because the local run would need to be identical. It would also need to ensure no custom modifications were performed during the official run. This approach is actually why PIAs were invented - they are singular and the source of truth. The `TlbImp` tool had a flag, [`/primary`](https://docs.microsoft.com/dotnet/framework/tools/tlbimp-exe-type-library-importer), that made an interop assembly a PIA. We need to make sure we don't confuse those two topics a PIA is the "Primary"/Official truth. If that isn't the case then we aren't dealing with PIAs we are working with interop assemblies.

I admit this is a complex scenario so I could be missing something, but I don't see how anyone can say for certain a local generation and the official generation will be the same. This is the C/C++ problem with consuming libs from an unknown compiler.

**Comment by stevenbrix** [comment]
> A projection assembly would no longer be neede dthen - source could be compiled directly into the app.

I think an assembly still has to be generated because if I'm Telerik and building a .NET library on top of WinUI, I would reference the `Microsoft.WinUI` assembly.

> And I assume this would override/obsolete any framework package distributions of interops? So the build footprint and the app install footprint would both grow quite a bit.

I'm not sure, I had thought about that. I don't see a reason why we couldn't keep the interop assemblies in the framework packages around to prevent the extra app size. This is an important consideration, we do have people complaining about the install size of their app. If we don't, I was thinking IL Linking could help only include what's actually used.

**Comment by AaronRobinsonMSFT** [comment]
>I was thinking IL Linking could help only include what's actually used.

IL Linking is very sensitive to reflection. Once reflection is detected what it is capable of is limited unless a good/bad list is provided. That could be generated by CsWinRT via some analysis but IL Linker would need a fair amount of hints given the use of reflection.

**Comment by stevenbrix** [comment]
> I don't see how this solves the PIA problem. There is no guarantee that the assembly is the same. Flags that are passed to CsWinRT would need to be described because the local run would need to be identical.

I may be overloading the term PIA here (so please correct me if I am), but I just meant that there will only ever be one assembly and it has the same assembly name and types. I agree there could be issues if someone changes the parameters to cswinrt and removes a type, so maybe we modify the tool to prevent improper usage?

>>I was thinking IL Linking could help only include what's actually used.

> IL Linking is very sensitive to reflection. Once reflection is detected what it is capable of is limited unless a good/bad list is provided. That could be generated by CsWinRT via some analysis but IL Linker would need a fair amount of hints given the use of reflection.

> Nugets are smaller, but to be fair, these were shared to begin with (global nuget package cache) and

Regarding both of these, we have this issue for implementing custom COM Wrappers for WinUI to remove the use of reflection and enable IL Linking scenarios: https://github.com/microsoft/CsWinRT/issues/136. Scott, are you suggesting that we could update cswinrt.exe to produce these more generically, and thus remove the need for WinRT component authors to generate these themselves? When we talked about WinUI including our own custom COM Wrappers, one issue that cropped up was the bloat this would add to our Nuget. If we could generate these on the client side that would be ideal. I don't know if that's possible though.

**Comment by AaronRobinsonMSFT** [comment]
>I may be overloading the term PIA here (so please correct me if I am), but I just meant that there will only ever be one assembly and it has the same identity because it's generated on the client and not strong name signed.

It isn't really much of an issue other than the fact that a PIA specifically implies there is only one. This means that if the owner and client are both generating definitions the concept of a PIA is no longer valid.

>I agree there could be issues if someone changes the parameters to cswinrt and removes a type, so maybe we modify the tool to prevent improper usage?

Perhaps, but I think we would entering a place where owner may need to customize something for a bug in CsWinRT or perhaps handle a special case. If this occurred then the client would also need to know use version X.Y.Z of CsWinRT for your scenario so it works. Whereas the owner should really be the owner of that issue.

**Comment by stevenbrix** [comment]
> This means that if the owner and client are both generating definitions the concept of a PIA is no longer valid.

The key thing with this proposal is that the owner **is not** generating a definition. The client is always generating the definition. The only definition the owner is responsible for is the .winmd(s).

**Comment by AaronRobinsonMSFT** [comment]
>The client is always generating the definition. The only definition the owner is responsible for is the .winmd(s).

Ah. I think I missed that - thanks for the clarification.

Then the next question would be consumption of WinRT types defined in .NET?

I would still be a bit concerned about modification of the generated code, but if consumers are the owners of that I am bit less since that is considered a no-no in general.

**Comment by weltkante** [comment]
You don't have full information at build time. You must be able to interop with runtime-loaded assemblies (aka plugins).

**Comment by AaronRobinsonMSFT** [comment]
>You don't have full information at build time. 

Yep. That is the reflection piece of this. The plugin model is the practical example.

>Extensibility is a key concept for a lot of our applications and I'd expect WinUI as a UI framework to support extensible application models.

Agreed.

**Comment by stevenbrix** [comment]
> Then the next question would be consumption of WinRT types defined in .NET?

Is this the scenario where I'm a .NET app with a reference to a .NET WinRT Component? I'm not 100% sure what the production side for .NET WinRT components looks like. I don't see a reason why this would change anything, but it's a good thing to call out and keep in mind.

**Comment by stevenbrix** [comment]
> > You don't have full information at build time.
> 
> Yep. That is the reflection piece of this. The plugin model is the practical example.
> 
> > Extensibility is a key concept for a lot of our applications and I'd expect WinUI as a UI framework to support extensible application models.
> 
> Agreed.

Unless I'm missing something, I don't think we would be preventing that scenario with this approach?

**Comment by weltkante** [comment]
Maybe I'm misunderstanding, but it sounded like libraries are not supposed to distribute the projection, the application is doing it at build time. But the application doesn't have full information over what extensions will be using, so if application extensions needed interop thats not part of the base application that would cause either missing references (when extensions are viewed as libraries and nobody distributes the interop definition) or duplicates (when extensions are viewed as clients and multiple extensions deploy the same generated interop, perhaps even using different version of tooling to generate it).

**Comment by AaronRobinsonMSFT** [comment]
>Not sure what this is referring to, couldn't find where this is discussed in this context.

Mentioned when talking about the IL Linker above for type pruning - which would cause certain types to be pruned away. Otherwise all needed types should be kept as I can't see why they would be removed by default. Perhaps your concern here was for the mentioned CsWinRT analysis engine that could prune?

**Comment by weltkante** [comment]
> Perhaps your concern here was for the mentioned CsWinRT analysis engine that could prune?

No I think I just misunderstood the discussion, sounded like you wanted to reduce footprint by having the projection only exist in transient form on library level, just built to be referenced but not included inline in the assembly or deployed with the library - only the final application build generating the closure of all required projections.

Anyways I don't want to derail the discussion, I'm fine having made my point about extensibility and will follow along and see what you'll come up with.

**Comment by AaronRobinsonMSFT** [comment]
>only the final application build generating the closure of all required projections.

I do think that was implied - at least that is how I interpret what a CsWinRT analysis engine would do. The plug-in model does then hinder both IL Linker and analysis in CsWinRT for an application.

@stevenbrix I think both @weltkante and I are concerned about the same issue just coming at it from two different angles. Are we both confused here as to what is the suggestion or does this concern make sense?

**Comment by stevenbrix** [comment]
> Are we both confused here as to what is the suggestion or does this concern make sense?

Nope! I think the concern makes total sense. It was never my intention to make IL Linking + type pruning the only way to consume WinRT components in .NET, it should always be an option.

I am far and wide not the expert on plug-in models, so I appreciate your experience @weltkante 

> But the application doesn't have full information over what extensions will be using, so if application extensions needed interop thats not part of the base application that would cause either missing references (when extensions are viewed as libraries and nobody distributes the interop definition)

I would imagine in this scenario an extension could ship the WinRT component interop then. Although that would probably lead to the next thing you described...

> or duplicates/conflicts (when extensions are viewed as clients and multiple extensions deploy the same -or overlapping- generated interop, perhaps even using different version of tooling to generate it).

Can you explain what happens when there are conflicts for existing .NET assemblies in this scenario? I don't think WinRT interop assemblies would be any different in this scenario.

**Comment by weltkante** [comment]
> Can you explain what happens when there are conflicts for existing .NET assemblies in this scenario? I don't think WinRT interop assemblies would be any different here.

As far as we are concerned, so far we only have experience on Desktop Framework. We have an .exe.config in place with redirections for dependencies in our base application. This mostly works out but if conflicts happen anyways the user has to go through our support and we update the .exe.config accordingly.

I think VS has a more automated model to handle and resolve conflicts in extensions? I don't know it that well though.

For .NET Core the dependency configuration file looks too complicated to adjust by hand so I'd probably attempt to put extensions in separate AssemblyLoadContext and try finding a resolution logic by trial and error as conflicts come up in practice. Maybe inventing some configuration file for extensions whether they want an isolated or shared copy of a dependency?

For interop I'd expect RCWs to be shareable between extensions, as has come up in one of the other discussions of this topic, where the response was that there should be a PIA-style resolution where the author of a COM visible definition will build and deploy the interop assembly. For the Windows interop you'd refer to the CsWinRT package.

This kinda goes counter what is proposed here so I was raising the usecase of extensions again to make sure they are not overlooked. Making interop a primary source of dependency conflicts would be a problem for us.

**Comment by BenJKuhn** [comment]
@Scottj1s & @AaronRobinsonMSFT, is this approximately the same problem as https://github.com/microsoft/CsWinRT/issues/304, related, or distinct?

**Comment by stevenbrix** [comment]
@BenJKuhn it's distinct, because this issue isn't talking about embedding the sources into the app. They are related in the sense that we'd be generating the code on the client in both cases, but that's about it.

I love that @richlander opened #310, perhaps we need to wait for that to fully understand what the right thing to do here is. I feel like we're all hovering in the same ballpark, and a scenario driven spec will really help us understand where to go.

**Comment by stevenbrix** [comment]
BTW, I *wouldn't* advocate for the projection assemblies for any interop assembly that ships with .NET to be generated by the client. Those can all be generated ahead of time and cross-gen'd.

The point of this is so that cswinrt.exe always generates assemblies that match the winrt.runtime.dll it's paired with. As soon as people put interop assemblies in Nuget, you lose this guarantee.

**Comment by reflectronic** [comment]
I really dislike the idea of having to publish .NET versions of every Windows Runtime component. As a component author, it almost defeats the point of the Windows Runtime to have to create special cases for certain platforms. Generating and maintaining a separate interop assembly to use components from .NET is a pain, and the "tools" for doing that (which amount to just invoking `cswinrt.exe` with command line arguments) are difficult to set up. 

For NuGet package authors, maintaining two versions of a package is annoying, and I think many will just pass the buck for generating the interop assembly onto the consumers anyway. However, I have used the Windows Runtime on a number of occasions just for standard cross-language interop. It is by far the cleanest and richest choice for communicating between components written in different languages like C++ and C#. The tools as-is are even worse for this, and you often need to spend several hours tinkering with MSBuild to get a good workflow.

Strong thumbs up for having projections being generated on the client.

**Comment by stevenbrix** [comment]
> For NuGet package authors, maintaining two versions of a package is annoying, and I think many will just pass the buck for generating the interop assembly onto the consumers anyway. 

This is great feedback, because this wouldn't be the guidance. You can ship your .winmd and interop assembly in the same package.

As for the difficulty in setting up the tools, I imagine we'll have support so that there isn't any extra setup. @scottj1s is there an issue for this?

**Comment by AdamBraden** [comment]
For 1.0, the component author must build the projection. Based on feedback we can consider future options.
