### ISSUE TITLE
Update to new ComSupport api surface

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#316]
.Net 5 SDK Preview 5 introduced a breaking change, causing C#/WinRT-based apps to fail at runtime on finding System.Runtime.InteropServices.ComWrappers.RegisterAsGlobalInstance.  Need to update the projection and add user protection from future prerelease breaking changes via msbuild assertions.

**Comment by wli3** [comment]
It is hard to work on https://github.com/dotnet/sdk/issues/11556 due to this issue. Any ETA for this? And is there a workaround?

**Comment by Scottj1s** [comment]
@wli3 - no workaround I'm aware of, other than basing your work on preview 4 if possible.  I expect this fix to be published shortly though.

**Comment by Scottj1s** [comment]
Note that publishing the next cswinrt package with this fix to nuget.org is being coordinated with WinUI 3 preview 2 release.

**Comment by wli3** [comment]
@Scottj1s publish to nuget happens? I need to finish the above task in 2 weeks to catch next preview
