### ISSUE TITLE
Investigate crossgen performance impact with CsWinRT generated SDK interop

### ISSUE THREAD

**Issue by mikebattista** [microsoft/CsWinRT#317]
As part of integrating into .NET 5 TFMs, we need to evaluate crossgen support. This would require delivering per-arch runtime targeting packs for each TFM we support (17763, 18362, and 19041).

We first should do perf analysis to understand the perf gains of doing this. If they're not significant, then we could deliver TFM integration as Any CPU instead.

**Comment by fabiant3** [comment]
@mikebattista  - thank you for opening this issue. Does this also take care of crossgen build related issue as well? My understanding is that crossgen does require some time to complete.

**Comment by mikebattista** [comment]
@manodasanW would have to comment.

The primary perf gains we have discussed so far are runtime/startup gains, not build-time gains.

**Comment by Scottj1s** [comment]
The main concern here is that crossgen would not make perf any worse, when compared to cswinrt projection without it.  That would have to be very pathological code-gen in cswinrt, so it's not expected.  If perf improves, as expected, this issue can be closed with no further action.

**Comment by ujjwalchadha** [comment]
Ready to run case sees some improvement in general but is almost never worse. Memory usage, as expected, is higher in case of ready to run. The results are here: \\nunatak\perf_analysis\experiments\r2r\visualizations
