### ISSUE TITLE
Assess compatibility of C#/WinRT netstandard2.0 support for Mixed Reality toolkit projection

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#320]
One of the motivating reasons for C#/WinRT was to support non-Windows runtimes like Mono 5.4 in Unity, for WinRT light-up features such as the Hololens Mixed Reality toolkit.  This should be evaluated to and any gaps closed to ensure that netstandard2.0 support isn't just theoretical.

**Comment by AdamBraden** [comment]
If we build a netstandard2 projection, we need to make it clear this is intended for Mono consumers. I do not want developers confused by mixing projections - a windows targeted netfx or netcore3 app should still reference winmds and let the compiler and runtime handle the projection.

For the Windows SDK, that means we continue shipping the contracts package for netfx/netcore3, and start shipping a net5 cswinrt projection. For Mono, we build a package with Unity Package Manager to ship the netstandard2 projection for use by mixed reality scenarios.

**Comment by StephenHodgson** [comment]
Who said it had to be specifically for mixed reality applications?

There's also machine learning APIs and all sorts of other useful things in the windows runtime I'd like to have access to for application development.
