### ISSUE TITLE
System.MissingMethodException for ComWrappers.RegisterForTrackerSupport on startup

### ISSUE THREAD

**Issue by llongley** [microsoft/CsWinRT#328]
I'm not sure if this is something I'm doing wrong, but after updating to the latest C#/WinRT, I'm seeing this exception thrown on startup:

**System.MissingMethodException**: 'Method not found: 'Void System.Runtime.InteropServices.ComWrappers.RegisterForTrackerSupport(System.Runtime.InteropServices.ComWrappers)'.'

It looks like a reference to that method was added in [this commit](https://github.com/microsoft/CsWinRT/commit/e6126c1c074d891d2bfd4175a6daf2e78bbd303b), but the version of System.Runtime.InteropServices.dll that's being packaged with my app does not have that method in it.  I'm using the version of the .NET SDK listed as required in [this commit](https://github.com/microsoft/CsWinRT/commit/94e6db00a37a7d162ee1973fcef97dae32afa8bb) - possibly more of the change in the previous commit needs to be backed out to accompany the version downgrade?

**Comment by jkoritzinsky** [comment]
Yes, the new versions of C#/WinRT require Preview 5. There was a breaking API change to enable fixing some C#/WinRT issues between Preview 4 and 5.

**Comment by Scottj1s** [comment]
@Llongley - have you been able to confirm that you're referenced .net sdk preview 5?

**Comment by llongley** [comment]
I *thought* I was, but it turned out that us installing it to a custom directory was causing problems where it was being picked up some times but not other times.  Moving the install to the default directory looks like it fixed things.  Sorry for the randomization!
