### ISSUE TITLE
Developers need a Package Compatible with .Net 5.0 preview 6+

### ISSUE THREAD

**Issue by jtbrower** [microsoft/CsWinRT#332]
Today I updated my 150 project .Net5.0 effort to **preview version 6**.  There is a compatibility issue that prevents me from using the following SDK because an exception is thrown due to a missing method.

```<PackageReference Include="Microsoft.Windows.SDK.NET" Version="10.0.18362.3-preview" />```

```
System.MissingMethodException: Method not found: 'Void System.Runtime.InteropServices.ComWrappers.RegisterAsGlobalInstance()'.
   at WinRT.ComWrappersSupport.get_ComWrappers()
   at WinRT.ComWrappersSupport.CreateRcwForComObject(IntPtr ptr)
   at WinRT.MarshalInspectable.FromAbi(IntPtr ptr)
   at ABI.Windows.Devices.Enumeration.DeviceWatcher.FromAbi(IntPtr thisPtr)
   at ABI.Windows.Devices.Enumeration.IDeviceInformationStatics.CreateWatcher(String aqsFilter)
   at Windows.Devices.Enumeration.DeviceInformation.CreateWatcher(String aqsFilter)
```
I initially reported this [issue ](https://github.com/dotnet/runtime/issues/35318#issuecomment-640117029)over in the runtime repository 3 weeks ago but forgot to log it over here.  It seems this could be related to this [runtime update] (https://github.com/dotnet/runtime/issues/35318).  Does your team have plans to release a compatible version soon?

**Comment by jkoritzinsky** [comment]
The Microsoft.Windows.CsWinRT package has an update with the fix. Sadly, the team didn’t have a chance to push out a new version of Microsoft.Windows.SDK.NET that points to the updated Microsoft.Windows.CsWinRT package in time for the Preview 6 release.

**Comment by jtbrower** [comment]
Hello @jkoritzinsky, that's certainly understandable, Microsoft is moving at an amazing (and fun) fast pace.  Do you have an expected timeframe for that package?  Its not blocking anything that I can't work-around for the moment but it would be great to have it in the next week.

**Comment by jkoritzinsky** [comment]
You should be able to add a `<PackageReference>` directly to the `Microsoft.Windows.CsWinRT` package to get the updated version. I don't know the ETA on the updated SDK package. My guess would be when WinUI Preview 2 comes out, but I don't know for sure.

**Comment by jtbrower** [comment]
Forgive any ignorance on my part regarding these questions as I am in control of a substantial amount of code and trying to remain an expert in all fast migrating repositories is a fun challenge to have.

Are you sure the latest Microsoft.Windows.CsWinRT preview has the updated fix?  Adding a reference to it did not stop the original exception from being thrown.  If I examine the Microsoft.Windows.SDK.NET package, it is indicating the same version of the latest Microsoft.Windows.CsWinRT package.  I assumed that there was a newer Microsoft.Windows.CsWinRT version that would be used in place of the one that Microsoft.Windows.SDK.NET lists?

Latest Previews that I am Referencing
```
    <PackageReference Include="Microsoft.Windows.SDK.NET" Version="10.0.18362.3-preview" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="0.1.0-prerelease.200512.7" />
```

Is there another package feed that I need to add?

**Comment by jkoritzinsky** [comment]
cc: @Scottj1s about pulling in the new CsWinRT NuGet package with the support for .NET 5 Preview 5+.

**Comment by jtbrower** [comment]
@jkoritzinsky  @Scottj1s that would be for .Net 5 Preview 6+.  Preview 5 works fine.

**Comment by Scottj1s** [comment]
Hi Jason, the function you mention was removed in Preview 5, and replaced with the pair of functions RegisterForTrackerSupport and RegisterForMarshalling.  There's an unlisted cswinrt prerelease nuget that resolves this issue: https://www.nuget.org/packages/Microsoft.Windows.CsWinRT/0.1.0-prerelease.200623.5

**Comment by jtbrower** [comment]
@Scottj1s sweet, thank you!  I updated the version, booted up and connected to my target magnetic swipe reader. Cheers!

**Comment by Scottj1s** [comment]
We will be publishing a listed cswinrt nuget with this fix (and a few others) in sync with the WinUI 3 Preview 2 release (soon).

**Comment by jtbrower** [comment]
@scottj1s since you brought up WinUI 3 I thought I would mention that I gave preview 1 WinUI a try over the weekend and was pleased that I could build a desktop application using it.  I applied the same fix that you shared above so that it would work with .Net5.0 preview 6.  "Dying" for a new way forward regarding UI in Desktop applications I think I am going to attempt to convert a substantial amount of WPF over.  Although I know this topic is outside the scope of the repo, thanks for your fix because it gives me the ability to use the latest .Net while continue to evaluate other packages like WinUI.

**Comment by raffaeler** [comment]
I have this same error with RC1 and didn't expect at this time in a Console App that is just consuming WinSDK:
```
<PackageReference Include="Microsoft.Windows.SDK.NET" Version="10.0.18362.3-preview" />
```
Is there a fix right now?

TIA

**Comment by raffaeler** [comment]
Forget it, I came back to the nuget package after getting an access denied, which is caused by the location privacy settings instead.
It works, sorry for the confusion
