### ISSUE TITLE
WindowsRuntimeBufferExtensions.ToArray incorrectly checks Capacity

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [microsoft/CsWinRT#334]
**Issue moved from dotnet/runtime - see https://github.com/dotnet/runtime/issues/23383**

The following code will throw an ArgumentException:

```c#
var buffer = new Windows.Storage.Streams.Buffer(0);
var array = buffer.ToArray();
```

WindowsRuntimeBufferExtensions.ToArray checks the buffer capacity as a precondition, which isn't used in the method.  Obviously the expected behavior would be to return an array of length zero.

I also can't find a unit test for this case.

**Comment by weltkante** [comment]
For what its worth this edge case is also present in other methods of `WindowsRuntimeBufferExtensions`. (Count is allowed to be zero but then the index-check against the capacity is off by one to actually let the code through. This allows a count of zero on every position except the last, which is odd.)

**Comment by j0shuams** [comment]
[This ](https://github.com/dotnet/runtime/issues/23383#issuecomment-446370673) comment suggests making the condition in ToArray a strict greater-than.

**Comment by j0shuams** [comment]
The other methods this check happens in is CopyTo. I tried the following code, with no change to the exception condition:
```
var buffer = new Windows.Storage.Streams.Buffer(0);
byte[] bytes = { };
buffer.CopyTo(bytes);
```

And there was no error, so I think changing the condition there is unnecessary.

**Comment by weltkante** [comment]
The fix was incomplete, there are various extension methods in WindowsRuntimeBufferExtensions which still throw incorrectly.

**Comment by j0shuams** [comment]
@weltkante Can you be more descriptive and/or give examples? Of the remaining public methods: AsBuffer, CopyTo and GetByte, I do not see a situation like you describe of count being zero causing an index check against capacity to incorrectly throw.

**Comment by weltkante** [comment]
The cause of the false checks are incorrect `<=` checks - in particular of the style `if (source.Length <= sourceIndex) throw new ArgumentException(...);`

Source index can be at the end of the buffer when count is zero, see my [comment above](https://github.com/microsoft/CsWinRT/issues/334#issuecomment-659266068), so many of the extension methods incorrectly throw in this case even though the do not throw if length is zero at any place except the end of buffer.

**Comment by j0shuams** [comment]
@weltkante thanks for your reply, do you think changing to `<` is enough or should the `<=` be anded (`&&`) with `count != 0` ?

**Comment by weltkante** [comment]
I think its an off-by-one error and changing into `<` _should_ be enough, but I didn't do a full review. The PR which was used to fix some of the errors might not have had to introduce new conditionals if these off-by-one were fixed, so thats also worth taking a second look.

**Comment by j0shuams** [comment]
@weltkante I've made some additional changes, review/feedback would be greatly appreciated! https://github.com/microsoft/CsWinRT/pull/504
