### ISSUE TITLE
Some async operations throwing type initialization exception on void* 

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#335]
Unhandled Exception: System.TypeInitializationException: The type initializer for 'ABI.Windows.Foundation.AsyncOperationCompletedHandler`1' threw an exception. ---> System.ArgumentException: The type 'System.Void*' may not be used as a type argument.

Repro examples:

var decoder_task = Windows.Graphics.Imaging.BitmapDecoder.CreateAsync(stream);
decoder_task.AsTask().Wait(); //HERE

var software_bitmap_task = decoder.GetSoftwareBitmapAsync();
software_bitmap_task.AsTask().Wait(); // HERE

var stream_task = image.OpenReadAsync();
stream_task.AsTask().Wait(); // HERE

**Comment by Scottj1s** [comment]
I can't repro this with:

            var file = await Windows.Storage.StorageFile.GetFileFromPathAsync("d:\\bitmap.bmp");
            var stream = await file.OpenAsync(Windows.Storage.FileAccessMode.Read);
            var decoder_async = Windows.Graphics.Imaging.BitmapDecoder.CreateAsync(stream);
            decoder_async.AsTask().Wait(); //HERE

I've tried a few other variations as well - the issue may have been fixed in the meantime, or the repro steps may be missing something.

**Comment by Scottj1s** [comment]
moving to RTM milestone, due to no repro by customer

**Comment by AdamBraden** [comment]
We cannot repo, closing
