### ISSUE TITLE
System.Type projects to Windows.UI.Xaml.Interop.TypeName with incorrect data when the represented type is also projected

### ISSUE THREAD

**Issue by RealTommyKlein** [microsoft/CsWinRT#344]
Example: the System.Type that represents its own type, "System.Type".  The System.Type is projected to Windows.UI.Xaml.Interop.TypeName with Name="System.Type" and Kind=TypeKind_Custom.  However, the data itself also needs to be projected, so Name="Windows.UI.Xaml.Interop.TypeName" and Kind=TypeKind_Metadata.

**Comment by stevenbrix** [comment]
A workaround in WinUI was added for this bug, when this is fixed that workaround needs to be removed

**Comment by ujjwalchadha** [comment]
Fixed [here](https://github.com/microsoft/CsWinRT/commit/f2bd242fd74f382a82963092fd0fcfec36f43861).
