### ISSUE TITLE
TypeName.Name doesn't return full assembly qualified type name

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#345]
When we are loading the default style for an object, we need the full assembly qualified name, so that we can form the appropriate URI to load generic.xaml from.

Repro:
1. Create a new WinUI Desktop App for C#

2. Add reference to `Microsoft.Toolkit.Uwp.UI.Controls.DataGrid` nuget package, version `8.0.0-preview1` from this feed: https://dotnet.myget.org/gallery/uwpcommunitytoolkit

3. Add the `DataGrid` control to MainWindow.xaml and F5

When we try to resolve the type name for the control so we can load the appropriate generic.xaml file, we QI the `DefaultStyleKey` property for `IReference<TypeName>`, when this QI succeeds, we get the `TypeName.Name` property and use that to find the assembly the control is located in.

**.NET Native**: Microsoft.Toolkit.Uwp.UI.Controls.DataGrid, Microsoft.Toolkit.Uwp.UI.Controls.DataGrid, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null

**.NET5**: Microsoft.Toolkit.Uwp.UI.Controls.DataGrid

**Comment by stevenbrix** [comment]
@dotMorten for FYI

**Comment by dotMorten** [comment]
@stevenbrix Thanks! This is definitely a blocker issue for us.

**Comment by stevenbrix** [comment]
@dotMorten you can workaround this by putting a line like this in your app.xaml:

```xml
<Application.Resources>
   <ResourceDictionary.MergedDictionaries>
       <ResourceDictionary Source="ms-appx://Esri.ArcGISRuntime.WinUI/Themes/Generic.xaml"/>
   </ResourceDictionary.MergedDictionaries>
</Application.Resources>
```

**Comment by ujjwalchadha** [comment]
This has been fixed by the latest dotnet. (net 5.0.100 RTM or greater).

**Comment by Scottj1s** [comment]
closed by mistake

**Comment by ujjwalchadha** [comment]
This issue should be fixed with [this commit](https://github.com/microsoft/CsWinRT/commit/f9e64eba5ae40bdf033d3c0bcef2a3878e05f015)

@stevenbrix @RealTommyKlein 
Please check if the upcoming update of CsWinRT fixes this.

**Comment by Scottj1s** [comment]
@ujjwalchadha this looks like something we can validate ourselves, right?

**Comment by dotMorten** [comment]
I'll be more than happy to validate too, once preview 3 ships, unless you want to share a preview of the preview with me again 😉

**Comment by ujjwalchadha** [comment]
@dotMorten Thanks! We’ll let you know if that’s necessary.

**Comment by ujjwalchadha** [comment]
Fixed with CsWinRT1.0.1
