### ISSUE TITLE
Objects are marshaled as IUnknown instead of IInspectable, causing crashes when using IInspectable methods

### ISSUE THREAD

**Issue by RealTommyKlein** [microsoft/CsWinRT#347]
When CSWinRT marshals objects, they appear to be marshaled as IUnknowns instead of IInspectables native code expects.  If native code attempts to use the IInspectable methods like GetRuntimeClassName without first QueryInterface'ing, it will crash.  Normally this isn't an issue for C++/WinRT code since it will QI the IInspectable before attempting to use it, but it does affect non-C++/WinRT code like WinUI 3.  Example repro by modifying the Class.ObjectProperty setter in the TestComponentCSharp test project:
```
  // Include headers to access ABI types
  #include <windows.foundation.h>
  #include <unknwn.h>
  #include "winrt/Windows.Foundation.h"

```
    void Class::ObjectProperty(IInspectable const& value)
    {
        _object = value;

        HSTRING className;
        HSTRING classNameQI;

        // Get the raw ABI IInspectable pointer out of the C++/WinRT struct we were given.
        winrt::com_ptr<::IInspectable> ptr = nullptr;
        winrt::copy_to_abi(_object, *ptr.put_void());

        if (ptr != nullptr)
        {
            // The raw pointer we were given.  While it is meant to be an IInspectable, the pointer value
            // is actually an IUnknown.
            ::IInspectable* ptrRaw = winrt::get_abi(ptr);

            // The pointer we get when QI'ing for IUnknown.  This is unexpectedly equal to the IInspectable
            // pointer we're given, when the different interfaces should point to different locations in memory.
            ::IUnknown* ptrQIUnknown;

            // The pointer value we get when QI'ing for IInspectable.
            ::IInspectable* ptrQIInspectable;
            ptrRaw->QueryInterface<::IInspectable>(&ptrQIInspectable);
            ptrRaw->QueryInterface<::IUnknown>(&ptrQIUnknown);

            // This suceeds as expected when we explicitly QI for the IInspectable interface from the IInspectable we were given.
            ptrQIInspectable->GetRuntimeClassName(&classNameQI);

            // This unexpectedly fails - the IInspectable value we were originally given is actually
            // an IUnknown, so we walk off the vtable and crash.
            ptrRaw->GetRuntimeClassName(&className);
        }

    }

Also note in the CSWinRT code for Class.ObjectProperty, `__value` is marshaled as `WinRT.ObjectReference<WinRT.Interop.IUnknownVftbl>`.

**Comment by weltkante** [comment]
> This is unexpectedly equal to the `IInspectable` pointer we're given, when the different interfaces should point to different locations in memory.

This is not unexpected, its common to share the same vtable with superclasses.

> When CSWinRT marshals objects, they appear to be marshaled as IUnknowns instead of IInspectables native code expects.

That sounds much worse actually. If the IDL signature says its typed as a particular interface the caller has to QI, C++ implementations will trust the types specified in the header are available and call vtable methods directly. Passing IUnknown or IInspectable when a concrete interface is in the signature is undefined behavior.

**Comment by Scottj1s** [comment]
@RealTommyKlein - thanks for the repro!
