### ISSUE TITLE
Cannot reference a C++ windows runtime project from a .net 5 (preview 6) C# project

### ISSUE THREAD

**Issue by lhak** [microsoft/CsWinRT#348]
After updating to .net 5 preview 6, it is no longer possible to reference a C++ windows runtime project from a C# project in Visual Studio (version 16.7.0 Preview 4.0). The build failes with this error:

error NETSDK1130: Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.

The generation of the projections should be handled automatically in this scenario.

**Comment by AdamBraden** [comment]
@lhak - the tooling to autogenerate the projection must come from CSWinRT and the component author must explicitly create a projection project.

**Comment by lhak** [comment]
Ok, so if I have a solution with one C# project (app code) and one C++ project (library code) I now need to manually create a third project containing the projection code and reference that one from the app project? This seems overly complicated and a regression compared to the previous situation. Or is this just a temporary issue and will be fixed in future cswinrt or Visual Studio updates?

**Comment by AliveDevil** [comment]
Not only that, you have to manually change the app-project to remove all winmd-references (direct and indirect through the projection library project).

**Comment by AdamBraden** [comment]
@ihak - yes, to support .NET5 applications, you as the component developer need to build the .NET5 projection assembly. Right now this is a fairly manual process, however the desired experience is:
- add a .NET5 dll project to your solution
- add package reference to cswinrt
- set a project property telling what namespaces to include in the projection
- build
- update your nuget package for .NET5 target
- from your .net5 app, update your reference to the projection project or use the updated nuget package

**Comment by AdamBraden** [comment]
@AliveDevil - yes we are working on the props/targets for cswinrt, so when its added, it helps remove all those winmd references. Additionally we are working with the .NET team to make the error more informative and less blocking - see https://github.com/dotnet/sdk/issues/13268

**Comment by lhak** [comment]
@AdamBraden Thank you for the clarification. In my case, I do not want to use or publish the C++ project as a nuget package but use it to simplify calling certain Windows APIs. I would have hoped that in this cases, the creation of a dedicated projection project could be skipped and adding a project reference from the C# to the C++ project would be enough to automatically create  the projection code. Maybe this can be considered in the future?
