### ISSUE TITLE
A better way to use IInitializeWithWindow

### ISSUE THREAD

**Issue by mveril** [microsoft/CsWinRT#355]
Using [IInitializeWithWindow](https://docs.microsoft.com/windows/win32/api/shobjidl_core/nn-shobjidl_core-iinitializewithwindow) is very complicated with CsWinRT compared to the old .NET way. You can see the implementation in the  [WinUI-3-Demos repo](https://github.com/microsoft/WinUI-3-Demos/blob/86b9520de09b764aafef44b3a9859f72146b2dc6/DemoBuildCs/DemoBuildCs/DemoBuildCs/MainWindow.xaml.cs#L57). It's possible to restore the old way or create a wrapper for that integrated in CsWinRT ?
Another isuue which talk about that #287

**Comment by Scottj1s** [comment]
CsWinRT now supports ComImport-attributed interfaces directly.  These can be defined by end developers, or included in projection assemblies, where appropriate.  See also:
https://github.com/microsoft/microsoft-ui-xaml/issues/2595
