### ISSUE TITLE
Project WinRT IXamlServiceProvider interface to System.IServiceProvider

### ISSUE THREAD

**Issue by MikeHillberg** [microsoft/CsWinRT#358]
See the following new Xaml API, which is designed to match System.IServiceProvider: https://github.com/microsoft/microsoft-ui-xaml-specs/pull/84

In a cs/winrt projection, this should show up as System.IServiceProvider, analogous to the special projection of INotifyPropertyChanged from Microsoft.UI.Xaml.Data to System.ComponentModel.

**Comment by AdamBraden** [comment]
@MikeHillberg - when is your eta for implementing - is it in an unlisted nuget we can update to, in order to complete our work?
