### ISSUE TITLE
Can't create AppService from dotnet 5 appp

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/CsWinRT#364]
I used [`Microsoft.Windows.SDK.NET`](https://www.nuget.org/packages/Microsoft.Windows.SDK.Net) nuget package instead of [`Microsoft.Windows.SDK.Contracts`](https://www.nuget.org/packages/Microsoft.Windows.SDK.Contracts) in my dotnet 5 project to create consume [App Service](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/app-services) from an uwp app. But it failed with following error:
![JKfchMvvMA (2)](https://user-images.githubusercontent.com/51203900/89654690-a32e0000-d8e6-11ea-95dd-bc7aa48eacb5.png)

**Comment by manodasanW** [comment]
@soumyamahunt which version of the Microsoft.Windows.SDK.NET package are you using?  Can you try out the the unlisted [10.0.18362.6-preview](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET/10.0.18362.6-preview) version of the package.

**Comment by soumyamahunt** [comment]
> @soumyamahunt which version of the Microsoft.Windows.SDK.NET package are you using? Can you try out the the unlisted [10.0.18362.6-preview](https://www.nuget.org/packages/Microsoft.Windows.SDK.NET/10.0.18362.6-preview) version of the package.

I was using version 10.0.18362.3-preview, and yes using 10.0.18362.6-preview version fixes this issue.
