### ISSUE TITLE
Project ValueSet as  IDictionary<String, Object>

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/CsWinRT#366]

**Comment by AdamBraden** [comment]
@Jaiganeshkumaran  - do you have a repo of the issue? ValueSet should be mapping to IDictionary.

**Comment by AdamBraden** [comment]
Confirmed. it must map to a runtime class that implements IDictionary

public sealed class ValueSet : IPropertySet, IObservableMap<string, object>, global::System.Collections.Generic.IDictionary<string, object>, global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<string, object>>, global::System.Runtime.InteropServices.ICustomQueryInterface, IEquatable<ValueSet>

**Comment by Marv51** [comment]
Is this about ValueSet implementing IDictionary<string, object>, or can the projection also improve methods accepting ValueSet objects? 
For example `Windows.System.Launcher.LaunchUriAsync(Uri uri, LauncherOptions options, ValueSet inputData);` could this change to IDictionary, or an additional overload maybe?

**Comment by Jaiganeshkumaran** [comment]
> Is this about ValueSet implementing IDictionary<string, object>, or can the projection also improve methods accepting ValueSet objects? For example `Windows.System.Launcher.LaunchUriAsync(Uri uri, LauncherOptions options, ValueSet inputData);` could this change to IDictionary, or an additional overload maybe?

I meant that you should be able to construct a ValueSet directly from an existing IDictionary<String, Object> instance.
