### ISSUE TITLE
Better error messages - CsWinRT needs to diagnose invalid metadata 

### ISSUE THREAD

**Issue by ocalvo** [microsoft/CsWinRT#367]
Repro:
1. Run CSWinRT with a large CX/C++ code base.

Actual:
CsWinRT fails to generate code with a cryptic error message:
  EXEC : error : element type not supported
Expected:
CsWinRT fails to generate code with an informative error message:
  EXEC : error : element type "Foo" referenced from type "Goo" is not supported

**Comment by Scottj1s** [comment]
Waiting for customer feedback on private build before proceeding to implement diagnostic errors
