### ISSUE TITLE
Reference dotnet standard 2.0 project with WinRT references in UWP 

### ISSUE THREAD

**Issue by Marv51** [microsoft/CsWinRT#376]
Hi not sure if this is the correct repo to report this, but here is my bug/issue I found.

In dotnet core 3.1 I had a WPF and a UWP project that shared code via a dotnet standard 2.0 library. This library contains references to the WinRT API (for example `Windows.ApplicationModel.AppService.AppServiceConnection`). Both the WPF project and the dotnet standard project referenced the Microsoft.Windows.SDK.Contracts nuget package.

After trying the .net5.0 preview 8 bits today (did not try before), this does not appear to work. When the reference between dotnet standard and UWP is in place, I am getting this error for every WinRT type I touch: 

CS0433: Type "AppServiceConnection" already exists in both "Microsoft.Windows.SDK.NET, Version=10.0.18362.3, Culture=neutral, PublicKeyToken=null" and "Windows.Foundation.UniversalApiContract, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime".

Is this a bug? Or is/will there a better way to do this? 

Using VS 16.8 Preview 2 and .net 5 preview 8, Microsoft.Windows.SDK.NET 10.0.18362.3-preview and CsWinRT 0.1.0-prerelease.200629.3

**Comment by hansmbakker** [comment]
This might be related to https://github.com/microsoft/CsWinRT/issues/290

**Comment by Marv51** [comment]
#290 is the same issue. Did not find that during search.
