### ISSUE TITLE
Interface with event changed from dotnet core 3.1 to C#/WinRT

### ISSUE THREAD

**Issue by Marv51** [microsoft/CsWinRT#384]
Not sure if this is an intentional change or not:
In dotnet core 3.1 and Microsoft.Windows.SDK.Contracts I was implementing the [ILoggingChannel ](https://docs.microsoft.com/en-us/uwp/api/windows.foundation.diagnostics.iloggingchannel?view=winrt-19041)interface like this:

```csharp
public class MyLoggingChannel : Windows.Foundation.Diagnostics.ILoggingChannel
{
       // ...
       public event TypedEventHandler<ILoggingChannel, object> LoggingEnabled
       {
           // this disables the event (and warning) but still implements the interface
           add { return new System.Runtime.InteropServices.WindowsRuntime.EventRegistrationToken(); }
           remove { }
       }
       // ...
}
```

with dotnet 5 preview 8 and Microsoft.Windows.SDK.NET 10.0.18362.3-preview I had to change this to:

```csharp
public class MyLoggingChannel : Windows.Foundation.Diagnostics.ILoggingChannel
{
       // ...
       public event TypedEventHandler<ILoggingChannel, object> LoggingEnabled
       {
           // this disables the event (and warning) but still implements the interface
           add {  }
           remove {  }
       }
       // ...
}
```

Because the change of an interface was somewhat unexpected, I thought I would report this here. Feel free to close, deleting the line is easy.

**Comment by AdamBraden** [comment]
@angelazhangmsft - document Breaking Change for RTM

**Comment by angelazhangmsft** [comment]
@Marv51 - we no longer project the System.Runtime.InteropServices.WindowsRuntime type, as it has been removed from .NET5.
