### ISSUE TITLE
Feature suggestion: allow partial classes during generation

### ISSUE THREAD

**Issue by MikeHillberg** [microsoft/CsWinRT#390]
This Xaml/WinUI issue is an interesting idea that can't be accomplished today. The idea is to add a [CancellationToken](https://docs.microsoft.com/dotnet/api/System.Threading.CancellationToken) to an API on [ContentDialog.ShowAsync](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.ContentDialog.ShowAsync), but CancellationToken is a .Net feature, and so can't be expressed as a WinRT API.

https://github.com/microsoft/microsoft-ui-xaml/issues/3220

One solution could be for the Xaml component to ship a .Net-specific ContentDialogHelper API, but that's not very discoverable.

Would it be possible for the Xaml component instead to ship a partial ContentDialog class with this method that gets mixed in to the generated class?

**Comment by Scottj1s** [comment]
Why wouldn't this just be implemented as another ShowAsync overload (e.g., in IContentDialog4)?

**Comment by Scottj1s** [comment]
How would this ShowAsync be implemented, since CancellationToken is not a WinRT type? I.e, what would it marshal to?  Wouldn't there still need to be an ABI method to accept the marshaled token and execute the cancel?  In that case, how about an extension method to provide a type safe wrapper?

**Comment by MikeHillberg** [comment]
Yes, an extension method would be good, and that's something we should be able to do today. Extension methods aren't as discoverable, but maybe it's good enough.

In this case the implementation would be something like:

```cs
public class ContentDialog
{
    IAsyncOperation<ContentDialogResult> ShowAsync(CancellationToken token)
    {
        token.Register(() => this.Hide());
        return this.ShowAsync();
    }
}
```

**Comment by Scottj1s** [comment]
I like the extension method for simplicity

**Comment by reflectronic** [comment]
Couldn't the async operation returned by `ShowAsync` interpret the `Cancel` method as hiding the dialog? Then, you could simply `await dialog.ShowAsync().AsTask(cancellationToken);`.

**Comment by MikeHillberg** [comment]
Yes, canceling the the async operation hides the dialog. The original ask though is about also fitting ContentDialog into the [cooperative cancellation model](https://docs.microsoft.com/en-us/dotnet/standard/threading/cancellation-in-managed-threads) that .Net has. So I was wondering about approaches in cs/winrt for a component to have extra APIs specific to .Net, in addition to its WinRT APIs that project automatically.

**Comment by Scottj1s** [comment]
Closing this request with agreement on the extension method idea, as that's specific to WinUI and doesn't add complexity to cswirnt
