### ISSUE TITLE
Fix intermittent unit test failures 

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#394]
There are two issues that occasionally cause the nightly build to fail:

1. [  X UnitTest.TestWinRT.Array_Nested_Call [45ms]
  Error Message:
   System.ArgumentException : Value does not fall within the expected range.
](https://microsoft.visualstudio.com/Dart/_build/results?buildId=26694612&view=logs&j=af683234-044d-5980-ba16-3a96b0eba294&t=69b6f12e-90b2-5747-cbd1-9b2ed0a66fd9&l=40)

2. [ Error Message:
   System.InvalidOperationException : Attempt to update previously set global instance.
  Stack Trace:
     at System.Runtime.InteropServices.ComWrappers.RegisterForTrackerSupport(ComWrappers instance)
](https://microsoft.visualstudio.com/Dart/_build/results?buildId=26705321&view=logs&j=af683234-044d-5980-ba16-3a96b0eba294&t=69b6f12e-90b2-5747-cbd1-9b2ed0a66fd9&l=55)

in both cases, the failing unit test itself may vary

**Comment by Scottj1s** [comment]
fixed ComWrappers issue (2), but range exception (1) still occurring

**Comment by AdamBraden** [comment]
Haven't seen the issue recently. Open new issue if it comes back.
