### ISSUE TITLE
Add CSWinRT version info to metadata for Microsoft.Windows.SDK.NET.Ref & Targeting packs

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/CsWinRT#398]
.NET5 Ref/Targeting packs need to be self contained, thus we include in the WinRT.Runtime.dll in the package. Typically this comes from a dependency reference in a nuget package. Thus there is no way to tell what version of cswinrt the Ref pack was built with unless you dig into the build output and check the file version of winrt.runtime.dll.

Proposal - At a minimum, add cswinrt version info to the nuget description. Also see if there is another way to add additional metadata, similar to what VS does for <build:Metadata> tag when building packaged apps.

**Comment by angelazhangmsft** [comment]
Can reopen if we see a need to do this
