### ISSUE TITLE
Move remaining code for WinRT.cs into the winrt.runtime.dll

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/CsWinRT#405]
There isn't much that remains in WinRT.cs and WinRT_Interop.cs, we should consider moving this into the runtime.

**Comment by jkoritzinsky** [comment]
I think it's good to keep some of the implementation details in WinRT.cs as internal types. It reduces the amount of public surface area that needs to be maintained in future versions and enables C#/WinRT to be able to evolve more easily.
