### ISSUE TITLE
Identify and evaluate scenarios for packaging and versioning of Windows, WinUI, CsWinRT (winrt.runtime.dll)

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#417]
Ensure that at least this scenario can be supported:

- Cswinrt nupkg is updated with a hot fix
- App developer adds a direct cswinrt nuget reference just to pick up winrt.runtime.dll (note: this might require ExcludeAssets or a project property to avoid creating a projection)
- Package resolution selects the newer Cswinrt winrt.runtime.dll over the TFM-supplied one 
- Does Nuget support this?  Does it require some assist from the TFM metapackage?

There may be other scenarios

**Comment by AdamBraden** [comment]
will track this via #459
