### ISSUE TITLE
-include Windows.UI.Colors also projects Windows.UI.Color

### ISSUE THREAD

**Issue by MilesCohen-MS** [microsoft/CsWinRT#426]
It looks like cswinrt is projecting more than just the class name specified using -include. In particular I was trying to project the Windows.UI.Colors class, but when doing so cswinrt pulled in Windows.UI.Color, which exists in the same namespace. Even putting -exclude Windows.UI.Color doesn't remove it.

Note: I should probably using Microsoft.UI.Colors instead, so this particular projection may not be needed for my project. But I thought I should log the issue with cswinrt regardless in case it comes up in other scenarios.

**Comment by AdamBraden** [comment]
Moving to Microsoft.UI.Colors should solve this issue.
