### ISSUE TITLE
Performance of TryUnwrapObject can be improved by caching attributes.

### ISSUE THREAD

**Issue by bartekk8** [microsoft/CsWinRT#437]
When looking into XAML's Dependency Property performance, I noticed that there's a significant overhead coming from using reflection to get custom attributes in WinRT.ComWrappersSupport.TryUnwrapObject.  If these were cached, it could potentially reduce time spent in this method.  Stack info below:

![image](https://user-images.githubusercontent.com/59668723/94179562-89725900-fe51-11ea-9ffa-b33ab756bab8.png)

**Comment by jkoritzinsky** [comment]
We may be able to improve this scenario for .NET 5 by not even having to look at custom attributes if we enhance the `IWinRTObject` interface that is being added in #369.

**Comment by AdamBraden** [comment]
Leaving for .NET5 GA to consider Jeremy's suggestion.
