### ISSUE TITLE
CSWrint does not support ready to run

### ISSUE THREAD

**Issue by wli3** [microsoft/CsWinRT#442]
[ConsoleApp21.zip](https://github.com/microsoft/CsWinRT/files/5294307/ConsoleApp21.zip)

use above asset. In commandline run ` dotnet publish -r win-x64`. Get error:

C:\Program Files\dotnet\sdk\5.0.100-rc.2.20468.8\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(401,28): error MSB4094: "C:\Users\wul\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.19041.1-preview\lib\Microsoft.Windows.SDK.NET.dll;C:\Users\wul\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.19041.1-preview\lib\Microsoft.Windows.SDK.NET.dll" is an invalid value for the "CompilationEntry" parameter of the "RunReadyToRunCompiler" task. Multiple items cannot be passed into a parameter of type "Microsoft.Build.Framework.ITaskItem". [C:\work\temp\ConsoleApp21\ConsoleApp21\ConsoleApp21.csproj]

**Comment by mangod9** [comment]
@AntonLapounov

**Comment by Scottj1s** [comment]
@ujjwalchadha this may not be a CsWinRT issue - William is following up with more investigation

**Comment by dsplaisted** [comment]
This looks like a bug in the .NET SDK with runtime packs with `RuntimePackAlwaysCopyLocal` = true, which is only the Microsoft.Windows.SDK.NET.Ref packs.

The `_ResolveCopyLocalAssetsForPublish` target adds `_ResolvedCopyLocalPublishAssets` items for assets from runtime packs for self-contained apps:

```xml
      <ItemGroup>
        <_ResolvedCopyLocalPublishAssets Include="@(RuntimePackAsset)" Condition="'$(SelfContained)' == 'true'" />
      </ItemGroup>
```

The `_ComputeResolvedCopyLocalPublishAssets` target (which depends on `_ResolveCopyLocalAssetsForPublish`) adds `_ResolvedCopyLocalPublishAssets` items from runtime packs where `RuntimePackAlwaysCopyLocal` is true:

```xml
      <!-- Include RuntimePackAsset where RuntimePackAlwaysCopyLocal is true -->
      <_ResolvedCopyLocalPublishAssets Include="@(RuntimePackAsset)"
                              Condition="'%(RuntimePackAsset.RuntimePackAlwaysCopyLocal)' == 'true'">
        <DestinationSubPath>%(ReferenceCopyLocalPaths.DestinationSubDirectory)%(ReferenceCopyLocalPaths.Filename)%(ReferenceCopyLocalPaths.Extension)</DestinationSubPath>
      </_ResolvedCopyLocalPublishAssets>
```

So for self-contained apps, the items from the Microsoft.Windows.SDK.NET.Ref pack get added twice.  We should update the logic to avoid this.

**Comment by stevenbrix** [comment]
This probably isn't related, but I just came across this issue when publishing with `PublishTrimmed` set to true

@dplaisted and @wli3, is this a known issue, or just related to windows?

   "c:\dev\winui\Samples\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp.sln" (default target) (1:2) ->
       "c:\dev\winui\Samples\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp (Package)\WinUICsD
       esktopSampleApp (Package).wapproj.metaproj" (default target) (6) ->
       "c:\dev\winui\Samples\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp (Package)\WinUICsD
       esktopSampleApp (Package).wapproj" (default target) (2:6) ->
       "c:\dev\winui\Samples\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUICsDesktopSamp
       leApp.csproj" (DesktopBridgePublishItemsOutputGroup target) (4:13) ->
       (_RunILLink target) ->
         ILLink : error IL1018: Missing argument for '--nowarn' option [c:\dev\winui\Samples\WinUICsDesktopSampleApp\Wi
       nUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp.csproj]


       "c:\dev\winui\Samples\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp.sln" (default target) (1:2) ->
       "c:\dev\winui\Samples\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp (Package)\WinUICsD
       esktopSampleApp (Package).wapproj.metaproj" (default target) (6) ->
       "c:\dev\winui\Samples\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp (Package)\WinUICsD
       esktopSampleApp (Package).wapproj" (default target) (2:6) ->
       "c:\dev\winui\Samples\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUICsDesktopSamp
       leApp.csproj" (DesktopBridgePublishItemsOutputGroup target) (4:13) ->
       (ILLink target) ->
         C:\Program Files (x86)\dotnet\sdk\5.0.100-rc.1.20452.10\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.ta
       rgets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting th
       e PublishTrimmed property to false. [c:\dev\winui\Samples\WinUICsDesktopSampleApp\WinUICsDesktopSampleApp\WinUIC
       sDesktopSampleApp\WinUICsDesktopSampleApp.csproj]

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:37.11

c:\dev\winui>.buildtools\MSBuild\Current\Bin\MSBuild.exe Samples\XamlControlsGallery\XamlControlsGallery.Desktop.sln /p:Platform=x86 /p:Configuration=Debug /restore /m /bl
Microsoft (R) Build Engine version 16.8.0-preview-20452-03+5dee11854 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

c:\dev\winui\.buildtools\MSBuild\Current\Bin\.buildtools\MSBuild\Current\Bin\MSBuild.exe /bl /m /p:Platform=x86 /p:Configuration=Debug /restore Samples\XamlControlsGallery\XamlControlsGallery.Desktop.sln
Build started 9/30/2020 12:31:48 PM.
     1>Project "c:\dev\winui\Samples\XamlControlsGallery\XamlControlsGallery.Desktop.sln" on node 1 (Restore target(s))
       .
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|x86".
       _GetAllRestoreProjectPathItems:
         Determining projects to restore...
       Restore:

**Comment by AntonLapounov** [comment]
@stevenbrix Please open a separate issue for that and include repro steps.

**Comment by ujjwalchadha** [comment]
This has been fixed by the [latest .net](https://github.com/dotnet/installer). (net 5.0.100 RTM or greater).
