### ISSUE TITLE
Project WinRT enum Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction to System.Collections.Specialized.NotifyCollectionChangedAction

### ISSUE THREAD

**Issue by RealTommyKlein** [microsoft/CsWinRT#454]
In WinUI Preview 3, we plan to introduce a new enum, `Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction`, to replace our existing usage of `Windows.UI.Xaml.Interop.NotifyCollectionChangedAction`.  Their definitions are identical outside of the namepace:

```
namespace Microsoft.UI.Xaml.Interop
{
    public enum NotifyCollectionChangedAction
    {
        Add = 0,
        Remove = 1,
        Replace = 2,
        Move = 3,
        Reset = 4,
    }
}
```
We would like to have projection support for this new type in lieu of the old Windows.UI.Xaml type, so that `Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction` projects to `System.Collections.Specialized.NotifyCollectionChangedAction`.

The `Microsoft.UI.Xaml.Interop.NotifyCollectionChangedEventArgs.Action` property would also have its type updated from `Windows.UI.Xaml.Interop.NotifyCollectionChangedAction` to `Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction`, so its projection to `System.Collections.Specialized.NotifyCollectionChangedEventArgs` may need to be updated as well.

**Comment by RealTommyKlein** [comment]
(@Scottj1s - this is what we had talked about today)

**Comment by Scottj1s** [comment]
@RealTommyKlein we already provide this projection (search code for NotifyCollectionChangedAction). Is it not working correctly?

**Comment by RealTommyKlein** [comment]
@Scottj1s - thanks for the response!  Turns out there are some other unrelated issues which are preventing us from validating it works correctly.  Once those are resolved, I will test the existing projection support.

**Comment by Scottj1s** [comment]
closing this issue as there's nothing actionable atm - please open a new issue if necessary (i.e., if there's a bug in the NotifyCollectionChangedAction projection)
