### ISSUE TITLE
`ref const`-Parameter not handled correctly

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/CsWinRT#456]
Given my previous issues with winrt related APIs, I discovered, that `ref const` parameters are _not_ handled correctly.
For following IDL
```
struct Argument
{
	Int32 Parameter;
};

interface IHandler
{
	void Handle(ref const Argument arg);
};
```
I expect the CsWinRT projection to generate an interface that respects this statement:
> A const reference parameter is used for efficient input parameter passing of large value types (but not simple types such as integral or floating-point numbers, nor enums). Methods receive such parameters as a reference to the actual value

This states that `ref const`-parameters are used for _input_ values passed _by reference_. Following interface is generated by CsWinRT `0.1.0-prerelease.200928.7`:
```
public interface IHandler
{
    void Handle(Argument arg);
}
```
The `Argument`-type is translated correctly:
```
public struct Argument: IEquatable<Argument>
{
    public int Parameter;

    public Argument(int _Parameter)
    {
        Parameter = _Parameter; 
    }

    public static bool operator ==(Argument x, Argument y) => x.Parameter == y.Parameter;
    public static bool operator !=(Argument x, Argument y) => !(x == y);
    public bool Equals(Argument other) => this == other;
    public override bool Equals(object obj) => obj is Argument that && this == that;
    public override int GetHashCode() => Parameter.GetHashCode();
}
```

The parameter should either be projected as `ref` (as .NET Core 3.1 does it) or `in` (as I expect an _input parameter_ to be handled).

Previous Issues (for sake of linking)
- [winrt-related/#162](https://github.com/MicrosoftDocs/winrt-related/issues/162)
- [winrt-related/#149](https://github.com/MicrosoftDocs/winrt-related/issues/149)

**Comment by Scottj1s** [comment]
thanks @AliveDevil - triaged to our next milestone, since this would be a breaking change in the projection

**Comment by jkoritzinsky** [comment]
If this gets projected as `in Argument`, then it won't be a source breaking change. It will only be a binary breaking change.

**Comment by AliveDevil** [comment]
It is source breaking as well. There may be interface implementations with the in-argument, which would need to be changed. For sealed classes there is no source breaking though, as they cannot be derived from.

**Comment by jkoritzinsky** [comment]
True, usage of the methods wouldn’t be broken but implementation would.
