### ISSUE TITLE
Call CsWinRT on PackageReference, instead of pushing the projection into the published package

### ISSUE THREAD

**Issue by simonferquel** [microsoft/CsWinRT#457]
The promise of WinRT at the beginning was to be a metadata system that whatever toolset could consume to produce language-specfic/optimized projections. The fact that a library should author the .net-specific projection alongside his library feel very weird in that sense.

Plus, it makes it difficult for the following scenarios:
- Imagine I am an author of a WinRT component written in C++ or rust. I now have to add cswinrt (and probably .net core runtime) to my CI infrastructure (plus add a bit of scripting) to publish .Net specific projections with it.
- I am a consumer of a WinRT package that is now in maintenance mode and not actively developped (and does not have .net specific projections in it). I need to build my own projection package somewhow to consume it via cswinrt
- I am a consumer of a WinRT package that comes with a .net projection build with a slightly outdated cswinrt version. I want to get advantage of the latest cswinrt advancements.
- I am a consumer of 2 WinRT packages with projections built from 2 different versions of cswinrt, and thus reference 2 different versions of the cswinrt runtime package (which may be incompatible ?). 

If cswinrt is invoked transparently on the consumer side, we (partially) solve the issue, as all dependencies will have their projection code generated with the same toolset.
Only problem here is about transitive dependencies. So I certainly expose a lot of problems in this ticket, but certainly not a final solution :D

**Comment by Scottj1s** [comment]
Thanks for the suggestion.  We've been considering that model as well - as you point out, it solves many distribution complexities.  At this point, it's too late to consider for RTM, as it's fairly disruptive.  But we'll keep it in the backlog for a future release.

**Comment by simonferquel** [comment]
Thanks. In the meantime, have you considered splitting .net projection and implementation into separate packages ? 
It feels like it could make it easier to deal with versioning of cswinrt (still without dealing with transitive dependencies) by allowing people to create their own projection library for all winmds they depend on instead to be forced to consume pre-baked (and potentially incompatible) projections.

**Comment by simonferquel** [comment]
Plus in a longer term, it would make it easier to consume those packages with a "generate projection on consuming" model

**Comment by Scottj1s** [comment]
Yes, developers can create their own projection libraries today, and component authors can choose to package their projection and implementation binaries separately.  That decoupling adds complexity for consumers, of course, who are expecting to add a nuget reference to a single entity.  But it might have some value for versioning.

Additionally, a project can add an explicit reference to the C#/WinRT nuget package to pick up winrt.runtime.dll fixes outside the version implicitly included with the Windows SDK (Microsoft.Windows.SDK.Net.Ref, via the TFM).

**Comment by Scottj1s** [comment]
Related issue on generating projections on demand (consuming side):
https://github.com/microsoft/CsWinRT/issues/314

It's closed, but really on the backlog

**Comment by angelazhangmsft** [comment]
We've added embedded support in CsWinRT which should solve part of this issue - https://github.com/microsoft/CsWinRT/blob/master/docs/embedded.md

We currently don't have plans to change the projection mechanics, but can consider feedback for the future.
