### ISSUE TITLE
Support light-up of WinRT APIs without limiting by TFM

### ISSUE THREAD

**Issue by dotMorten** [microsoft/CsWinRT#458]
If I want to use a WinRT API in a light-up scenario, I have to target `net5-windows10.0.17763`, meaning I can't just support build a class library that targets `net5-windows`. This is a bit problematic because the default target for a .NET 5 WPF project is `net5-windows` so my class library will not be compatible out of the box, but require the developer to increase the min-level.

In .NETCore 3.1 I could just use reflection against the WinRT APIs, and it could light up all the way down to Windows 8 (since the specific API I'm interested in came with Win8). However reflection into WinRT APIs are now broken in 5.0, so how would we achieve this today?

Now I get for applications, they can just do API checks to do adaptive code, but this approach doesn't work for class libraries, as apps referencing that class library have to increase their TFM beyond what they might want to increase it to.

Multi-targeting doesn't work either, because it would again mean anyone targeting `net5-windows` would not get light-up from WinRT APIs on Windows 8+. even if they are on the latest version of Windows 10.

Here's the specific scenario: If an app using my class library runs on Windows 8 or up, it'll be able to use the WinRT GeoLocator WinRT apis and add location information to the application. If the user runs on Win 7 that feature won't be enabled. I solved that in .NET Core 3.1 by using reflection into WinRT. If the API was found, it'll light up, otherwise report that location isn't supported on that platform. It's seems that with .NET 5, I'm forcing developers to only build apps that targets 17763 and up.

My understanding is that to do this in a class library, I'll have to multi-target for `netcoreapp3.1` and `net5-windows10.0.17763`. This becomes problematic if my user uses the library in a WPF application. Creating a new WPF Project, will default to targeting `net5-windows`. Adding a reference to my library, the target fallback will pick `netcoreapp3.1` since `net5-windows10.0.17763` is a higher version. This would cause it to use the reflection-based WinRT APIs that can be used in `netcoreapp3.1` but is broken in `net5` - so when the user runs the application it won't work correctly, and I can only begin to imagine all the support issues that'll come out of this and reminding people to upgrade the target version.

**Comment by Scottj1s** [comment]
@dotMorten thanks for raising the issue.  We'll give some thought to how C#/WinRT can support light up in class libraries.

**Comment by dotMorten** [comment]
@Scottj1s Thanks. I was trying to build CsWinRT and then copy the generated files for geolocator into a project, but had a hard time getting it to work.

My preferred solution is to be able to just target `netcoreapp3.1` and the assembly would work fine on `net5-windows` as well (provided you're on Windows 8+). Alternatively I can multi-target `netcoreapp3.1` + `net5-windows` (not `net5-windows10.0.xxxxx`). It's a little more work to multi target, and more code to maintain, so if that can be avoided that'll be good.

**Comment by angelazhangmsft** [comment]
Need a sample demonstrating SupportedOSPlatform attributes

**Comment by angelazhangmsft** [comment]
@dotMorten - We recently completed C#/WinRT embedded support work in [v1.4.1](https://github.com/microsoft/CsWinRT/releases/tag/1.4.1.211117.1), which should help address this scenario. These [docs](https://github.com/microsoft/CsWinRT/blob/master/docs/embedded.md) and [samples](https://github.com/microsoft/CsWinRT/tree/master/src/Samples/TestEmbedded) provide more details on how to use the support.

Would love to get your feedback on this!

**Comment by dotMorten** [comment]
@angelazhangmsft Thanks I noticed. Already added it to our backlog to look into.

**Comment by angelazhangmsft** [comment]
Tracking improved light-up support in #832
