### ISSUE TITLE
Reconcile versioning across .NET SDK, Windows SDK, and C#/WinRT

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#459]
Currently, the TFM-specified runtime pack adds a reference to Microsoft.Windows.SDK.Net.Ref (the "Windows SDK") for .NET 5 projects.  The Windows SDK package uses the Windows 10 versioning scheme, incrementing the last field for each release - e.g., 10.0.19041.6-preview.  This does not adhere to [SemVer v2 policy](https://semver.org/) for compatibility.  Because the Windows SDK is built against specific versions of the .NET SDK and C#/WinRT, its possible that updating either of those could create a binary breaking change in the Windows SDK projection.  We need a strategy for how to version safely, incorporating potentially breaking changes to any components of the Windows SDK.

**Comment by Scottj1s** [comment]
Recommendations:

- Per .NET team, avoid breaking changes in cswinrt if at all possible.  There is not a reliable mechanism to flow a breaking change across TFM references (regardless of semver), and they are highly disruptive to the ecosystem.  
- Tie updates to cswinrt to .NET servicing schedule so that users rarely have to take an explicit nuget reference to cswinrt
- Document (and hopefully improve) the user experience (build/runtime errors) resulting from transitive mismatches in SDK references (app builds with Windows SDK 10.0.19041.6 and a component that in turn builds with 10.0.19041.7)
- Assembly version updates to winrt.runtime.dll are okay - document potential build breaks (downgrades, etc)

**Comment by manodasanW** [comment]
We can resolve this once we have a markdown which documents our assembly version decisions and build/runtime errors.

**Comment by Scottj1s** [comment]
closing, with versioning.md creation
