### ISSUE TITLE
Derived classes need test coverage

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#463]
A recent change (IDynamicInterfaceCastable support) created several serious regressions with derived classes, specifically handling of the _inner field.  This has exposed a lack of test coverage on derived classes.  A few cases to add:

- Call operator== through base
- Compare base and derived
- Cast base to derived interfaces
- All of the above with objects created both in markup and code
- etc

**Comment by Scottj1s** [comment]
May be worth porting the cppwinrt composable test cases:
[test_component_base](https://github.com/microsoft/cppwinrt/tree/c36cf05f5030726c8ada1b89fc78bd470f737032/test/test_component_base)
[test_component_derived](https://github.com/microsoft/cppwinrt/tree/c36cf05f5030726c8ada1b89fc78bd470f737032/test/test_component_derived)

**Comment by AdamBraden** [comment]
finish test winrt work, then come back to this for cswinrt side.

**Comment by AdamBraden** [comment]
agreed its been covered
