### ISSUE TITLE
Restore fallback to all loaded assemblies in FindTypeByNameCore 

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#465]
With module initializers, projection assemblies no longer need to be registered.  But projected XAML classes (e.g., MainPage) in the app still do, which requires an explicit registration in the app startup path, like:
        public App()
        {
            WinRT.ComWrappersSupport.RegisterProjectionAssembly(typeof(App).Assembly);
        }

Failure to do this results in hard to debug TypeLoadExceptions.  The preference for projectionAssemblies in TypeNameSupport.FindTypeByNameCore should be preserved (so that projection types take precedence over app types - a previously reported issue), with a fallback for loaded assemblies so that apps don't have to explicitly register.

**Comment by j0shuams** [comment]
to get XCG app working I also needed to add 

WinRT.ComWrappersSupport.RegisterProjectionAssembly(typeof(App).Assembly);

**Comment by Scottj1s** [comment]
@j0shuams right, that requirement will go away with this fix
