### ISSUE TITLE
WinUI App: PublishTrimmed in publish options removes required dlls in winui packaged app

### ISSUE THREAD

**Issue by ujjwalchadha** [microsoft/CsWinRT#475]
TargetFramework: net5.0-windows10.0.18362.0
WinUI Version: 3.0.0-development.201006.1-CI

Publishing an app with PublishTrimmed option turned on crashes the app with following error:
An assembly specified in the application dependencies manifest (WinUISample.deps.json) was not found:
 package: 'runtimepack.Microsoft.NETCore.App.Runtime.win-x64', version: '5.0.0-rtm.20502.8'
 path: 'Microsoft.CSharp.dll''WinUISample.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll

**Comment by AdamBraden** [comment]
Not cswinrt related. This needs to be an issue in the WinUI repo.
