### ISSUE TITLE
Unable to Create a BluetoothLEAdvertisementFilter with BluetoothLEAdvertisement ServiceUuids

### ISSUE THREAD

**Issue by marcpopMSFT** [microsoft/CsWinRT#496]
---
**Issue moved from dotnet/sdk#13940**
- Please respond to @michaelerice-github.

---

_From @michaelerice-github on Thursday, October 1, 2020 6:40:05 PM_

Using nuget pkg "Microsoft.Windows.SDK.Contracts", version "10.0.19041.1"

When you try to create a BluetoothLEAdvertisement to use within a BluetoothLEAdvertisementFilter, the ServiceUuids property is read only:

			var bluetoothLEAdvertisementWatcher= new BluetoothLEAdvertisementWatcher
			{
				ScanningMode = BluetoothLEScanningMode.Active,

			};

			var bluetoothLEAdvertisement = new BluetoothLEAdvertisement
			{
				ServiceUuids = new Guid[] { GattServiceUuids.BloodPressure }, // read-only
			};

			var bluetoothLEAdvertisementFilter = new BluetoothLEAdvertisementFilter
			{
				Advertisement = bluetoothLEAdvertisement
			};

			bluetoothLEAdvertisementWatcher.AdvertisementFilter = bluetoothLEAdvertisementFilter;

**Comment by manodasanW** [comment]
This doesn't look like a projection issue.  The [platform API](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisement.serviceuuids?view=winrt-19041#Windows_Devices_Bluetooth_Advertisement_BluetoothLEAdvertisement_ServiceUuids) itself it documented as a Get only property, so you would not be able to reinitialize the list.  You would need to either add to the list after construction to add your Guid or use a collection initializer which does something similar like the following:

`
		var bluetoothLEAdvertisement = new BluetoothLEAdvertisement
		{
			ServiceUuids = { GattServiceUuids.BloodPressure },
		};
`
