### ISSUE TITLE
usage doc is out of date

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#498]
https://github.com/microsoft/CsWinRT/blob/master/USAGE.md

It looks like the usage doc could be updated with a lot of the good information in this blog post: https://blogs.windows.com/windowsdeveloper/2020/10/13/c-winrt-version-0-8-and-the-net5-rc2-release/

**Comment by AdamBraden** [comment]
Yep - the content has largely moved to https://github.com/microsoft/CsWinRT/blob/master/nuget/readme.md. but usage should provide the example
