### ISSUE TITLE
CSWinRT 0.9.0 - CS0539 errors with HasUnwrappableNativeObject

### ISSUE THREAD

**Issue by RealTommyKlein** [microsoft/CsWinRT#503]
CSWinRT 0.9.0 has a regression in generating projections (which does not happen in 0.8.0).  When compiling the generated CSWinRT projections for WinUI 3, there’s now a few thousand errors about a HasUnwrappableNativeObject missing on various types, e.g.:
`Microsoft.UI.Xaml.Interop.cs(140,31): error CS0539: 'BindableVectorChangedEventHandler.NativeDelegateWrapper.HasUnwrappableNativeObject' in explicit interface declaration is not found among members of the interface that can be implemented`

**Comment by Scottj1s** [comment]
most likely requires this, until the 0.9.0 propagates to the TFM Windows SDK:
```
  <ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.8-preview" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.8-preview" />  
  </ItemGroup>

```

**Comment by Scottj1s** [comment]
confirmed that 10.0.18362.8-preview is required to build against an updated winrt.runtime.dll (downstream build issues still exist)
