### ISSUE TITLE
CSWinRT can't find windows metadata

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#507]
Repro app: [CsWinRTRepro.zip](https://github.com/microsoft/CsWinRT/files/5392579/CsWinRTRepro.zip)
binlog: [cswinrtrepro.zip](https://github.com/microsoft/CsWinRT/files/5392597/cswinrtrepro.zip)

This app is a plain WPF .net5 app with a reference to a C++/WinRT component. cswinrt.exe fails with the error:

```
1>EXEC : error : 'Type 'Windows.Foundation.Metadata.MarshalingType' could not be found' when processing RuntimeComponent1.Class
1>EXEC : error : Type 'Windows.Foundation.Metadata.MarshalingType' could not be found
```

Building from the command line works, because the developer command prompt sets the `WindowsSDKVersion` environment variable, but this isn't set in VS.

Also, I'm not sure if it's of any consequence, but the C++ component is referencing the 19041 SDK, but the WPF app is targeting 18362. It seems like this configuration should be invalid? I would think cswinrt would pick up the windows metadata based on the TFM, but if it does that, then it won't match the windows metadata used to build the component

**Comment by Scottj1s** [comment]
> I would think cswinrt would pick up the windows metadata based on the TFM

There's no windows metadata in Microsoft.Windows.SDK.NET.Ref.  Mano is looking at adding it for this very scenario.  Meantime, users will have to supply it from the Windows SDK or Contracts package.  And the build should detect when it's missing and error out with a diagnostic (versus the error you're seeing)

**Comment by Scottj1s** [comment]
Workaround (e.g.):
set CsWinRTWindowsMetadata=10.0.19041.0
