### ISSUE TITLE
Microsoft.UI.Xaml.Data.ICustomProperty not being excluded from projection

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#509]
so it's showing up in winrt.runtime.dll and microsoft.winui.dll.  an entry should be made to cswinrt\helpers.h, and breaking change relnote posted

**Comment by AdamBraden** [comment]
Need to coordinate with WinUI, potentially breaking change.
This type should be provided by WinRT.Runtime.dll, but WinUI is projecting when it shouldn't be.

**Comment by AdamBraden** [comment]
@stevenbrix as fyi

**Comment by stevenbrix** [comment]
Thanks @AdamBraden, how will users be affected by this?

**Comment by Scottj1s** [comment]
The reason this is a breaking change is that assembly-qualified references to ICustomProperty must now be updated to find the type in winrt.runtime.dll, and not Microsoft.WinUI.dll

**Comment by Scottj1s** [comment]
Reviewing the code, I don't think this change is warranted.  There's no conflict between the public projected ICustomProperty* interfaces in Microsoft.WinUI.dll, and the internal managed implementations provided for all CCWs in winrt.runtime.dll.  We could go to some trouble to consolidate these, and create a breaking change, or just leave things as is.
