### ISSUE TITLE
System.IO.FileLoadException - SDK version mismatch in library/consuming app with WinRT type returned

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#521]
Library with SDK version 10.0.19041.7, console app with 10.0.19041.6-preview.
Exception thrown in console app upon calling the library when it returns a WinRT type (e.g. creating a new Windows.Devices.Geolocation.Geolocator();)

System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'Microsoft.Windows.SDK.NET, Version=10.0.19041.7, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
  Source=TestLibrary

Also get this warning when building:
Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3277	Found conflicts between different versions of "Microsoft.Windows.SDK.NET" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.	TestConsoleApp	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2123

**Comment by DHowett** [comment]
This was closed by #541, which only updated the documentation. Reading over that doc update, I can't determine why it was closed. I ended up hear searching for this exact issue.

**Comment by angelazhangmsft** [comment]
@DHowett - the Scenarios in this [versioning spec](https://github.com/microsoft/CsWinRT/blob/master/docs/versioning.md) from the PR I just linked above document this issue. Let me know if you have questions.

**Comment by DHowett** [comment]
@angelazhangmsft thanks, that's.. verbose. It is enlightening, if I were a .NET core developer. As a user who's running into this issue, it offers no help at all :smile:
