### ISSUE TITLE
IBufferByteAccess.Buffer fails for netstandard

### ISSUE THREAD

**Issue by ujjwalchadha** [microsoft/CsWinRT#525]
IBufferByteAccess (cswinrt/strings/additions/IBufferByteAccess.cs) doesn't have the Vftbl properly initialized and fails to call the Do_Abi methods

Repro:
Run test TestBuffer in TestComponentCSharp_Tests.cs on netstandard

**Comment by j0shuams** [comment]
@ujjwalchadha Does this fix by Scott resolve this? https://github.com/microsoft/CsWinRT/pull/504/commits/50db586a154972e4a460984a5dff95e999ed8796

**Comment by AdamBraden** [comment]
fixed by commit above #504
