### ISSUE TITLE
stabilize winrt.runtime.dll version number

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#537]
At this point, the `WinRT.Runtime.dll` `AssemblyVersion` should stabilize. See the guidance here on assembly versioning:
 
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/versioning
https://stackoverflow.com/questions/64602/what-are-differences-between-assemblyversion-assemblyfileversion-and-assemblyin

The same should go for `Microsoft.Windows.SDK.Net.dll`

**Comment by Scottj1s** [comment]
For WinUI preview3, winrt.runtime.dll should set AssemblyVersion to 1.1 and manually update thereafter (with API changes)

**Comment by manodasanW** [comment]
Resolved by #578
