### ISSUE TITLE
Projecting an implementation of  Microsoft.UI.Xaml.Interop.IBindableVector generates incorrect method names

### ISSUE THREAD

**Issue by ujjwalchadha** [microsoft/CsWinRT#539]
Steps to repro:
1. Try to project implementation of IBindableOfVector by adding the following code to TestComponentCharp.idl:
```
    [default_interface]
    runtimeclass IBindableVectorTest : Microsoft.UI.Xaml.Interop.IBindableVector
    {
       
    }
```
2. Run build.cmd

The build fails with compilation errors in the generated code (Something like: 'IBindableVectorTest.Size' in explicit interface declaration is not found among members of the interface that can be implemented)

**Comment by ujjwalchadha** [comment]
A similar thing happens for System.Collections.IEnumerable. Steps to repro:
1. Try to project implementation of IBindableOfVectorView (instead of IBindableVector as above) by adding the following code to TestComponentCharp.idl:
```
    [default_interface]
    runtimeclass IBindableVectoiewrTest : Microsoft.UI.Xaml.Interop.IBindableVector
    {
       
    }
```
2. Run build.cmd

**Comment by AdamBraden** [comment]
Confirm behavior in UWP/.NETNative and ensure we are consistent. Document as required.
