### ISSUE TITLE
Process Documentation

### ISSUE THREAD

**Issue by AdamBraden** [microsoft/CsWinRT#544]
During intermediate builds we need to improve our release notes and documentation for a Recommended configuration, and what partners need to do to update.

- [x] Create a ReleaseProcess.md that includes our recommended guidance for adopting a given release, breaking changes, the set (cswinrt, runtime, sdk) combination of libraries and toolsets required for distributed communications. *This has been addressed by C#/WinRT Release notes + versioning.md*

- [x] Update Relnotes with .NET release info to ensure that devs can correlate a fixed issue with a .NET 5 version

- [x] Readme points to latest GA vs PreRelease

- [ ] Clarification of Triage process and SLAs

**Comment by angelazhangmsft** [comment]
@AdamBraden anything else needs to be done here - does versioning.md resolve this?
