### ISSUE TITLE
LoadLibrary Namespace to native DLL name mapping inconsistent

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/CsWinRT#549]
There are issues if namespace and native dll name do not correspond (e.g. automatic namespace sanitization).

If my native dll is called "lib-something" (in my case "winrt-something"), the namespace is automatically sanitized to "lib_something" ("winrt_something").
As the current implementation automatically tries "lib_something.dll" instead of "lib-something.dll" this fails immediately with a ModuleNotFound exception. Is there anything I can do to ensure that CsWinRT can load a dll when a dash has been sanitized in the namespace?

**Comment by AdamBraden** [comment]
Do you have a reproducible bug? Ideally you should have an app or package manifest for class registration lookup logic. We do have a 'fallback' mechanism that uses a naming convention. See https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/#winrt-type-activation

**Comment by AliveDevil** [comment]
App/Package Manifest works as long as the app is not running on an older Windows version as Windows 10 19H1 - unless it uses UndockedRegFreeWinRT.

So … on Windows 10 older than 19H1 the fallback mechanism (without Undocked RegFree WinRT) will not work.
Repro in above commit/repository.

**Comment by Scottj1s** [comment]
@AliveDevil, this behavior is expected.  It starts with the C++/WinRT project template, which adjusts the project name you supply, removing "unsafe characters".  You can see that adjustment in your repro's Class.idl, with "namespace lib_test".  That new namespace then propagates to all downstream tools, like C#/WinRT.

See info on $safeprojectname$ here:
https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2019
