### ISSUE TITLE
Windows.ApplicationModel.Package.HasUnwrappableNativeObject has no implementation

### ISSUE THREAD

**Issue by AliveDevil** [microsoft/CsWinRT#555]
CSWinRT: v1.0.2-prerelease.201021.1
.NET SDK: 19041

Reference in project:
```
  <PropertyGroup>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <CsWinRTWindowsMetadata>10.0.19041.0</CsWinRTWindowsMetadata>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.0.2-prerelease.201021.1" />
  </ItemGroup>
```

Following crashes:
```
Path.Combine(Package.Current.InstalledLocation.Path, "sample.dll");
```

with this exception:
```
Method 'get_HasUnwrappableNativeObject' in type 'Windows.ApplicationModel.Package' from assembly 'Microsoft.Windows.SDK.NET, Version=10.0.19041.6, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
```

**Comment by AliveDevil** [comment]
Looking at the decompilation of `Microsoft.Windows.SDK.NET (10.0.19041.6)` Package does indeed not implement `HasUnwrappableNativeObject`.

**Comment by Scottj1s** [comment]
This was a breaking change in the final version (1.0.1) of cswinrt, which requires a newer version of Microsoft.Windows.SDK.NET - 10.0.19041.8 or better, in your case.  You can specify that with explicit FrameworkReferences:

  <ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.10" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.10" />  
  </ItemGroup>
