### ISSUE TITLE
Accessing properties dictionary of WebAccount fails with invalid cast exception

### ISSUE THREAD

**Issue by bgavrilMS** [microsoft/CsWinRT#574]
1. Create a new net5.0-windows10.0.17763.0 app (console or whatever)
2. On a machine where you have at least one Work and School account registered run the following:

```csharp
            Windows.Security.Credentials.WebAccountProvider provider = await WebAuthenticationCoreManager.FindAccountProviderAsync(
                "https://login.microsoft.com", "organizations");

            FindAllAccountsResult findResult = await WebAuthenticationCoreManager.FindAllAccountsAsync(provider, "872cd9fa-d31f-45e0-9eab-6e460a02d1f1"); // client ID does not matter
            
           // result contains all Work and School accounts
            Windows.Security.Credentials.WebAccount firstAccount = findResult.Accounts[0];

            // both of these fail with System.InvalidCastException: 'Invalid cast from 'WinRT.IInspectable' to 'ABI.System.Collections.Generic.IEnumerable`1
            bool keyFound = firstAccount.Properties.TryGetValue("Authority", out string authority);
            var count = firstAccount.Properties.Count;
```

**Actual:** 

Invalid cast from 'WinRT.IInspectable' to 'ABI.System.Collections.Generic.IEnumerable`1

**Comment by bgavrilMS** [comment]
Looks similar to https://github.com/microsoft/CsWinRT/issues/535

**Comment by manodasanW** [comment]
Properties look to be a [IReadOnlyDictionary](https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.webaccount.properties?view=winrt-19041#Windows_Security_Credentials_WebAccount_Properties), so it should be the same issue.  We plan to have a fix in the next .NET SDK servicing update of the Windows SDK projection.  In the mean time, if you are building an application, you can add a reference to the [latest version](https://www.nuget.org/packages/Microsoft.Windows.CsWinRT/1.0.2-prerelease.201103.7) of the CsWinRT prerelease package which also has the same fix.

**Comment by bgavrilMS** [comment]
Ok, so if I reference the latest CsWinRT in my library, then CsWinRT will re-generate C# projections right? 

Do you have an example of how to exactly specify the windows metadata? I tried with

```xml
<PropertyGroup>
    <TargetFramework>net5.0-windows10.0.17763.0</TargetFramework>
    <WindowsSDKVersion>10.0.17763.0</WindowsSDKVersion>
  </PropertyGroup>
```

and with

```xml
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.0.2-prerelease.201103.7" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.17763.1000" />
```

But both fail either at build time or at runtime with TypeLoadEx.

**Comment by bgavrilMS** [comment]
Just to update the thread with @manodasanW 's reply: 

` oh that error is because we had a breaking change at one point and the version of the .NET SDK you have is probably the preview or pre-GA one that didn't have the respective changes.  Can you update to the .NET 5 SDK GA build that released today and see if that works?`

Yes, with latest .net5 SDK (5.100 GA) regenerating the data works and the bug is no longer present.
