### ISSUE TITLE
Unable to use IInitializeWithWindow with .NET 5

### ISSUE THREAD

**Issue by mveril** [microsoft/CsWinRT#581]
# Unable to use IInitializeWithWindow with .NET 5

I have created a test C# WPF application to try the new [support of COM interface](https://blogs.windows.com/windowsdeveloper/2020/10/13/c-winrt-version-0-8-and-the-net5-rc2-release) like [IInitializeWithWindow](https://docs.microsoft.com/windows/win32/api/shobjidl_core/nn-shobjidl_core-iinitializewithwindow) in CSWinrt.
When I click the button to show a WinRT `MessageDialog` on .NET Core 3.1 everithing work fine but on .NET 5 I have a `System.InvalidCastException : 'Invalid cast from 'Windows.UI.Popups.MessageDialog' to 'WinRTTest.IInitializeWithWindow'.`
Here this is my code
```csharp
using System;
using System.Runtime.InteropServices;
using System.Windows;
using System.Windows.Interop;
using Windows.UI.Popups;

namespace WinRTTest
{

    [ComImport]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
    internal interface IInitializeWithWindow
    {
        void Initialize(IntPtr hwnd);
    }

    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            MessageDialog dialog = new MessageDialog("Hellow WinRT");
            IInitializeWithWindow withWindow = (IInitializeWithWindow)(object)dialog; // Throw System.InvalidCastException on .NET 5
            withWindow.Initialize(new WindowInteropHelper(this).Handle);
            await dialog.ShowAsync();
        }
    }
}
```
And my project file
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net5.0-windows10.0.19041.0</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Condition="'$(TargetFramework)' == 'netcoreapp3.1'"
                      Include="Microsoft.Windows.SDK.Contracts"
                      Version="10.0.19041.1" />
  </ItemGroup>
</Project>
```
So what's wrong ?
I Use:
- .NET SDK 5.0.100
- Visual Studio 16.8.0

**Comment by manodasanW** [comment]
@mveril For ComImport interfaces, C# style casts don't work for them.  Can you try changing that line to `((object)dialog).As<IInitializeWithWindow>()` and see if that works.  You probably need to also add a `using WinRT` at the top as it is an extension API from that namespace.

**Comment by mveril** [comment]
It's works very well Thank you so much (I notice that it also works with `dialog.As<IInitializeWithWindow>()` without converting explicitly `dialog` into `object`)

**Comment by smourier** [comment]
I've also has this issue (on other interfaces) and this means it's a lot of work to migrate from a .NET Core 3 or .NET Framework because:

1) it requires a change in the calling code, i.e. replace this:

    var win= (IInitializeWithWindow)(object)dialog; 

by this

    var win = ((object)dialog).As<IInitializeWithWindow>();

everywhere in an existing code!

2) the code is not backward compatible so we can't have the same source for existing .NET targets and .NET 5 and beyond, we'd have to use conditional if statements.

4) this new code now *requires* the interface definition to have the ComImport attribute while it was not the case before.

Are there any plans to evolve on this? This just adds to the big list of breaking (source) changes of .NET 5.
