### ISSUE TITLE
Understanding: simple Command line sample 

### ISSUE THREAD

**Issue by hannespreishuber** [microsoft/CsWinRT#583]
In general I am searching for samples

from my understanding a winRT api can be called from .NET 5. So started with command line and pasted some UWP clipboard code

  `  static void Main(string[] args)

        {

             var dp = new DataPackage();

            var html = HtmlFormatHelper.CreateHtmlFormat("test");

            dp.SetHtmlFormat(html);

            dp.SetText("Hallo Welt");

            Clipboard.SetContent(dp);

        }`
it compiles csporj

`<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>

    <OutputType>Exe</OutputType>

	  <TargetFramework>net5.0-windows10.0.17763.0</TargetFramework>

	  <CsWinRTWindowsMetadata>10.0.19041.0</CsWinRTWindowsMetadata>

  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.1.0-prerelease.201111.6" />

  </ItemGroup>

</Project>`

runs with exception
System.Runtime.InteropServices.COMException: "CoInitialize wurde nicht aufgerufen. (0x800401F0 (CO_E_NOTINITIALIZED))"

question is: what is missing?
and yes- I am lack of understanding.

**Comment by Scottj1s** [comment]
@hannespreishuber the easiest way to ensure that your Main thread has initialized COM is to add the STAThread attribute:

        [STAThread]
        static void Main(string[] args)
