### ISSUE TITLE
The UWP API Package.InstalledLocation.Path takes too much time on Windows 10.19041.572 and later

### ISSUE THREAD

**Issue by mingtong** [microsoft/CsWinRT#587]
OS version: 2004,
build number: 19041.572

When I call this API on one of the mentioned Windows 10, it takes about 4~5 seconds.
But it doesn't reproduce on my own Windows 10(same build same version).

Any one have ran into this issue?

**Comment by manodasanW** [comment]
@mingtong Can you confirm whether you are using this API in a .NET 5 application via or not?

**Comment by mingtong** [comment]
> @mingtong Can you confirm whether you are using this API in a .NET 5 application or not?

it happened to both .net 4.5 and .net 5

**Comment by AdamBraden** [comment]
@mingtong - please file an issue in Feedback Hub (win+F).
@DrusTheAxe - is there a known OS issue here?

**Comment by DrusTheAxe** [comment]
There's no known issue.

The .InstalledLocation call is probably the locus of the problem, as that creates a StorageFolder object which can get non-trivial depending. The .Path call is probably not where the perf issue occurs.

What package(s) show this perf?
What paths?
Are these on removable media? Network paths?
Anything else unusual or odd about their locations e.g. EFS? NTFS compressed directories?

I'm trying to think of common threads that might explain the perf delta.

@AdamBraden who's the primary contact(s) for StorageFolder?

**Comment by mingtong** [comment]
> There's no known issue.
> 
> 
> 
> The .InstalledLocation call is probably the locus of the problem, as that creates a StorageFolder object which can get non-trivial depending. The .Path call is probably not where the perf issue occurs.
> 
> 
> 
> What package(s) show this perf?
> 
> What paths?
> 
> Are these on removable media? Network paths?
> 
> Anything else unusual or odd about their locations e.g. EFS? NTFS compressed directories?
> 
> 
> 
> I'm trying to think of common threads that might explain the perf delta.
> 
> 
> 
> @AdamBraden who's the primary contact(s) for StorageFolder?

I forget to mention that all folders are uwp packages. I am trying to enumerate all the packages and find out only games.

**Comment by AdamBraden** [comment]
@mingtong - take a look at the following guidance. Storage apis are large objects and can be optimized:
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/optimize-file-access

If that isn't fast enough, try looking at the *FromApp() apis, eg: FindFirstFileExFromApp. 
https://github.com/microsoft/microsoft-ui-xaml/issues/1465#issuecomment-575987737
