### ISSUE TITLE
Can I use this to make calls to Shell32 / COM?

### ISSUE THREAD

**Issue by hansmbakker** [microsoft/CsWinRT#591]
I'd like to read extended file properties from Explorer on a Windows Server 2016/2019 system in a .NET 5.0 application.

I found this [StackOverflow answer about reading extended file properties from Explorer](https://stackoverflow.com/a/2096315/1114918) and saw that they do that via a Shell32 COM object.

Is that something that would be possible to use CsWinRT for?

**Comment by asklar** [comment]
those are a different set of APIs. The APIs you'd be able to access via cswinrt are the WinRT APIs like StorageFile, StorageFolder, etc. See e.g. https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.StorageFolder

**Comment by hansmbakker** [comment]
is there another way that one can make calls to the extended file properties from .NET5?

**Comment by asklar** [comment]
I think you should be able to do the same thing you could do in previous .net versions, i.e. use p/invoke to call the COM APIs of your choice.

**Comment by AdamBraden** [comment]
tagging as a feature - adding metadata support for win32 + COM apis, and putting on our future backlog.

**Comment by mikebattista** [comment]
@hansmbakker could you try https://github.com/microsoft/cswin32? That is our new Win32 and COM projection for .NET that will generate P/Invoke signatures for you and provide a friendlier developer experience.

Let us know how it goes and do file bugs if you run into any issues calling the APIs you want to call.

**Comment by AdamBraden** [comment]
closing as this is now handled by cswin32 as noted above
