### ISSUE TITLE
System.InvalidCastException on CollectionView enumeration

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/CsWinRT#592]
**Describe the bug**

I create CollectionViewSource and enumerate items in View.

```
CollectionViewSource source = new CollectionViewSource() { Source = new string[] { "str1", "str2", "str3" } };
            foreach(var item in source.View) {
            }
```
Code failed with "System.InvalidCastException: 'Specified cast is not valid.'" exception

![image](https://user-images.githubusercontent.com/23479280/95494068-fdf6dd00-09a5-11eb-8457-c8c7e90afff0.png)

Exception details:

```
System.InvalidCastException
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
```

Call stack:

```
 	winrt.runtime.dll!WinRT.ExceptionHelpers.ThrowExceptionForHR(int hr)
winrt.runtime.dll!ABI.System.Collections.Generic.IEnumerable<object>.Windows.Foundation.Collections.IIterable<object>.First()
 	winrt.runtime.dll!ABI.System.Collections.Generic.IEnumerable<object>.FromAbiHelper.GetEnumerator()
 	winrt.runtime.dll!ABI.System.Collections.Generic.IEnumerable<System.__Canon>.GetEnumerator()
 	winrt.runtime.dll!ABI.System.Collections.Generic.IList<System.__Canon>.FromAbiHelper.GetEnumerator()
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Data.ICollectionView.GetEnumerator()
	AttachedCollections.dll!AttachedCollections.MainWindow.MainWindow() Line 19	C#
```

**Version Info**

Windows 10 1903 (OS Build 18362.1082)

**NuGet package version:**

WinUI 3.0.0-preview2.200713.0

**Windows app type:**

| UWP              | Win32            |
| :--------------- | :--------------- |
|| Yes|

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by stevenbrix** [comment]
@angelazhangmsft this looks like a C#/WinRT issue that was missed for Preview3. Would you mind taking a look?

**Comment by angelazhangmsft** [comment]
I'm able to repro this error with WinUI Preview 3. I also tried updating the FrameworkReference as follows and it still repros with same exception in WinRT.Runtime

```xml
<ItemGroup>
        <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref"
                            RuntimeFrameworkVersion="10.0.18362.11-preview" />
        <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref"
                            TargetingPackVersion="10.0.18362.11-preview" />
</ItemGroup>
```

**Comment by stevenbrix** [comment]
Thanks for clarifying, is this something that can make the first .NET5 servicing release in December?
