### ISSUE TITLE
Support CloneStream in projected AsRandomAccessStream

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/CsWinRT#596]
I'm using .NET stream to set clipboard:
```csharp
            var dataPackage = new DataPackage();
            var stream = new MemoryStream(_data).AsRandomAccessStream();
            dataPackage.SetBitmap(RandomAccessStreamReference.CreateFromStream(stream));
            dataPackage.RequestedOperation = DataPackageOperation.Copy;
            Clipboard.SetContent(dataPackage);
```

It fails with `CopyStream not supported`. Looking into the decompilation, it is not implemented at all.

WinRT type `InMemoryRandomAccessStream` does support it, but it's less convenient.

**Comment by huoyaoyuan** [comment]
I noticed that it is intentionally:

https://github.com/microsoft/CsWinRT/blob/cca8f405d87f29d0e2b76f298daa8f8a0640047b/cswinrt/strings/additions/Windows.Storage.Streams/NetFxToWinRtStreamAdapter.cs#L414-L419

What I want is just `MemoryStream` support. In this case, should I implement a custom class simply?

**Comment by angelazhangmsft** [comment]
@huoyaoyuan - We copied this source from the CLR and we do not plan on implementing this, but you can implement your own custom class.
