### ISSUE TITLE
Access Windows.UI.Xaml.Data namespace

### ISSUE THREAD

**Issue by xperiandri** [microsoft/CsWinRT#602]
I try to build an F# library that targets .NET Standard 2.0 and .NET 5 UWP.
I need `Windows.UI.Xaml.Data`.
What is the minimum target version of UWP I can use and how to access `Windows.UI.Xaml.Data` namespace?

**Comment by AdamBraden** [comment]
@xperiandri - you can update the F# app to target net5 using the new TFM and gain access to the SDK and runtime support libraries. Additional Xaml components are found in the WinUI3 preview, so you need to add a nuget reference to that. eg:

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework> 
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview3.201113.0" />
  </ItemGroup>

This only works for .NET5, there is no support currently for .netstandard.

F# has not been our focus, but I think @AngelMunoz has done some investigations in this area.

Regarding UWP - supporting Net5 in a UWP/NetNative app is not in our plan, instead ProjectReunion is working on a plan to bring UWP/NetNative apps forward onto .NET5. So I would focus on WinUI3+ProjectReunion on Net5.

**Comment by AngelMunoz** [comment]
From my side, I just explored non UI parts of the WinRT API without any issues, anything else that is UI related requires a core window I believe. For my use cases that wouldn't work. Beyond that, I have not explored anything regarding F# + WinUI sadly I'm sorry I can't provide better output on that

**Comment by xperiandri** [comment]
Will netstandard be supported the same way as .NET 5?
