### ISSUE TITLE
`Windows.UI.Colors` is not projected in net5

### ISSUE THREAD

**Issue by ShadowDancer** [microsoft/CsWinRT#606]
Hi, I've created new console app, changed `TargetFramework` to `net5.0-windows10.0.17763` and `Windows.UI.Colors` is not projected.

My code:
```
        static void Main(string[] args)
        {
            var colors = Windows.UI.Colors.White;
        }
```

Some people mentioned that it's possible to `Microsoft.UI.Colors`, but `Windows.UI.Colors` is used in some WinRt apis, like Themes, and not all apps using it will use WinUI.

**Comment by cjj19970505** [comment]
Same problem here. 
My case is Windows.UI.Xaml.Controls.SwapChainPanel.
Is all Windows.UI namespace unsupported ?

**Comment by stevenbrix** [comment]
@ShadowDancer and @cjj19970505 all the `Windows.UI.Xaml.*` types are not currently projected. This includes related types, like `Windows.UI.Colors` as well. 

There are a few reasons we did this:
1. The `Windows.UI.Xaml.*` APIs are designed to work in UWP. UWP only supports .NET Native at the moment.
2. When using `Windows.UI.Xaml.*` types, you have the opposite issue with the .NET projections as we currently have with WinUI3 in .NET Native. See https://github.com/microsoft/microsoft-ui-xaml/issues/2978.
3. Avoid any confusion from having both `Microsoft.*` and `Windows.*` types.

As a workaround, you can use the projection generation support to create your own. Below is an example of how to do this:

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.1.0"/>
  <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />
</ItemGroup>

<PropertyGroup>
   <CSWinRTIncludes>
       Windows.UI.Colors;
       Windows.UI.Xaml;
       Windows.UI.Text;
   </CSWinRTIncludes>
   <CSWinRTExcludes>
        Windows.UI.Text.FontStretch
        Windows.UI.Text.FontStyle
        Windows.UI.Text.IFontWeight
        Windows.UI.Text.UnderlineType
        Windows.Foundation.Diagnostics
   </CSWinRTExcludes>
</PropertyGroup>
```

**Comment by stevenbrix** [comment]
It would also be helpful to know what your scenario is, and if there is anything we should re-think here. Your feedback is always appreciated 👍

**Comment by ShadowDancer** [comment]
@stevenbrix thanks a lot for help, this is really useful post especially considering fact that people just want to migrate their apps without digging too deep into guts of WinRT.

My use case:
I have app using Avalonia and WinRT apis (so no winui here). I want to detect system theme, so I am querying `Windows.UI.ViewManagement.UiSettings` `Background` and `Foreground` properties. On netcore I would compare them to `Colors.White` and `Colors.Black`, however these are not available after migration.

I was able to get around this by doing `Color.FromArgb`, just reported this bug for documentation issues and in case other people have such problems.

**Comment by cjj19970505** [comment]
@stevenbrix 

Thanks a lot. It's really helpful
My case is that I implemented a custom Windows.UI.Xaml.Controls.SwapChainPanel in C++/WinRT and used it in C# UWP programs. As .Net 5 and CS/WinRT 1.0 released, I try to create a C# projection wrapper for my C++/WinRT library but failed since Microsoft.UI.Xaml.Controls of WinUI2 doesn't have a SwapChainPanel. I found that WinUI 3 will have a SwapChainPanel built in but It's still in preview.

**Comment by AdamBraden** [comment]
@stevenbrix - do we need to reassess where Colors comes from?

**Comment by Scottj1s** [comment]
@ShadowDancer - per your suggestion, we've opened an internal issue to document the Windows.* types excluded in the .NET 5 Windows TFM projection support

**Comment by stevenbrix** [comment]
@AdamBraden, I'm not sure TBH - I would say this could be a point-in-time issue until Reunion is online, but I don't imagine an Avalonia app to ever need Reunion.

For `Windows.UI.Colors` the code needed to make the projection is much simpler:

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.1.0"/>
  <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />
</ItemGroup>

<PropertyGroup>
   <CSWinRTIncludes>
       Windows.UI.Colors;
   </CSWinRTIncludes>
</PropertyGroup>
```

@cjj19970505 are you trying to move your existing programs to Win32, or do you want to stay UWP?

**Comment by cjj19970505** [comment]
> @AdamBraden, I'm not sure TBH - I would say this could be a point-in-time issue until Reunion is online, but I don't imagine an Avalonia app to ever need Reunion.
> 
> For `Windows.UI.Colors` the code needed to make the projection is much simpler:
> 
> ```
> <ItemGroup>
>   <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.1.0"/>
>   <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />
> </ItemGroup>
> 
> <PropertyGroup>
>    <CSWinRTIncludes>
>        Windows.UI.Colors;
>    </CSWinRTIncludes>
> </PropertyGroup>
> ```
> 
> @cjj19970505 are you trying to move your existing programs to Win32, or do you want to stay UWP?

Win32

**Comment by angelazhangmsft** [comment]
#597 related to this issue (we do not support `Windows.UI.Xaml` projections)
