### ISSUE TITLE
Documenting Some Build Issues

### ISSUE THREAD

**Issue by jdasilva** [microsoft/CsWinRT#609]
First, thanks for having such a great build script!  I just wanted to document some issues I ran into trying to build.  I hope this will help smooth the path for others.  I wasn't able to solve the second issue, but I was able to get past it for what I needed.

1) Maybe I missed some documentation, but I had to add the Windows 10 SDK (10.0.19041) component to support `[NoExcept]` in the idl files.

2)  For some reason when trying to run the unit tests for netcoreapp2.0 it fails for me with this error:

```
Running cswinrt unit tests for x64 Release
Build started 11/28/2020 9:18:14 PM.
Test run for E:\ThirdParty\CsWinRT\unittest\bin\x64\Release\netcoreapp2.0\UnitTest.dll (.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 16.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
An exception occurred while invoking executor 'executor://xunit/VsTestRunner2/netcoreapp': Could not load file or assembly 'System.Runtime.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
Results File: E:\ThirdParty\CsWinRT\unittest_0.0.0-private.0.xml

Test Run Failed.
Additionally, path to test adapters can be specified using /TestAdapterPath command. Example  /TestAdapterPath:<pathToCustomAdapters>.
```

My goal was to verify the final .targets file for a PR so I was able to work around it by removing the `netcoreapp2.0` target framework.

**Comment by Scottj1s** [comment]
@jdasilva, you may need to install the .NET Core SDK 2.1.  This was recently deprecated and removed from the .NET 5 SDK, so it must now be explicitly installed.  The pipeline does this, but not the build script, and it hasn't been included as a prereq.

https://dotnet.microsoft.com/download/dotnet-core/2.1

**Comment by Scottj1s** [comment]
Added mention of the .NET Core SDK 2.1 prereq to the docs - feel free to reopen if that does not address

**Comment by jdasilva** [comment]
👍  I deleted a bunch of 2.0.x folders in `C:\Program Files\dotnet\shared\Microsoft.NETCore.App\` and that did work.
