### ISSUE TITLE
DirectX interop question

### ISSUE THREAD

**Issue by alexserov** [microsoft/CsWinRT#610]
According to your [COM Interop Guide](https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md), I see that the best practice is to use the new interop API (`IObjectReference`, `MarshalInspectable`, and so on) even if we need to access non-WinRT types.
>Generally, the RCW/CCW functions in Marshal should be avoided, as they are incompatible with the new ComWrappers support in .NET 5.

In our case, we work with both WinRT objects and non-WinRT (DirectX) COM objects, so we're interested in the common mechanism to marshal these COM types.

We tried to marshal DirectX objects using the `MarshalInspectable<T>` API as follows:
```csharp
int[] featureLevels = { (int)D3D_FEATURE_LEVEL.D3D_FEATURE_LEVEL_9_1 };

D3D11CreateDevice(
    IntPtr.Zero, 
    (uint)D3D_DRIVER_TYPE.D3D_DRIVER_TYPE_HARDWARE, 
    IntPtr.Zero, 
    (uint)D3D11_CREATE_DEVICE_FLAG.D3D11_CREATE_DEVICE_BGRA_SUPPORT, 
    featureLevels, 
    (uint)featureLevels.Length, 
    7, 
    out var device,  // we pass all of the COM objects as IntPtr to prevent the RCW creation by CLR mechanisms
    out var outFeatureLevel, 
    out var context);            

var d3dDevice = MarshalInterface<ID3D11Device>.FromAbi(device);
```

But we get an exception when calling the `MarshalInterface<T>.FromAbi(...);` method.

_You can find a sample with the exception in the [attachment (App4.zip)](https://github.com/microsoft/CsWinRT/files/5614914/App4.zip). Simply run it and click on the `Click Me` button._

---
So my question is: _What is the proper way to marshal non-WinRT COM objects?_

**Comment by Scottj1s** [comment]
@alexserov For marshaling a COM interop interface, you can continue to use the CLR's support:
            var d3dDevice = (ID3D11Device)Marshal.GetTypedObjectForIUnknown(device, typeof(ID3D11Device));

The methods mentioned in the COM Interop Guide are for WinRT interfaces.

**Comment by angelazhangmsft** [comment]
Closing the issue as it's been answered. Feel free to open a new issue if there is an issue with the proposed solution.
