### ISSUE TITLE
Project equivalent WinRT structs as .NET types

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/CsWinRT#611]
Project Windows.Foundation.Size as System.Drawing.Size, Windows.Foundation.Point as System.Drawing.Point and Windows.Foundation.Rect as System.Drawing.Rectangle.

Since this is a breaking change that can break existing, it could be provided as an optional feature and could be enabled by default in new projects.

**Comment by Jaiganeshkumaran** [comment]
Since WinRT types use floats instead of an integer, it can be projected with the F variants like PointF, SizeF, RectangleF

**Comment by Scottj1s** [comment]
@Jaiganeshkumaran, for some related history on these types, see:
https://github.com/microsoft/CsWinRT/issues/280
https://github.com/microsoft/microsoft-ui-xaml/issues/2047

How would you propose to implement this?  Note that the support for both modes would have to be compiled into the WinUI interop assembly at build time.  In C++, it's possible to type apply conversions in client code based on conditional compilation, etc.  We looked at doing something like this for C#, but could not find any technique to enable it (e.g., ConditionalAttribute).

**Comment by Scottj1s** [comment]
closing, as there isn't a clear technique to implement

**Comment by Jaiganeshkumaran** [comment]
> closing, as there isn't a clear technique to implement

Consider adding a constructor for the WinRT "graphics" types that takes in the System.Drawing types, and offer implicit conversion operators to convert the other way back.
