### ISSUE TITLE
0x8001010E (RPC_E_WRONG_THREAD) on Windows API call

### ISSUE THREAD

**Issue by aemarco** [microsoft/CsWinRT#612]
as recommended in https://github.com/dotnet/runtime/issues/45071#issuecomment-735587045 -->

### Description

Windows Api "SetImageStreamAsync" broke with upgrade to .net5
It now throws an Exception --> 0x8001010E (RPC_E_WRONG_THREAD) after porting from .netcore3.1 to net5.0.

### Reproduce the problem

[https://github.com/aemarco/LockScreenTest.git](url)
contains a sample project with nothing but the failing api call in App.xaml.cs.
It should be as easy as checking the repo out and run.

### Working condition (netcore3.1)

By changing back to .netCore 3.1 as below, the lockscreen will get successfully set 

`<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">`
`<TargetFramework>netcoreapp3.1</TargetFramework>`
`<PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />`

### Expectations

By specifying the TargetFramework with the windows version, api´s supposed to be functional. 

### Questions (done.... found concept reading stuff in https://github.com/dotnet/designs/tree/main/accepted/2020/minimum-os-version

Maybe you have a hint were to read up about that "define version number to access windows api" concept.
https://docs.microsoft.com/en-us/dotnet/standard/frameworks
explains that till the -windows, but not the part with the version number and api projections(which i learned through .netconf).

Should it not be possible to target "net5.0-windows", guard against specific api calls, dropping the "feature" when not on supported version, but call them if version >= needed ?

**Comment by AaronRobinsonMSFT** [comment]
@scottj1s @manodasanW I directed @aemarco to this repo since C#/WinRT should be handling thread affinity for WinRT scenarios. Please take a first pass at it and let me know if you feel it is actually an issue within the runtime.

**Comment by azchohfi** [comment]
Any updates on this. Its the only bug keeping all the WCT test suite from passing.

**Comment by manodasanW** [comment]
No updates yet, this is next on my list to start looking at again.

**Comment by mattleibow** [comment]
Just to note, I also saw this with `StorageFile`

**Comment by getrou** [comment]
I am also seeing this issue in Win2D's CanvasBitmap.LoadAsync() when running a Desktop Project Reunion app.

**Comment by manodasanW** [comment]
There is 2 unique issues tracked by this bug.  The first one is fixed in the mentioned PR which is managed objects should implement the free threaded marshaler allowing marshaling of them across apartments.  The second one is for non agile objects, we need to switch to the right context before the call.  That is still in progress.

**Comment by manodasanW** [comment]
The second issue causing the wrong thread error is still being worked on but is now tracked by https://github.com/microsoft/CsWinRT/issues/844

Resolving this issue as today is the deadline for 1.2.6 and the issue reported by the original filer is the first issue that I mention which is resolved in 1.2.6.
