### ISSUE TITLE
Interfaces missing FromAbi method

### ISSUE THREAD

**Issue by robmikh** [microsoft/CsWinRT#620]
I'm trying to port https://github.com/robmikh/wpfcapturesample to use .NET 5, and I'm running into an issue trying to use the `ICompositorInterop` interface. The file in question is [`CompositionHelper.cs`](https://github.com/robmikh/WPFCaptureSample/blob/master/Robmikh.WindowsRuntimeHelpers/CompositionHelper.cs).

I've changed the interop interface definition to be:
```csharp
[ComImport]
[Guid("25297D5C-3AD4-4C9C-B5CF-E36A38512330")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
interface ICompositorInterop
{
    void CreateCompositionSurfaceForHandle(
        IntPtr swapChain, out IntPtr/*ICompositionSurface*/ surface);

    void CreateCompositionSurfaceForSwapChain(
        IntPtr swapChain, out IntPtr/*ICompositionSurface*/ surface);

    void CreateGraphicsDevice(
        IntPtr renderingDevice, out IntPtr/*CompositionGraphicsDevice*/ device);
}
```

My problem is that I can't find a way to turn my `IntPtr` into a `ICompositionSurface` after calling CreateCompositionSurfaceForSwapChain. Runtime classes like `DesktopWindowTarget` or `CompositionGraphicsDevice` have a FromAbi method that is exactly what I need, but interfaces like `ICompositionSurface` seem to lack it. 

Is there an alternative way to get this working?

**Comment by Scottj1s** [comment]
Have you tried MarshalInterface<ICompositionSurface>.FromAbi(ptr) ?

See:
https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#Create-RCW

**Comment by robmikh** [comment]
That did the trick, thanks!
