### ISSUE TITLE
C#/WinRT doesn't properly incremental build

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#636]
If I change an .idl file in my C++ project, when I do an incremental build, the C#/WinRT projection isn't updated. This is the opposite problem of #519.

Repro project: [CS-Desktop2.zip](https://github.com/microsoft/CsWinRT/files/5680966/CS-Desktop2.zip)

Repro steps:

1. Do a full build
2. In the `RuntimeComponent1` project, change `Class.idl` to take a constructor which accepts an `Int32`:
   `Class(Int32 prop);`
3. Do an incremental build

**Expected results**
Build fails, since call sites in C# code is using the default constructor, which no longer exists

**Actual results**
Build succeeds

**Comment by Scottj1s** [comment]
Problem doesn't occur from command line (msbuild), so we likely need to add tlog entries for cswinrt.exe executions
