### ISSUE TITLE
Should CsWinRT throw COMException or .NET exceptions?

### ISSUE THREAD

**Issue by trympet** [microsoft/CsWinRT#642]
I have spent some time writing switch statements for various system error codes relating to the _Windows.Services.Store_ API.

I am wondering if I should submit a PR, or if this is outside of the scope of CsWinRT? I was not able to find any documentation for the error codes that are thrown by any of the _Windows.Services.Store_ methods on MSDN, so it's quite a pain to map these to .NET exceptions.

An example of this are the network related errors thrown by the `StoreContext.GetAppAndOptionalStorePackageUpdates`, where the exceptions thrown are generic COMExceptions instead of HttpRequestExceptions.

Any guidance or general information would be greatly appreciated.

**Comment by huoyaoyuan** [comment]
`Marshal.GetExceptionForHR` ?

**Comment by Scottj1s** [comment]
CsWinRT uses [Marshal.GetExceptionForHR](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getexceptionforhr) and [Marshal.ThrowExceptionForHR](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.throwexceptionforhr) for mapping HRESULTs to exceptions, so they're not likely to be of help here.  The CLR generally doesn't provide domain (API) specific HRESULT mappings, [as discussed here](https://docs.microsoft.com/en-us/dotnet/framework/interop/how-to-map-hresults-and-exceptions).  CsWinRT is the same - except for a few built-in XAML exceptions.  Note that many domain-specific .NET exceptions, like [HttpRequestException](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestexception?view=net-5.0), are not used by WinRT types, but by .NET types.  You can map generic COMExceptions to whatever you like, but CsWinRT would have no way of knowing your preference.

**Comment by jcotton42** [comment]
Getting COMExceptoin all over the place sounds like a pretty unpleasant development experience. Unless they also include some sort of error string that will also make debugging quite painful.
