### ISSUE TITLE
Invalid cast from 'WinRT.IInspectable' to 'IMemoryBufferByteAccess'

### ISSUE THREAD

**Issue by fgoulet** [microsoft/CsWinRT#646]
**Describe the bug**
An System.InvalidCastException occurs when trying to cast to the ComImport IMemoryBufferByteAccess from an IMemoryBufferReference.

**To Reproduce**
```
[ComImport]
[Guid("5B0D3235-4DBA-4D44-865E-8F1D0E4FD04D")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]

unsafe interface IMemoryBufferByteAccess
{
    void GetBuffer(out byte* buffer, out uint capacity);
}

AudioFrame frame = new Windows.Media.AudioFrame(1024);

using (AudioBuffer buffer = frame.LockBuffer(AudioBufferAccessMode.Write))
using (IMemoryBufferReference reference = buffer.CreateReference())
{

    try
    {
        var memoryBuffer = (IMemoryBufferByteAccess)reference;
    }
    catch (Exception ex)
    {
        //  Invalid cast from 'WinRT.IInspectable' to 'WinUIApp1.IMemoryBufferByteAccess'
    }

}

```

**Expected behavior**
The variable memoryBuffer should have been casted to IMemoryBufferByteAccess.

**Version Info**
CsWinRT: 10.0.19041.12 
.NET SDK: 5.0.0

**Additional context**
I'm trying to port the following [Windows Universal sample](https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/AudioCreation/cs/AudioCreation/Scenario3_FrameInputNode.xaml.cs) to CsWInRT.
Exception occurs on line 104.

**Comment by j0shuams** [comment]
Thanks for your issue. I believe the issue is with how you cast to your interface. Since it is a `[Com Import]`, you need to use the `.As<>()` method of casting. We have some documentation for [ComInterop](https://github.com/microsoft/CsWinRT/blob/master/docs/interop.md#com-interop) interfaces that covers this. 

I was able to repro, then made this change and the exception doesn't throw now. 

```csharp
    // var memoryBuffer = (IMemoryBufferByteAccess)reference;
    var memoryBuffer = reference.As<IMemoryBufferByteAccess>();
```

**Comment by fgoulet** [comment]
It works like a charm. Thank you.

**Comment by TishSerg** [comment]
> It works like a charm. Thank you.

Indeed. Worked for me too.
Why they didn't mention this problem in the docs/examples?
