### ISSUE TITLE
Hosting support - Allow loading .NET 5 from another location

### ISSUE THREAD

**Issue by manodasanW** [microsoft/CsWinRT#655]
Investigate ways to support loading the .NET 5 runtime from another location other than program files for hosted types.
- Look into settings environment variables (DOTNET_ROOT)
- Look into passing location to hostfxr_initialize_for_runtime_config

**Comment by Scottj1s** [comment]
DOTNET_ROOT is supported as the fallback when a null parameter is passed to get_hostxfr_path.  Unless usage scenarios cannot reasonably set an env var before loading a component, there's probably not a need to complicate the config schema to specifying a dotnet_root that way.

**Comment by Scottj1s** [comment]
Closing, as no work seems necessary here, beyond built-in DOTNET_ROOT support
