### ISSUE TITLE
Reduce need for CsWinRTWindowsMetadata

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#657]
Currently users need to explicitly set CsWinRTWindowsMetadata when using the CsWinRT nuget pacakge in VS. We could set this automatically, perhaps by detecting if TargetPlatformVersion is set and using that as a default for CsWinRTWindowsMetadata. There's currently nothing to validate the version set by a user.

**Comment by manodasanW** [comment]
Note this is to look at the WinMDs distributed as part of the ref pack based on TFM used.

**Comment by Scottj1s** [comment]
TargetPlatformVersion can be consulted as a default, if available (it often is not).  If so, it should take precedence over WindowsSDKVersion that currently provides the default.   Note that in any case, no validation is possible - developers should look at build errors to determine if the Windows metadata is incorrect, whether implicitly or explicitly supplied.
