### ISSUE TITLE
Structs are always projected, even when excluded

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#658]
**Describe the bug**
Structs are always projected in the .cs file, even when they aren't in the `CSWinRTIncludes` list (and even if explicitly in `CSWinRTExcludes`)

**To Reproduce**

1. Extract the below zip to c:\temp (recommend that exact location)
[cswinrt-repro.zip](https://github.com/microsoft/CsWinRT/files/5784708/cswinrt-repro.zip)

2. Point cswinrt.exe at the .rsp extracted from the .zip:
> cswinrt.exe @c:\temp\cswinrt-repro\cswinrt.rsp

**Expected behavior**
The generated `c:\temp\cswinrt-repro\generated\Microsoft.UI.Xaml.cs` file only contains the `PrivateApiContract` type.

**Actual behavior**
It contains types like `Microsoft.UI.Xaml.Thickness` and `Microsoft.UI.Xaml.CornerRadius`

**Version Info**
CSWinRT: 1.1.0

**Comment by Scottj1s** [comment]
This happens when namespace additions (custom projections, extension methods, etc) are pulled in by any projection of that namespace.  See also:
https://github.com/microsoft/CsWinRT/issues/426

**Comment by Scottj1s** [comment]
closing won't fix - known issue with trying to produce partial custom projections
