### ISSUE TITLE
Question: Why is there an msb3073 error?

### ISSUE THREAD

**Issue by Haceau-Zoac** [microsoft/CsWinRT#659]
I installed it in the build `Microsoft.Windows.CsWinRT` An `MSB3073` error occurred in the .Net5.0 project of nuget package: 

命令“C:\Users\Administrator\.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe @"**projpath**\obj\Debug\net5.0-windows\Generated Files\cswinrt.rsp"”已退出，代码为 -1073741511。

**Comment by manodasanW** [comment]
@Haceau-Zoac That seems to be a dependency missing error.  Do you get any error if you just run `C:\Users\Administrator.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe`.  Also what version of Windows are you running on?

**Comment by Haceau-Zoac** [comment]
> @Haceau-Zoac That seems to be a dependency missing error. Do you get any error if you just run `C:\Users\Administrator.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe`. Also what version of Windows are you running on?

I found out i don't have `C:\Users\Administrator.nuget` folder!

**Comment by Haceau-Zoac** [comment]
> > @Haceau-Zoac That seems to be a dependency missing error. Do you get any error if you just run `C:\Users\Administrator.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe`. Also what version of Windows are you running on?
> 
> I found out i don't have `C:\Users\Administrator.nuget` folder!

And my windows version is `windows7 service pack 1`

**Comment by Haceau-Zoac** [comment]
> > @Haceau-Zoac That seems to be a dependency missing error. Do you get any error if you just run `C:\Users\Administrator.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe`. Also what version of Windows are you running on?
> 
> I found out i don't have `C:\Users\Administrator.nuget` folder!

I remembered, I deleted the CsWinRT NuGet package, I went to install it.

**Comment by manodasanW** [comment]
@Haceau-Zoac Also one other thing to check is if C:\Users\Administrator\.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe exists and if so try manually running that.  Note the \ after Administrator as I expect .nuget to be a folder under it.

**Comment by Haceau-Zoac** [comment]
> @Haceau-Zoac Also one other thing to check is if C:\Users\Administrator.nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe exists and if so try manually running that. Note the \ after Administrator as I expect .nuget to be a folder under it.

I will check.
Thanks!

**Comment by Haceau-Zoac** [comment]
> @Haceau-Zoac Also one other thing to check is if C:\Users\Administrator\ .nuget\packages\microsoft.windows.cswinrt\1.1.0\cswinrt.exe exists and if so try manually running that. Note the \ after Administrator as I expect .nuget to be a folder under it.

I entered the command `.\cswinrt` in the `C:\Users\Administrator\.nuget\packages\microsoft.windows.cswinrt\1.1.0` folder using `PowerShell 7-preview`, and it has no output.
I entered the command `.\cswinrt "F:\**projpath**\obj\Debug\net5.0-windows\Generated Files\cswinrt.rsp"`, it has no output, too.
I also entered the command `.\cswinrt @"F:\**projpath**\obj\Debug\net5.0-windows\Generated Files\cswinrt.rsp"`, it outputs: ```text
ParserError:
Line |
   1  |  .\cswinrt @"F:\DOTNETYES\Toolbox\obj\Debug\net5.0-windows\Generated F …
       |              ~
       | No characters are allowed after a here-string header but before the end of the line.
```
I entered `cswinrt` using `cmd.exe`, He popped up a dialog box titled `cswinrt.exe - 无法找到入口` with the content: 
```text
无法定位程序输入点 CreateFile2 于动态链接库 KERNEL32.dll 上。
```
And I entered `cswinrt @"F:\**projpath**\obj\Debug\net5.0-windows\Generated Files\cswinrt.rsp"`, He popped up a dialog box, too.
I checked the `CreateFile2` document (https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfile2), and its `Minimum supported client` is `Windows 8 [desktop apps \| UWP apps]`, so should I use Windows 8 or later?

**Comment by manodasanW** [comment]
@Haceau-Zoac It does look like we had an indirect dependency on CreateFile2 which is not available on Windows 7.  We typically test on Window 10, but I did a quick run on Windows 8 and the CsWinRT tool does seem to run on it.  So I would suggest trying out Windows 8 or later.  Given this is the issue, I am going to go ahead and close the issue, but feel free to comment here or open a new issue if you still run into issues with Windows 8 or later.
