### ISSUE TITLE
Authoring with user control - diagnostics catching Xaml generated file

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#662]
**Describe the bug**
Authoring diagnostics catches that one of Xaml's generated files doesn't have the default overload attribute on their classes.  It used to be that as long as the attribute was set on the interface (which it is), it was implied the same attribute on class.

**To Reproduce**

1. Add empty User Control WinUI template to authoring component project
2. Build results in error: Severity    Code    Description    Project    File    Line    Source    Suppression State    Tool
Error    WME1085    In class XamlMetaDataProvider: The 1-parameter overloads of GetXamlType must have exactly one method specified as the default overload by decorating it with Windows.Foundation.Metadata.DefaultOverloadAttribute.    UserControlLibrary    C:\Users\angzhang\source\repos\WinUII3Desktopnternal\UserControlLibrary\obj\Debug\net5.0-windows10.0.18362.0\XamlTypeInfo.g.cs    46    Build        Csc

**Version Info**

1.1.1-prerelease.210111.5

**Comment by angelazhangmsft** [comment]
I'm still seeing this error with a blank User Control - should it be fixed in 1.1.2-prerelease?

Severity	Code	Description	Project	File	Line	Source	Suppression State	Tool
Error	CsWinRT1016	In class XamlMetaDataProvider: The 1-parameter overloads of GetXamlType must have exactly one method specified as the default overload by decorating it with Windows.Foundation.Metadata.DefaultOverloadAttribute	WinUIAuthoringSample	C:\repos\WinUIAuthoringSample\WinUIAuthoringSample\obj\x64\Debug\net5.0-windows10.0.18362.0\XamlTypeInfo.g.cs	46	Build		Csc

**Comment by manodasanW** [comment]
@angelazhangmsft it requires you a WinUI projection update with the CsWinRT 1.1.1. build.
