### ISSUE TITLE
WebView2 hangs on reading final 0 bytes via NetFxToWinRtStreamAdapter

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/CsWinRT#670]
Originally opened on WebView2:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/806

But may be related to the cswinrt adapter code.

Internal tracking: https://task.ms/31565319

**Comment by j0shuams** [comment]
This is not a C#/WinRT issue exactly -- discussion is still going on offline about how to proceed. Seems the most appropriate fix is on the OS side of things.

**Comment by j0shuams** [comment]
Removing blocking label as we have a workaround for this:

```csharp
var stream = new InMemoryRandomAccessStream();
await stream.WriteAsync(Encoding.UTF8.GetBytes($"<html><body><div>Hello, WebView2!</div></body></html>").AsBuffer());

```

**Comment by Eilon** [comment]
Do we have any update on this? Right now the workaround is to copy all the stream content to a new stream, which is not a great solution due to performance problems.

**Comment by manodasanW** [comment]
I hope to spend some time looking at this soon.  Need to investigate whether we can remove our synchronization part of the task code if our delegates are already agile.

**Comment by mqudsi** [comment]
FYI This only happens with CsWinRt, when the same code is executed in a UAP environment it does not hang. ###

**Comment by mqudsi** [comment]
@j0shuams can you explain on a technical level why `InMemoryRandomAccessStream()` works here? I saw your comment a couple of weeks ago and figured "oh, I can just use `new MemoryStream()`, copy to it, then invoke `AsRandomAccessStream()` and spent hours trying to get it to work before trying to use a WinRT native `new InMemoryRandomAccessStream()` instead, which worked immediately (as a workaround).

The documentation on WebView2's threading model states that any streams passed to `CreateWebResourceResponse()` must be created on a background STA thread, but that doesn't help, e.g. this still hangs:

```csharp
webView.CoreWebView2.WebResourceRequested += async (s, e) =>
{
    using var deferral = e.GetDeferral();

    var url = e.Request.Uri;
    var id = url.Replace("http://attachments/", "").Replace('/', '\\');
    id = WebUtility.UrlDecode(path);
    var path = TranslateAttachmentIdToPath(id);

    if (attachment is null)
    {
        e.Response = webHistory.CoreWebView2.Environment.CreateWebResourceResponse(null, 404, "Not found", "");
        return;
    }

    TaskCompletionSource<IRandomAccessStream> completion = new ();
    var t = new Thread(() =>
    {
        var stream = File.Open(path).AsRandomAccessStream();
        completion.SetResult(stream);
    });
    t.IsBackground = true;
    t.SetApartmentState(ApartmentState.STA);
    t.Start();

    var stream = await completion.Task;

    e.Response = webView.CoreWebView2.Environment.CreateWebResourceResponse(stream, 200, "Found", "");
    deferral.Complete();
}
```

It seems that the `IRandomAccessStream` passed to `CreateWebResourceResponse` must be a native WinRT random access stream and not anything else converted to an `IRandomAccessStream` via `.AsRandomAccessStream()` or else the COM threads will lock up.

Can you or @angelazhangmsft confirm whether this is the same issue that is being tracked internally, or if I should open this as a separate bug either in the CsWinRT repo or the WebView2Feedback repo?

**Comment by mqudsi** [comment]
@j0shuams @angelahazhangmsft 

> Can you or @angelazhangmsft confirm whether this is the same issue that is being tracked internally, or if I should open this as a separate bug either in the CsWinRT repo or the WebView2Feedback repo (where a similar but not identical bug was closed after saying it was being tracked here)?

**Comment by angelazhangmsft** [comment]
@mqudsi - yes, this is being tracked internally (added internal link to the issue above). The issue you mentioned above is the same issue being tracked here.

**Comment by mqudsi** [comment]
Thanks, @angelazhangmsft
