### ISSUE TITLE
Write new docs for WRC diagnostics

### ISSUE THREAD

**Issue by j0shuams** [microsoft/CsWinRT#677]
Since our diagnostics do what Winmdexp used to do, we should make a new version of this [webpage](https://docs.microsoft.com/en-us/previous-versions/hh977010%28v=vs.110%29)

**Comment by j0shuams** [comment]
There is a link used in WinRTRules.cs that needs to be updated when we get our new webpage

**Comment by j0shuams** [comment]
I'll be updating this [branch](https://github.com/MicrosoftDocs/windows-uwp-pr/tree/jlarkin/update-diagnostic-docs) and will cut a pr into @angelazhangmsft 's branch when I've made all my changes

**Comment by angelazhangmsft** [comment]
Authoring diagnostics docs have been published here - https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/authoring-diagnostics
