### ISSUE TITLE
How do I reference preview api functionality in the Windows.UI.Core.Preview.Communications namespace?

### ISSUE THREAD

**Issue by v-tbert** [microsoft/CsWinRT#681]
TFM net5.0-windows10.0.19041.0 does not appear to include projections for this preview api, though I can see the winmd file in my local filesystem at:

c:\Program Files\Windows Kits\10\References\10.0.19041.0\Windows.UI.Core.Preview.Communications.PreviewCommunicationsContract\1.0.0.0\Windows.UI.Core.Preview.Communications.PreviewCommunicationsContract.winmd 

If I add a reference to it manually and compile I get an error saying that referencing winmd directly is not supported in .net 5.0 and to use cswinrt. 

If I add the Microsoft.Windows.CsWinRT nuget package, the error changes to "Windows Metadata not provided or detected".  In trying to understand the various msbuild properties I got a bit further by add these to my csproj:

```
	<PropertyGroup>
		<CsWinRTFilters>
			-include Windows.UI.Core.Preview.Communications.PreviewTeamDeviceCredentials
		</CsWinRTFilters>
	</PropertyGroup>
	
	<ItemGroup>
		<CsWinRTInputs Include="..\..\..\..\..\Program Files\Windows Kits\10\References\10.0.19041.0\Windows.UI.Core.Preview.Communications.PreviewCommunicationsContract\1.0.0.0\Windows.UI.Core.Preview.Communications.PreviewCommunicationsContract.winmd" />
	</ItemGroup>  
```
Unfortunately it now fails saying it can't find Windows.Foundation.Metadata.MarshalingType. 

So what is the proper way to be able to reference the preview api?

**Comment by manodasanW** [comment]
@v-tbert It does look like the extension SDK which this API is part of is not one we are currently projecting.  You can indeed project it yourself by doing the following:

1.  Add a package reference to Microsoft.Windows.CsWinRT
2. Set CsWinRTWindowsMetadata to your SDK version as seen below.
3. Set CsWinRTFilters to include namespaces / types which you want to project similar to what you did, but it needs to be a complete set including any dependent types / namespaces that are not already projected.
4. Set CsWinRTInputs to include the WinMD similar to what you did

I believe step 2 and and step 3 should resolve your issues.

```xml
    <PropertyGroup>
      <CsWinRTWindowsMetadata>10.0.19041.0</CsWinRTWindowsMetadata>
      <CsWinRTFilters>
-include Windows.UI.Core.Preview.Communications
      </CsWinRTFilters>
  </PropertyGroup>

  <ItemGroup>
    <CsWinRTInputs Include="C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0\Windows.UI.Core.Preview.Communications.PreviewCommunicationsContract\1.0.0.0\Windows.UI.Core.Preview.Communications.PreviewCommunicationsContract.winmd" />
  </ItemGroup>
```

**Comment by v-tbert** [comment]
That certainly got me closer as it will compile now. Unfortunately, it won't run because its looking for a dll of the same name as the winmd to load. It is very similar to the issue described here, but mine is all c# .net 5: https://github.com/microsoft/CsWinRT/issues/647

**Comment by v-tbert** [comment]
In trying to put together a minimal repro, I stumbled on the ABI prefix in the namespace.

This gives an exception when instantiating PreviewTeamDeviceCredentials:
`using Windows.UI.Core.Preview.Communications;`

This works though: 
`using ABI.Windows.UI.Core.Preview.Communications;`

Is that the way its expected to work?

**Comment by Scottj1s** [comment]
@v-tbert - no, the ABI namespace is not intended for end developer use (it must be public to permit use across projection assemblies).  The ABI namespace classes are simply wrappers around static marshaling helper methods for each public projected class, such as PreviewTeamDeviceCredentials.  Instantiating them does nothing. so your activation problem remains. 

The activation error suggests you need an explicit activatableClass manifest entry, which in turn requires a Windows Application Packaging project wrapping your console app (we're working to remove the packaging project requirement).

**Comment by manodasanW** [comment]
@v-tbert I would also make sure you are running the app using this API on a platform which supports this API as I don't believe this API is supported everywhere.

**Comment by v-tbert** [comment]
@manodasanW, too right, thanks for the reminder! 

For some reason I had been expecting a PlatformNotSupportedException if I ran it on a sku of Windows that didn't support the contract.  So when I got the  COMException I had just assumed I was doing the msbuild stuff wrong. When I ran the updated code on the appropriate target skut it worked without doing the packaging stuff that @Scottj1s mentioned.
