### ISSUE TITLE
Random exceptions when calling BitmapSource.SetSourceAsync

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/CsWinRT#682]
**Describe the bug**
From https://github.com/microsoft/microsoft-ui-xaml/issues/3857

Scenarios:

Call async `SetSourceAsync` with .NET class implementing `IRandomAccessStream`:
Random native `Cannot access disposed object` exception.

Call sync `SetSource` with .NET class implementing `IRandomAccessStream`:
Deadlock. Not investigated yet.

Call sync `SetSource` with WinRT `InMemoryRandomAccessStream`:
Success. But some images doesn't show randomly.

Call async `SetSourceAsync` with WinRT `InMemoryRandomAccessStream`, drop without await:
Success. But some images doesn't show randomly.

Call async `SetSourceAsync` with WinRT `InMemoryRandomAccessStream`, and await:
Random COMException 0x88982F50 (Can't find component)

**Version Info**
Present with bits built from latest master.

**Comment by j0shuams** [comment]
@huoyaoyuan Can you provide a repro project? I read the issue you linked and am trying to write a small repro, but am slow figuring out how to set up GetImageAsync in order to get a stream from whatever it returns.

**Comment by j0shuams** [comment]
Have you tried moving this line 

`var entry = await _imageCache.GetImageAsync(request, refreshMemoryCache).ConfigureAwait(true);`

into a `using (...)` statement? That might be why the object is disposed of

**Comment by huoyaoyuan** [comment]
I've refactored the the reproduction a bit. In that case, the code is effectively:

```csharp
using (var stream = new MemoryStream(entry.dataBytes))
{
    await imageSource.SetSourceAsync(stream.AsRandomAccessStream());
}
```

C# code shouldn't dispose the stream before `await`.

There is also random exception when using async version with WinRT stream. I suspect there's some issue with `await` here.

**Comment by manodasanW** [comment]
Was able to get a potential repro by doing the repro in a loop:

```
	WinRT.Runtime.dll!WinRT.IObjectReference.ThrowIfDisposed() Line 126	C#
 	WinRT.Runtime.dll!WinRT.IObjectReference.ThisPtr.get() Line 26	C#
 	WinRT.Runtime.dll!ABI.WinRT.Interop.IAgileReference.WinRT.Interop.IAgileReference.Resolve(System.Guid riid) Line 97	C#
 	WinRT.Runtime.dll!WinRT.AgileReference.Get() Line 47	C#
 	Microsoft.Windows.SDK.NET.dll!ABI.Windows.Foundation.AsyncOperationWithProgressCompletedHandler<Windows.Storage.Streams.IBuffer, uint>.NativeDelegateWrapper.Invoke(Windows.Foundation.IAsyncOperationWithProgress<Windows.Storage.Streams.IBuffer, uint> asyncInfo, Windows.Foundation.AsyncStatus asyncStatus) Line 1593	C#
 	Microsoft.Windows.SDK.NET.dll!System.Threading.Tasks.TaskToAsyncOperationWithProgressAdapter<System.__Canon, uint>.OnCompleted(Windows.Foundation.AsyncOperationWithProgressCompletedHandler<System.__Canon, uint> userCompletionHandler, Windows.Foundation.AsyncStatus asyncStatus) Line 7878	C#
 	Microsoft.Windows.SDK.NET.dll!System.Threading.Tasks.TaskToAsyncInfoAdapter<Windows.Foundation.AsyncOperationWithProgressCompletedHandler<Windows.Storage.Streams.IBuffer, uint>, Windows.Foundation.AsyncOperationProgressHandler<Windows.Storage.Streams.IBuffer, uint>, Windows.Storage.Streams.IBuffer, uint>.OnCompletedInvoker(Windows.Foundation.AsyncStatus status) Line 7187	C#
 	Microsoft.Windows.SDK.NET.dll!System.Threading.Tasks.TaskToAsyncInfoAdapter<Windows.Foundation.AsyncOperationWithProgressCompletedHandler<Windows.Storage.Streams.IBuffer, uint>, Windows.Foundation.AsyncOperationProgressHandler<Windows.Storage.Streams.IBuffer, uint>, Windows.Storage.Streams.IBuffer, uint>.TaskCompleted.AnonymousMethod__62_0(object tupleObject) Line 7410	C#
```

**Comment by manodasanW** [comment]
The issue looks to be the delegate was brought back, but the agile reference stored in the delegate wasn't and causes the ObjectDisposedException.
