### ISSUE TITLE
Warning when turning of CsWinRTEnableLogging

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#687]
**Describe the bug**
If I don't set `CsWinRTEnableLogging` to true in an authoring project, I get the following warning and the winmd isn't generated.

Severity	Code	Description	Project	File	Line	Source	Suppression State	Tool
Warning	CS8785	Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ObjectDisposedException' with message 'Cannot write to a closed TextWriter.'	AuthoringDemo	C:\Users\angzhang\source\repos\AuthoringDemo\AuthoringDemo\CSC	1	Build	Active	Compiler

**Expected behavior**
no warning

**Version Info**
CsWinRT 1.1.1

**Comment by manodasanW** [comment]
Not able to reliably repro.  Monitoring for hits.

**Comment by manodasanW** [comment]
Managed to get a repro, issue occurs when logging is enabled and then disabled in same session or across projects using CsWinRT authoring at the same time.
