### ISSUE TITLE
cswinrt.sln doesn't build

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#692]
Is the SLN file up to date? Looks like there are several problems, e.g. it references a BenchmarkComponent.vcxproj that doesn't exist

The WinUIDesktopSample has build errors too:
```
---------------------------
Microsoft Visual Studio
---------------------------
The debug executable 'C:\Users\asklar\source\repos\cswinrt\src\Samples\WinUIDesktopSample\bin\x86\Debug\net5.0-windows10.0.19041.0\WinUIDesktopSample.exe' specified in the 'WinUIDesktopSample' debug profile does not exist.
---------------------------
OK   
---------------------------
```

Could someone add some details in the CONTRIBUTING.md file as to how one can build this project including tests and samples? Is this supposed to be built for `any cpu` or `x86`, etc.?

**Comment by huoyaoyuan** [comment]
You need to initialize submodules with some script. I forget the script name.

`build.cmd` should be updated to invoke the script.

**Comment by j0shuams** [comment]
Just running `build` does a debug|x64 build IIRC. I agree it would be good if we had a bit more explaining how the script works, such as explaining the [optional parameters](https://github.com/microsoft/CsWinRT/blob/e33691ea5f4bac9baaaaa3be969ebab4772cc90d/src/build.cmd#L37-L43)
