### ISSUE TITLE
WinMD's implementation should be set as WinRT.Host

### ISSUE THREAD

**Issue by manodasanW** [microsoft/CsWinRT#696]
The automatic support should set the implementation as WinRT.Host to allow the correct manifest entries be generated by tooling.

https://github.com/microsoft/CsWinRT/blob/e33691ea5f4bac9baaaaa3be969ebab4772cc90d/nuget/Microsoft.Windows.CsWinRT.Authoring.targets#L22

https://github.com/microsoft/CsWinRT/blob/e33691ea5f4bac9baaaaa3be969ebab4772cc90d/src/Tests/AuthoringWinUITest/AuthoringWinUITest/AuthoringWinUITest.vcxproj#L145

**Comment by asklar** [comment]
confirmed that manually patching the cswinrt target with that property and rebuilding the package makes it possible to load the managed dll and instantiate the managed object
