### ISSUE TITLE
Working with WinUI 3 preview 3

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#698]
Related to #693, #697

- Created a C# NET 5 class library. Reference the WinUI 3 Preview 4 CI 1/26 nuget package.
- Follow the authoring instructions to produce a nuget pkg for the class library
- Created a cppwinrt WinUI 3 app from WinUI 3 Preview 3 VSIX
- update cppwinrt app's WinUI reference to latest internal WinUI nuget preview 4 from 01/26
- Referenced the NET 5 class library nupkg file from the cppwinrt app via a local nuget source
- Build solution

After applying both workarounds:
The WAP project that the WinUI 3 vsix creates does not do anything (fails to deploy complaining about a missing appxrecipe file).

Using an internal prerelease Preview 4 VSIX **makes the WAP project build** so I'm just filing this to track the fact that cswinrt doesn't play well with WinUI 3 preview 3, but will likely work better against Preview 4 when it's out.

**Comment by AdamBraden** [comment]
@angelazhangmsft - please include in relnotes

**Comment by angelazhangmsft** [comment]
Closing as the bugs mentioned were fixed. Documentation of authoring/WinUI 3 integration captured in #694
