### ISSUE TITLE
ActivationFactory's constructor does an unconditional replace of "WinRT" with "Windows" for the class name

### ISSUE THREAD

**Issue by dunhor** [microsoft/CsWinRT#7]
The constructor contains the line:
```c#
using (HString runtimeClassId = new HString(typeof(T).FullName.Replace("WinRT", "Windows")))
```
Which doesn't seem correct. First, I'm not entirely sure why this is present anyway? From the way that it's written, it seems like there are scenarios where the leading namespace of "Windows" is replaced with "WinRT", but I can't seem to find any evidence of this being done. The namespace used in WinRT.cs is `WinRT`, but AFAICT none of these types are activatable. But anyway, i'd expect that _at best_ this should only occur if (1) the full name _starts with_ "WinRT" and (2) has a trailing dot (i.e. starts with "WinRT.").

**Comment by AdamBraden** [comment]
fwiw - I got bit by this because I created a component called SimpleMathCppWinRT.SimpleMath for a demo

**Comment by jkoritzinsky** [comment]
I think this can be removed since working side by side with winmds is not a supported scenario

**Comment by AdamBraden** [comment]
Remove this code.
