### ISSUE TITLE
Debugging across C++ to C# calls

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#701]
Related to #693, #697, #698, #699, #700 / #696

- Created a C# NET 5 class library. Reference the WinUI 3 Preview 4 CI 1/26 nuget package.
- Follow the authoring instructions to produce a nuget pkg for the class library
- Created a cppwinrt WinUI 3 app from WinUI 3 Preview 3 VSIX
- update cppwinrt app's WinUI reference to latest internal WinUI nuget preview 4 from 01/26
- Referenced the NET 5 class library nupkg file from the cppwinrt app via a local nuget source
- Build solution (work around the other bugs :) )
- Try to set a breakpoint in managed code - VS says the bp won't be hit because you don't have symbols
- Try to give VS the pdb for the managed DLL, VS complains that it doesn't match

![image](https://user-images.githubusercontent.com/22989529/106073460-f5462600-60be-11eb-8145-ad4dc896cc7a.png)

**Comment by asklar** [comment]
it looks like VS is getting confused - there are two entries for the DLL, one of which has symbols resolved, and stepping into managed code works ok:
![image](https://user-images.githubusercontent.com/22989529/106074503-d6489380-60c0-11eb-9ded-580b3b112b32.png)

**Comment by asklar** [comment]
only the 3rd bp is getting hit here:
![image](https://user-images.githubusercontent.com/22989529/106074735-3d664800-60c1-11eb-902f-cf1f47fba59b.png)

**Comment by Scottj1s** [comment]
@asklar, this looks like a VS issue - can you enter it there?

https://docs.microsoft.com/en-us/visualstudio/ide/feedback-options
