### ISSUE TITLE
Windows Runtime does not work with .NET 5

### ISSUE THREAD

**Issue by ClosetBugSlayer** [microsoft/CsWinRT#702]
I wanted to convert my fairly simple .NET Core 3.1 WPF solution to .NET 5 but it's impossible. All the problems you see below, I ran into with a small standalone .EXE project as well. I have Visual Studio 16.8.4 with .NET 5 Runtime installed on Windows 10 Pro 20H2. This is my simplified root library project file (I don't know why line breaks aren't showing up, I don't have time for this):

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <RootNamespace>etc</RootNamespace>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
  </PropertyGroup>  
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2020.3.0" />
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.1.1" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.31" />
    <PackageReference Include="System.Management" Version="5.0.0" />
    <PackageReference Include="System.Runtime.WindowsRuntime" Version="4.7.0" />
  </ItemGroup>
</Project>
```

For the root project above, I get all 4 of these errors together at the same time when trying to await on a WinRT method that returns IAsyncOperation<SpeechSynthesisStream>:

**[...]SpeechSynthesizer.cs(188,46,188,115): error CS0012: The type 'IAsyncAction' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.
[...]SpeechSynthesizer.cs(188,46,188,115): error CS0012: The type 'IAsyncActionWithProgress<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.
[...]SpeechSynthesizer.cs(188,46,188,115): error CS0012: The type 'IAsyncOperation<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.
[...]SpeechSynthesizer.cs(188,46,188,115): error CS0012: The type 'IAsyncOperationWithProgress<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.**

Why is it not finding the interfaces, and why is it telling me to reference a .NET Framework assembly which no longer exists?

Then for every single project that references the root project (none of which use WinRT), I unconditionally get this error even when I comment out everything but the CsWinRT and Contracts packages:

**C:\Program Files\dotnet\sdk\5.0.102\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(934,5): error NETSDK1130: Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.**

I am unable to add this line to the root project...
`<PackageReference Include="Microsoft.Windows.SDK.NET.Ref" Version="10.0.19041.13" />`
...because I then get this error:

**Package 'Microsoft.Windows.SDK.NET.Ref 10.0.19041.13' has a package type 'DotnetPlatform' that is not supported by project '[...]'.**				

Strange, is that an old error?  I thought the nuget description said "The Windows SDK available as a targeting pack for .NET 5 applications." and the package was updated 7 days ago so it can't be obsolete.

Lastly, setting the root SDK to "Microsoft.NET.Sdk.WindowsDesktop" does not work.

According to these rules below, I have done my due diligence:

    https://github.com/microsoft/CsWinRT/blob/master/nuget/readme.md
    Windows Metadata is required for all C#/WinRT projections, and can be supplied by:
    -A package reference, such as to Microsoft.Windows.SDK.Contracts
    -An explicit value, supplied by $(CsWinRTWindowsMetadata)
    -The default value, assigned from $(WindowsSDKVersion)
    If a Windows SDK is installed, $(WindowsSDKVersion) is defined when building from a VS command prompt.    
    
    https://github.com/microsoft/cswinrt/blob/master/README.md
    Application developers on .NET5+ can reference C#/WinRT interop assemblies by adding a reference to the
    interop NuGet package. This replaces any *.winmd references. The .NET5+ application includes
    WinRT.Runtime.dll which handles WinRT type activation logic.

Nope and nope, they don't work. I have ported a ton of .NET projects since Windows 8 was released, and getting WinRT to work with .NET was always impossible for the first week, it doesn't matter what version of .NET I'm going from or to. The online instructions are 100% always wrong, never reproduceable, and there's always some random set of circumstances I have to stumble into to make it work. This is developer trauma to the point that I don't want anything to do with WinRT ever again, but for now I have to make this work.

**Comment by manodasanW** [comment]
@ClosetBugSlayer From what I understand, you have a WPF app that makes use of WinRT APIs from the Windows SDK.  Is my understanding correct?

If so, all you need to do is use the net5.0-windows10.0.xxx.0 TFM as you are already doing and you would get an **implicit** reference to the Microsoft.Windows.SDK.NET.Ref framework package for the respective SDK version via the .NET SDK.  This package contains the Windows SDK projection generated using CsWinRT allowing for you in your WPF app to make use of those APIs.  So if you were to remove the reference to the CsWinRT package, the SDK contracts page,  and the System.Runtime.WindowsRuntime package, you should be able to get it to build your project.  You only need a reference to the CsWinRT package and the SDK contracts package if you were looking to build your own projection for a WinRT component from its WinMD file.

Let me know if you still run into issues.

**Comment by ClosetBugSlayer** [comment]
> Let me know if you still run into issues.

I'm in shock. You fixed everything.

**Comment by mqudsi** [comment]
@manodasanW Is it intended for transitive dependencies on `System.Runtime.WindowsRuntime` to also induce this problem?
