### ISSUE TITLE
DateTimeOffset marshaling doesn't support negative FileTime

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/CsWinRT#703]
**Describe the bug**
https://github.com/microsoft/microsoft-ui-xaml/issues/3889
https://github.com/dotnet/runtime/issues/47523#issuecomment-768808987

Currently `DateTimeOffset` marshaling is using `ToFileTime`, which doesn't support negative value, while WinRT time supports.

**Comment by Scottj1s** [comment]
Repro should be evaluated with UWP (.NET Core) to determine whether this is a regression

**Comment by huoyaoyuan** [comment]
https://github.com/dotnet/runtime/blob/27dcce57c7fc4cfa6634f3f064edaa92f2f6eb83/src/coreclr/src/System.Private.CoreLib/src/System/StubHelpers.cs#L548-L575

The deleted .NET Core 3.1 marshaler did support it.

**Comment by angelazhangmsft** [comment]
From the above link: https://github.com/microsoft/microsoft-ui-xaml/issues/3889
Confirmed was able to set date between 1/1/0001 and 31/12/1600 range in a UWP app, but get a ArgumentOutOfRangeException in a WinUI desktop app with this code:
```csharp
new DateTimeOffset(1500, 1, 1, 0, 0, 0, new TimeSpan(0));
```
