### ISSUE TITLE
WME1044 for valid assembly name

### ISSUE THREAD

**Issue by j0shuams** [microsoft/CsWinRT#705]
**Describe the bug**
For assembly names that are specified with a period -- e.g. `MyComponent.Foo` the winmd is named `MyComponent.winmd` instead of `MyComponent.Foo.winmd`. 

**To Reproduce**

1. Change the AuthoringDemo to have assembly and default namespace "AuthoringDemo.Foo"
2. Build
3. inspect winmd filename 

**Expected behavior**

The winmd should be named "AuthoringDemo.Foo.winmd"

**Initial Comments**
This is either a bug in GetAssemblyName in WinRT.SourceGenerator\Generators.cs or a bug in how we verify assembly names with namespaces in WinRT.SourceGenerator\DiagnosticHelpers.cs

**Comment by andrewleader** [comment]
Ah... Windows Community Toolkit Notifications library is blocked on this, looking forward to the 1.1.2 release!

**Comment by manodasanW** [comment]
@andrewleader we just had a prerelease build go out today with authoring bug fixes including for this one if you want to use that to get unblocked.

**Comment by andrewleader** [comment]
Awesome thanks Manodasan 😊 I still haven't had a chance to try the prerelease builds out and possibly won't get to try it this week, but when I do, I'll be sure to update you and your team if I find any other issues or if it goes well! Thanks!
