### ISSUE TITLE
Authoring component with SDK types raises CA1416 warnings

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#729]
**Describe the bug**

By setting `CsWinRTComponent` to true, I'm getting a bunch or warnings like the following. They disappear when commenting out `CsWinRTComponent`.

Severity	Code	Description	Project	File	Line	Source	Suppression State	Tool
Warning	CA1416	This call site is reachable on: 'Windows' all versions. 'ContentControl.Content.set' is only supported on: 'Windows' 10.0.17134.0 and later.	WinUIAuthoringSample	C:\repos\WinUIAuthoringSample\WinUIAuthoringSample\CustomButton.cs	27	IntelliSense	Active	Microsoft.CodeAnalysis.NetAnalyzers

**To Reproduce**

1. Author C#/WinRT component with Windows SDK types (for example FolderEnumeration class in the AuthoringDemo sample)
2. Build

Warnings may be coming from the roslyn source generator. It's possible that the roslyn source generator needs to be fed the SupportedOSPlatform props from the component project.

![image](https://user-images.githubusercontent.com/69016571/108789062-49adbb80-752e-11eb-9957-4e16e4d900cb.png)

**Expected behavior**

No warnings

**Version Info**

1.1.2-prerelease.210205.6
5.0.200-preview.21078.11 [C:\Program Files\dotnet\sdk]

**Comment by azchohfi** [comment]
I believe this is not an issue anymore, due to this? https://github.com/microsoft/CsWinRT/commit/9359ad7a32985831b2483cc5fbc35ac66240c3f7

**Comment by angelazhangmsft** [comment]
Yes, it looks like the warnings don't repro anymore with 1.2.6.
