### ISSUE TITLE
cswinrt doesn't support targeting .net6 

### ISSUE THREAD

**Issue by stevenbrix** [microsoft/CsWinRT#730]
If you update a .NET5 projection project to target .NET6, you won't get any generated files in the project. The `CSWinRTGenerateProjection` succeeds, which makes it seem like it does work, but any downstream dependencies on the projection being generated will fail. 

On top of supporting .net6 TFMs, the `CSWinRTGenerateProjection` should be updated to fail when cswinrt.exe fails.

**Comment by angelazhangmsft** [comment]
Tested with this [repro project](https://github.com/angelazhangmsft/ProjectionProject) that generating the projection with .NET 6 TFM doesn't produce Generated Files:

 ![image](https://user-images.githubusercontent.com/69016571/116452107-319a3700-a812-11eb-963b-e6fa07dfbfaa.png)
