### ISSUE TITLE
Questions: How do you bring in third-party winmds?

### ISSUE THREAD

**Issue by riverar** [microsoft/CsWinRT#748]
## Questions
The documentation states:
> In this project you would also need to reference the C#/WinRT NuGet package and the project-specific .winmd files you want to project, whether through a NuGet package, project reference or direct reference

But doesn't explain what a "direct reference" is.

**Q: What is a "direct reference"?**
**Q: How do I reference my external winmd?**

I tried, to no avail:
* adding a reference in my .csproj to a winmd via a `None` build action (e.g. `<None Include="../my.winmd">`)
* dropping the winmd directly into the project directory hierarchy for automatic inclusion
* manually specifying the file via `CsWinRTInputs` 

Entering gibberish into `CsWinRTInputs` also yields no error, which is very confusing. And none of the logging facilities work either, so I must have missed something.)

## Repro cases
* Repro for no log output, not clear how to reference winmd: [CsWinrtBringInWinmd.zip](https://github.com/microsoft/CsWinRT/files/6017421/CsWinrtBringInWinmd.zip)

* Repro for bad CsWinRTInputs not generating errors: [CsWinrtBadInputsRepro.zip](https://github.com/microsoft/CsWinRT/files/6017417/CsWinrtBadInputsRepro.zip)

## Additional information

.net5.0 project
Visual Studio 2019 16.8.5
Windows 10 19042
CsWinRT 1.1.2

**Comment by angelazhangmsft** [comment]
Hi Rafael, I noticed in your first repro you have `<OutputType>Exe</OutputType>`, but to build a projection you need to use a class library project. There is a [walkthrough here](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component) that demonstrates how to build a projection with a C# library project. 

You should be able to reference the a winmd using the `<None Include=..` or by browsing for the winmd file in the Reference Manager here.
![image](https://user-images.githubusercontent.com/69016571/108800744-d2395580-7548-11eb-9600-71d401c25f11.png)

`CsWinRTIncludes` is the property to use for specifying which namespaces to project and is required in your project file. The default is to not project any namespaces as documented [here.](https://github.com/microsoft/CsWinRT/tree/master/nuget) You shouldn't need `CsWinRTInputs`.

@Scottj1s, is there anything you can add on `CsWinRTInupts` not generating errors?

**Comment by riverar** [comment]
@angelazhangmsft I think I misunderstood the project completely. I was focused strictly on replicating what .NET yanked out of the runtime and overlooked the auto-magic that occurred. Sounds like I need to do some of the legwork of building the projection myself and then consume that in a subsequent step. I'll try this now.

There's definitely room here for some improvements around error checking and documentation!
