### ISSUE TITLE
Cannot build F# project with Microsoft.ProjectReunion.WinUI

### ISSUE THREAD

**Issue by xperiandri** [microsoft/CsWinRT#767]
**Describe the bug**
F# project that references `Microsoft.ProjectReunion.WinUI` does not build
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2902,7): error MSB4057: The target "XamlPreCompile" does not exist in the project.
```

**To Reproduce**
1. Clone https://github.com/xperiandri/Elmish.Uno/tree/uno_winui
2. Check out https://github.com/xperiandri/Elmish.Uno/tree/uno_winui branch
3. Open Elmish.Uno.sln
4. Build Elmish.Uno.fsproj

**Expected behavior**
Project builds sucessfully

**Version Info**
Microsoft.ProjectReunion.WinUI 0.5.0-prerelease

**Comment by angelazhangmsft** [comment]
@xperiandri Can you file this issue on the Reunion repo? https://github.com/microsoft/ProjectReunion
This seems like a Reunion issue, not C#/WinRT
