### ISSUE TITLE
Rust/WinRT fails when referencing two authored components - "Class not registered"

### ISSUE THREAD

**Issue by j0shuams** [microsoft/CsWinRT#776]
When two components are 'consumed' by a Rust component, at runtime one of them will fail with "Class not registered".

**Comment by angelazhangmsft** [comment]
The runtime error I see is: { code: 0x8007007E, message: "The specified module could not be found." }

**Comment by raffaeler** [comment]
Thank you both for logging this. Let me know if I can do some specific test to help.

**Comment by angelazhangmsft** [comment]
Here is an example of calling two C#/WinRT components in Rust which we can use to validate:  https://github.com/angelazhangmsft/rust-cswinrt-authoring/tree/angzhang/twocomponents

**Comment by angelazhangmsft** [comment]
Should validate this with fix from #922

**Comment by j0shuams** [comment]
I made a rust project that uses two cswinrt components here - https://github.com/j0shuams/rust-cswinrt-authoring/tree/two-references

This built and ran no problem, so closing this.
