### ISSUE TITLE
Question: How does one reference Windows SDK APIs?

### ISSUE THREAD

**Issue by stevedesmond-ca** [microsoft/CsWinRT#791]
Perhaps this is more a documentation issue than anything.

In .NET Core 3.1, I could use Windows SDK APIs simply by including a `PackageReference` to `Microsoft.Windows.SDK.Contracts` and running `dotnet build`.

Now with .NET 5, I'm trying to do the same using CsWinRT, but am seeing a viral expansion of requirements in the `CsWinRTIncludes` tag of my `csproj` file.

Minimal repro: https://github.com/stevedesmond-ca/CsWinRT-repro -- I would expect this to compile on `dotnet build`, as it does in 3.1 (adding `<OutputType>Exe</OutputType>` and removing the `CsWinRT` reference).

The only class actually used is `Windows.Devices.WiFi.WiFiAdapter`, but trying to build the code as-is then requires me to add everything that `WiFiAdapter` references. Doing that then requires I add everything that each of those classes reference.

The same is true if I use namespaces instead of classes in `CsWinRTIncludes`: I basically end up requiring the entire Windows SDK surface.

What am I missing (either technically in the `csproj` or theoretically in my understanding)?

**Comment by manodasanW** [comment]
@stevedesmond-ca With .NET 5, we build the Windows SDK projection generated using CsWinRT and distribute it as a package which the .NET SDK has a reference to.  If you were to use the .NET 5 Windows SDK specific TFMs like `net5.0-windows10.0.19041.0`, you would get an implicit reference to that projection package and be able to use the Windows SDK APIs like WifiAdapter.  You don't actually need to reference the `Microsoft.Windows.CsWinRT` package or the `Microsoft.Windows.SDK.Contracts` package unless you are looking to build your own CsWinRT projection for your own component.

**Comment by stevedesmond-ca** [comment]
So for Windows SDKs, the big change for .NET 5 is that they only work with the Windows TFM? Which means I would now need different projects for Windows vs Linux, where I could previously just switch on the platform ID within the same project?

**Comment by angelazhangmsft** [comment]
@stevedesmond-ca yes with .NET 5, you now access Windows APIs using the TFM instead of needing a package reference. These docs have more information on .NET 5 + OS-specific TFMS: https://docs.microsoft.com/en-us/dotnet/standard/frameworks#net-5-os-specific-tfms

Specifically, 

> To make your app portable across different platforms but still have access to OS-specific APIs, you can target multiple OS-specific TFMs and add platform guards around OS-specific API calls using #if preprocessor directives.

**Comment by stevedesmond-ca** [comment]
Thanks for the info!
