### ISSUE TITLE
Question: [What .NET Type projects to TypedEventHandler?]

### ISSUE THREAD

**Issue by raffaeler** [microsoft/CsWinRT#797]
Instead of exposing events using EventHandler, whose sender is an object (IInspectable), I would like to project the object type using `TypedEventHandler`.
How can I make the projection generating a `TypedEventHandler<TSender, TArgs>` ?

Thanks

**Comment by angelazhangmsft** [comment]
@Scottj1s, @manodasanW - are you able to answer this?

**Comment by manodasanW** [comment]
@raffaeler are you try to do this in a consumption scenario (native component being projected via C#/WinRT in C#) or an authoring scenario (projecting a C# component into WinRT)?  For the former, if your native component uses Windows.Foundation.TypedEventHandler like [here](https://github.com/microsoft/CsWinRT/blob/7d7025896aea22a02e059eb6684575dcd40afa8d/src/Tests/TestComponentCSharp/TestComponentCSharp.idl#L126), it should be projected similarly.  There is no custom type mapping for it to .NET built-in types like for EventHandler, but Windows.Foundation.TypedEventHandler is projected in C# as is.  For the latter scenario, you should be able to use that type in your C# component.

**Comment by raffaeler** [comment]
@manodasanW I am authoring a custom component and willing to expose the TypedEventHandler to C++ and Rust.
Kenny told me that I can't avoid the QueryInterface if the sender was authored as object. He told me that TypedEventHandler must be authored since the beginning in order to benefit from the typed information. Of course I can just "cast".

So I am asking if I have any way to author my event so that it appears as TypedEventHandler<> in the winmd metadata

**Comment by manodasanW** [comment]
@raffaeler In your C# component, you should be able to just declare your event like `public event Windows.Foundation.TypedEventHandler<Sender, Result> TypedEvent;` or something similar to that and it should achieve what you want where it is exposed in the winmd and to consumers.

**Comment by angelazhangmsft** [comment]
Closing as this seems to be answered - @raffaeler feel free to reopen if this didn't answer your question!
