### ISSUE TITLE
Need public docs for supported custom type mappings

### ISSUE THREAD

**Issue by j0shuams** [microsoft/CsWinRT#806]
Something like [this](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/net-framework-mappings-of-windows-runtime-types), which was for UWP.

**Comment by angelazhangmsft** [comment]
Added docs for C#/WinRT custom type mappings, and edited existing doc to clarify mappings for UWP vs .NET 5/Desktop.

https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-mappings-of-winrt-types
