### ISSUE TITLE
Drag&Drop scenario broken because InvalidCastException

### ISSUE THREAD

**Issue by marb2000** [microsoft/CsWinRT#807]
**Describe the bug**
This is a frequent and basic drag & drop scenario. In a WinUI 3 Desktop app, when dragging an element that contains DataPackage, there is a InvalidCastException because it was no possible to cast DataPackage to DataPackageView. This was working in UWP with .NET Native before. 

Here is the exception:
```
System.InvalidCastException: Unable to cast object of type 'Windows.ApplicationModel.DataTransfer.DataPackage' to type 'Windows.ApplicationModel.DataTransfer.DataPackageView'.
at WinRT.ComWrappersSupport.CreateRcwForComObject[T](IntPtr ptr)
at WinRT.MarshalInspectable`1.FromAbi(IntPtr ptr)
at Windows.ApplicationModel.DataTransfer.DataPackageView.FromAbi(IntPtr thisPtr)
at ABI.Microsoft.UI.Xaml.IDragEventArgs.global::Microsoft.UI.Xaml.IDragEventArgs.get_DataView()
at Microsoft.UI.Xaml.DragEventArgs.get_DataView()
```
**To Reproduce**
1. Clone this [repository](https://github.com/marb2000/DragDropBud_Reunion.0.5.5).
2. Run the app and you will see something like this:
![image](https://user-images.githubusercontent.com/12536513/115089859-19e4b980-9ec8-11eb-84f7-b079da409bf9.png)

3. Try to drag the **First Label** element or the **Another Label** element into the TreeView. 
4. You will observe the Exception in the Output window. Feel free to place some breakpoints when capturing the exception.

**Expected behavior**
Work nicely and beautiful showing up even the pictures (a rendered text of First Label or Another Label)

**Version Info**
```XML
<PackageReference Include="Microsoft.ProjectReunion" Version="0.5.5" />
<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.5" />
<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.5" />
<PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.2.2" />
```

**Comment by Marv51** [comment]
Can we get an update on how things are going with this bug?

**Comment by rick-palmsens** [comment]
We were expecting this to have been fixed based on the milestone. Drag and drop still cannot be implemented properly in our WinUI app. And as said in the first post:
> This is a frequent and basic drag & drop scenario.

So when can we expect this to be fixed? Is someone working on it, or is it going to keep getting moved to later milestones?

**Comment by ujjwalchadha** [comment]
@Marv51 @rick-palmsens We are working on root causing this bug currently and trying out some potential fixes. You can expect a fix in upcoming milestone.
