### ISSUE TITLE
Authored component .dll -- processor architecture mismatch

### ISSUE THREAD

**Issue by j0shuams** [microsoft/CsWinRT#811]
We need to make sure a component can author winui types and have those be consumed by a winui app. 
For "winui" we are focusing on the ProjectReunion version of WinUI. Currently, I have a component producing a winmd, and a c++ app consuming it and trying to use one of the types via **ProjectReference**

You can change the build configuration to build for x86 instead of x64, and you'll get past this error. But we should support x64 out of the box. 

Repro: Build the solution here for x64
https://github.com/j0shuams/ReunionAuthoringSample

**Describe the bug**
The bug is a build failure:
```
"c:\gh\Repros\ReunionAuthoringSample\ReunionAuthoringSample.sln" (default target) (1) ->
"c:\gh\Repros\ReunionAuthoringSample\CppApp\CppApp\CppApp.vcxproj" (default target) (4:6) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targe
ts(2204,5): 

error MSB3271: There was a mismatch between the processor architecture of the project being built "AMD64" a
nd the processor architecture, "x86", of the implementation file "c:\gh\Repros\ReunionAuthoringSample\MyLibrary\bin\Deb
ug\net5.0-windows10.0.19041.0\MyLibrary.dll" for "c:\gh\Repros\ReunionAuthoringSample\MyLibrary\bin\Debug\net5.0-window
s10.0.19041.0\MyLibrary.winmd". 

This mismatch may cause runtime failures. Please consider changing the targeted process
or architecture of your project through the Configuration Manager so as to align the processor architectures between yo
ur project and implementation file, or choose a winmd file with an implementation file that has a processor architectur
e which matches the targeted processor architecture of your project. [c:\gh\Repros\ReunionAuthoringSample\CppApp\CppApp
\CppApp.vcxproj]
```

**Version Info**
CsWinRT : **1.2.3**
ProjectReunion (& co.) : **0.5.5**

It would be good to try this same scenario but using a PackageReference.

**Comment by angelazhangmsft** [comment]
Is this because the path of the winmd is wrong?  I wasn't able to repro after setting all my configs to x64, and removing/readding the winmd reference. 

I think the path should be c:\gh\Repros\ReunionAuthoringSample\MyLibrary\bin\x64\Debug\net5.0-windows\10.0.19041.0\MyLibrary.winmd

I did however run into #812 but not this issue.

**Comment by angelazhangmsft** [comment]
I saw this error with a command line build using `msbuild`, but not a VS build. This was using this repro (packaging scenario): https://github.com/angelazhangmsft/AuthoringPackagingScenarios

**Comment by j0shuams** [comment]
Did not repro on reunion 0.8.1
