### ISSUE TITLE
Reunion app failing to load authored type

### ISSUE THREAD

**Issue by j0shuams** [microsoft/CsWinRT#812]
The same background details as #811 

This is the case where we build for x86. The build goes through, but on launch when the CustomButton type tries to get created there is a failure "Error in the Dll" 

I have a .dmp of this, just can't attach to the issue. 

The output folders look good -- all WinRT.xx.dll are there, as well as MyLibrary.dll and MyLibrary.winmd

**Comment by angelazhangmsft** [comment]
This is not an x86-specific issue, related issue tracked in #955
