### ISSUE TITLE
CsWinRT filters Microsoft namespace, precluding ReactNative consumption

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#817]
I started a new Reunion app, added a WinRT component (Microsoft.ReactNative) and tried to build the interop assembly by creating a new .net core 5 project, referencing cswinrt, and referencing the Microsoft.ReactNative project per the instructions.
However, no projections are generated
I think this is because ReactNative is under the Microsoft namespace

**Comment by Scottj1s** [comment]
Yes, "Microsoft" and "Windows" are filtered out by default

**Comment by asklar** [comment]
What's the plan or workaround for teams who ship APIs under the Microsoft namespace, but are not part of Reunion?

**Comment by DrusTheAxe** [comment]
@Scottj1s by default

That implies there's a way to override it. Is there a certain property or #define or like magic?

**Comment by manodasanW** [comment]
To confirm, have you tried adding ```<CsWinRTIncludes>Microsoft.ReactNative</CsWinRTIncludes>``` to your csproj and that didn't generate the projection?

If so, you should be able to do something like below which takes precedence over the `CsWinRTIncludes` and `CsWinRTExcludes` property.  More details [here](https://github.com/microsoft/CsWinRT/blob/ad6adcb997b40cea649cf4156451316e714bc3ea/nuget/readme.md#customizing).

```
    <CsWinRTFilters>
-include Microsoft.ReactNative
    </CsWinRTFilters>
```
