### ISSUE TITLE
Building both Debug/Release or multiple archs end up trying to compile more than one copy leading to build errors

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#819]
Build a projection in debug, then build it in release
it seems like the project ends up trying to use all of the cs files under any folder, without regard for what Configuration or Platform it is, which results in wrong/duplicate definitions

**Comment by Scottj1s** [comment]
Building out-of-source should avoid this, so that projects don't implicitly include all generated source files found under the project folder, but instead only include [those explicitly added by cswinrt](https://github.com/microsoft/CsWinRT/blob/da4541151f30a1e7decbb30481ec6a8896344ff3/nuget/Microsoft.Windows.CsWinRT.targets#L119).

**Comment by asklar** [comment]
Hm weird that you didn't run into the error; did you do the directory.build.props thing that the docs mention?
My gut feel is that this happens because the C# projects are trying to build "any files under the current folder" and when you build Debug you get one set of files under x64\Debug\Generated Files, then when you switch to Release the first set of files aren't deleted, and a separate set of files is put in x64\Release\Generated Files, then when you build both sets of files get sucked in

**Comment by angelazhangmsft** [comment]
Did the error occur when you built the projection for Release (after building for Debug)?  I am building out-of-source (with the Directory.build.props file), is that what you did as well?

**Comment by asklar** [comment]
yes I believe that is the same set of steps though it's been about a week so my memory is starting to fade 😆

**Comment by angelazhangmsft** [comment]
Closing as the docs have been updated to explain building out of source and architecture neutral/specific assemblies. The C#/WinRT projection DLLs are architecture-neutral, but the [projection sample](https://github.com/microsoft/CsWinRT/tree/master/src/Samples/Net5ProjectionSample) is configured to build with x64/Debug to avoid warnings on mismatch between processor architecture when referencing the architecture-specific C++/WinRT Component.
