### ISSUE TITLE
Walkthrough is broken once we add Directory.Build.props

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#820]
After adding Directory.Build.props which overrides the output directory to be under _build, deployment of the resulting app fails because the appxrecipe file cannot be found

The file is in:
`C:\Users\asklar\source\repos\rn64Reunion\windows\_build\x64\Release\RN64Reunion (Package)\bin\RN64Reunion (Package)\RN64Reunion (Package).build.appxrecipe`

However the packaging project looks for it in:
`C:\Users\asklar\source\repos\rn64Reunion\windows\RN64Reunion (Package)\bin\x64\Release\RN64Reunion (Package).build.appxrecipe`

**Comment by angelazhangmsft** [comment]
I am not able to repro this issue - here's a repro of consuming the SimpleMathComponent in a Project Reunion app: https://github.com/angelazhangmsft/ProjectReunionSimpleMathProjection

I was able to deploy the app fine. If there's a repro, I can look into it

**Comment by angelazhangmsft** [comment]
Closing since I wasn't able to repro. Feel free to reopen with a repro project if this issue occurs again.
