### ISSUE TITLE
Question: List of changes is not available

### ISSUE THREAD

**Issue by kant2002** [microsoft/CsWinRT#823]
I see that in the release, there link to list of changes, but it is not accessible.

**Comment by angelazhangmsft** [comment]
@kant2002 - Yes, it seems like the release pipeline automatically adds this link which is internal only. @j0shuams is there a way to edit the release pipeline so we don't get "This list of changes was auto generated"?

**Comment by manodasanW** [comment]
Note that the link is actually to the build which generated the change list.  The change list is still listed above where the link is.

**Comment by kant2002** [comment]
@angelazhangmsft technically I would like to see and list of changes, but if that's too complicated to place in the build description, I would not insist.

**Comment by manodasanW** [comment]
@kant2002 to confirm, are you just looking for a list of changes for a release or was your concern the link specifically?

**Comment by kant2002** [comment]
I was looking for list of changes (obviously want to read them in Release page). But I think that bad experience have a link and not able to navigate it. 

In my opinion would be good to have list of changes without link. 
But if this touch your infra, it maybe not so easy for you as it sounds. I would not die on that hill.

**Comment by angelazhangmsft** [comment]
@kant2002 there is a list of commits under the "Changes" section, for example:

![image](https://user-images.githubusercontent.com/69016571/116267436-43f07400-a731-11eb-984d-94fa936ee6f0.png)

You could look through the specific commits here, is that what you're looking for?
