### ISSUE TITLE
Evaluate finalizer performance time

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#834]
Evaluate finalizer performance time - how much time are we spending on larger apps e.g. Fresco

**Comment by manodasanW** [comment]
During marshaling, we no longer create an IObjectReference.  But rather we now use an ObjectReferenceValue which is a value type which doesn't need to be finalized.  This has saved a considerable amount of finalizer time given before this change each function call probably made use of marshaling and caused for a couple objects to be allocated.
