### ISSUE TITLE
Net5ProjectionSample: can't use x86 Projection

### ISSUE THREAD

**Issue by mjfusa** [microsoft/CsWinRT#835]
**Describe the bug**
When building for x86 when resulting .nupkg is reference in Reunion 0.5 app, you see the following error:
```Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3270	There was a mismatch between the processor architecture of the project being built "x86" and the processor architecture of the reference "C:\Users\mikefra\.nuget\packages\simplemathcomponent\0.1.0-prerelease\lib\net5.0\SimpleMathProjection.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.	App1	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	2182	
```

**To Reproduce**

1. Build Net5ProjectionSample targeting x86 from this repo.
2. Install Project Reunion pre-requisites and create WinUI Desktop app.
3. Add the nupkg created in step one to the Reunion app.
4. Build. Note Error. 

**Expected behavior**

Would expect x86 version of projection to be consumable by Reunion app. This works as expected when targeting x64.

**Version Info**

CsWinRT: 1.2.5
Windows SDK: 10.0.19041.0

**Additional context**

**Comment by angelazhangmsft** [comment]
Hi @mjfusa, this error looks like the nupkg includes an assembly built with x64. Did you change the configuration for both SimpleMathComponent and SimpleMathProjection to target Win32/x86? 

Also just making sure - did you update these paths in the nuspec from x64 -> x86?
https://github.com/microsoft/CsWinRT/blob/9359ad7a32985831b2483cc5fbc35ac66240c3f7/src/Samples/Net5ProjectionSample/SimpleMathProjection/nuget/SimpleMathProjection.nuspec#L19

**Comment by angelazhangmsft** [comment]
This looks like a similar issue as well - #811

**Comment by angelazhangmsft** [comment]
Hi @mjfusa, it looks like this error occurs when either the C++/WinRT component or C# projection project is built for x64. I would confirm that the configuration manager is set to Win32 for **SimpleMathComponent** and x86 for **SimpleMathProjection**. You will also need to alter the nuspec to include the correct paths and RID-relative folder for x86.

I have a repro project here that builds for x86 and consumes the projection from a Project Reunion app: https://github.com/angelazhangmsft/ProjectReunionSimpleMathProjection

Let me know if you are still running into issues.
