### ISSUE TITLE
Question: Roadmap for project references

### ISSUE THREAD

**Issue by nseveno** [microsoft/CsWinRT#851]
Hi,

With the current version of WinUI, we can write a UWP application in C# and consume C++/WinRT components from the same solution using project references. I have a big solution that uses project references between a UWP / WinUI 2 C# application and C++/WinRT components. I would like to migrate this application to the desktop WinUI 3 platform because the UWP platform is limiting the APIs I can use. 

With WinUI 3, to consume a C++/WinRT component, I must use C#/WinRT. But according to [the documentation](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component), I must use a Nuget instead of a project reference. The procedure is complicated. This breaks the fast "F5" development loop.

I was not able to find a roadmap for the C#/WinRT project. Do you plan to bring back project references ? If so, when ? I would like to know what are the options for my project...

Thanks,

Nicolas

**Comment by angelazhangmsft** [comment]
@nseveno - The project reference scenario hasn't been documented yet, although it is supported with some known issues. Our typical recommendation is to build an interop projection project which references your C++/WinRT component as demonstrated in the docs above and this [sample](https://github.com/microsoft/CsWinRT/blob/f84a3d5294f3bd99d6372ce5c754327192b605ff/src/Samples/Net5ProjectionSample/SimpleMathProjection/SimpleMathProjection.csproj#L15), and reference the interop projection project from your app via project reference. Note there is a known issue (#756) so you will need to add a cswinrt NuGet reference in your app.

We do also support a project reference to your component directly from your C# app project, but this may result in issues if there are multiple references to the same component, with each building their own projection. The interop projection project approach allows you to share the projection.

**Comment by nseveno** [comment]
Hi,

Thank you for answering.
I tried the workaround : it works.

Thanks again.

Nicolas
