### ISSUE TITLE
.winmd Referencing issues when targeting .NET5 framework or higher 

### ISSUE THREAD

**Issue by HSoumi** [microsoft/CsWinRT#854]
**Describe the bug**

I had created a c++/winrt component for which a projection was then made following the Sample code given here. On building, the component is built fine but the Nuget package is unable to be formed since the projection project is failing to build. As shown in the photo below, it says we **cannot reference .winmd file directly if we're targeting a .NET 5 or higher framework**.

**Expected behavior**

Previously, my projection project was building successfully. But on updating my visual studio 2019 preview version (used an only this version supports WINUI 3.0 development), this error is showing for my projection project no matter what latest SDK version I'm using.

**Version Info**

_CsWinRT nuget_ -> 1.2.6 version (latest one)
_Visual studio 2019_ -> Preview version (16.11.0 Preview 1.0)
_Project Reunion_ -> 0.5.0 version
_.NET SDK Version_ -> 5.0.300

**Additional context**

<img width="628" alt="pocError" src="https://user-images.githubusercontent.com/40801404/119946215-055e0b80-bfb4-11eb-91f2-319774756a2a.png">

**Comment by angelazhangmsft** [comment]
Hi @HSoumi, can you upload a repro or binlog of this issue? I was not able to repro the issue.

**Comment by j0shuams** [comment]
Can you elaborate on the project structure? I have seen this when a net5 app has a project reference to cppwinrt project. But wouldn't expect this from a nuget reference.

**Comment by HSoumi** [comment]
> Hi @HSoumi, can you upload a repro or binlog of this issue? I was not able to repro the issue.

**Comment by HSoumi** [comment]
Git repo containing the project: https://github.com/HSoumi/TestComponent

The project structure is also there in this link @j0shuams : a c++/winrt component was referenced using a c# based projection to create a NuGet package for that component

**Comment by angelazhangmsft** [comment]
@HSoumi, I tried building your project and I was able to successfully build the NuGet package. I'm on VS 16.11 Preview 1 and .NET SDK 5.0.300. There were [changes with the NETSDK1130 error](https://github.com/dotnet/sdk/pull/17098), which may be the reason for this error, although I'm not able to repro it. Would you be able to provide a binlog so we can investigate further?

**Comment by HSoumi** [comment]
The binlog files have been uploaded under the same Git repo: https://github.com/HSoumi/TestComponent/tree/master/testcomponent_logs

**Comment by angelazhangmsft** [comment]
cc/ @dsplaisted who worked on the NETSDK1130 errors. Would you be able to take a look at the binlogs in the repo above?

**Comment by dsplaisted** [comment]
Does the project fail to build from the command line or also in VS?  If it fails from the command line, could you share a binlog from a command line build (via the `/bl` MSBuild parameter), as those have a lot more information than what VS gathers.

**Comment by HSoumi** [comment]
@dsplaisted I've added the binlog file got from a failed build in Command line, here: https://github.com/HSoumi/TestComponent/tree/master/testcomponent_logs

**Comment by dsplaisted** [comment]
I tried building the repro and for me it built successfully.  I looked at the binlogs, and the difference appears to be that in the failing binlog, the .targets file from the Microsoft.Windows.CSWinRT package is not being imported, so the CsWinRTRemoveWinMDReferences target isn't being run, which results in the error.

I don't know why that .targets file isn't being imported.  Perhaps something didn't work in the NuGet restore.  Can you try running the command line build, but adding the `/restore` parameter to it?

**Comment by HSoumi** [comment]
@dsplaisted I did what was asked using the /restore parameter. The project still failed to build. 
The binlog for that: https://github.com/HSoumi/TestComponent/tree/master/testcomponent_logs
Kindly take a took.

**Comment by angelazhangmsft** [comment]
Closing as we cannot repro the issue.
