### ISSUE TITLE
error CS0111: Type 'SomeType' already defines a member called 'Equals' with the same parameter types

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/CsWinRT#864]
**Describe the bug**
CsWinRT generates duplicate Equals methods if the underlying type in the WInMD already has an Equals() method with itself as the type parameter

**To Reproduce**
Create a C++WinRT component with a type that has an Equals method with itself as the equator. For example:

```
    runtimeclass SomeType
    {
        SomeType();

        Boolean Equals(SomeType someType);
    };
```

Pass the WinMD to CsWinRT.

**Expected behavior**
No error.

**Version Info**
CsWinRT 1.2.6

**Comment by angelazhangmsft** [comment]
We should investigate the built-in support behavior in .NET Native/.NET Core to see what they do

**Comment by angelazhangmsft** [comment]
With existing built-in .NET support for WinRT, default behavior for ToString, Equals(Object), and GetHashCode methods is provided for C# WinRT components. According to [these docs](https://docs.microsoft.com/dotnet/api/system.object.equals?view=net-5.0#System_Object_Equals_System_Object_), Windows Runtime classes that are written in C# or Visual Basic can override the Equals(Object) method overload. 

@Scottj1s - is it possible to define/override the Equals method from a C++/WinRT component that is projected into C#/.NET 5?

**Comment by angelazhangmsft** [comment]
Looking into the existing .NET Native support:

If we have a C++/WinRT component with the following definition:

```
runtimeclass Class
    {
        Class();
        Boolean Equals(Class c);
    }
```
Consuming this component from a .NET Native (UWP) C# application, I see two Equals methods (overloaded):

```csharp
public bool Equals(Class c); // in my RuntimeComponent
public virtual bool Equals(Object obj); // in System.Runtime

**Comment by jlaanstra** [comment]
It sounds like CsWinRT should probably not auto-generate the implementation of IEquatable<SomeType>. Thoughts?

**Comment by angelazhangmsft** [comment]
CsWinRT should ensure the IEquatable pattern of 5 methods is enforced, picking up any methods that the runtime component implements.

**Comment by Corillian** [comment]
I just ran into this problem :sob:.

**Comment by pontin-pdftron** [comment]
Same problem here. 
We have an old component in C++/CX which overrides Equals and when migrating to C++/WinRT got the same issue.
