### ISSUE TITLE
Generated file WinRTEventHelpers.cs fails fsharp projects

### ISSUE THREAD

**Issue by vslynko** [microsoft/CsWinRT#887]
**Describe the bug**
When Microsoft.Windows.CsWinRT (1.3.0) is referenced from an FSharp based project, the build fails.

`
Error	FS0226	The file extension of 'obj\x64\Debug\net5.0-windows10.0.19041.0\win-x64\Generated Files\WinRTEventHelpers.cs' is not recognized. Source files must have extension .fs, .fsi, .fsx, .fsscript, .ml or .mli.	WAVEcontrol.Tests	C:\src\wavecontrol\src\WAVEcontrol.Tests\FSC	1	Active
`

**To Reproduce**
1. Create an FSharp project and reference Microsoft.Windows.CsWinRT (1.3.0) package.
2. Try build

**Expected behavior**
Build should succeed as with  Microsoft.Windows.CsWinRT (1.2.6)

**Version Info**

`.NET SDK (5.0.203)`
`Microsoft.WindowsDesktop.App 5.0.6`

```*.fsproj
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>
    <DisableImplicitSystemValueTupleReference>true</DisableImplicitSystemValueTupleReference>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <IsPackable>false</IsPackable>
    <Deterministic Condition="'$(NCrunch)' == '1'">false</Deterministic>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <GenerateProgramFile>false</GenerateProgramFile>
```

**Additional context**

**Comment by angelazhangmsft** [comment]
@vslynko - Could you expand on why you are referencing the CsWinRT package? The CsWinRT package doesn't support generating projections for F# scenarios.

**Comment by manodasanW** [comment]
Just to further clarify, the net5.0-windows10.0.19041.0 TFM that you are already using has an implicit reference to the C#/WinRT generated Windows SDK projection which provides you access to the Windows WinRT APIs.  If you are not looking to build your own custom C#/WinRT projection for your own component, you do not need a CsWinRT package reference.  As Angela mentioned, it would be good to know the scenario that you are trying to use the CsWinRT package reference in: whether to use the Windows WinRT APIs, build your own projection for your component, or something else?

**Comment by vslynko** [comment]
Thank you @angelazhangmsft and @manodasanW. 

1. The main problem I was trying to solve is to use Windows 10 toast notifications from net48 application, through using `Microsoft.Toolkit.Uwp.Notifications`.
2. So I had a WPF winexe C# project and xunit F# project referencing it.
3. Then I have migrated everything to net50
4. Then I played for a long time to refactor everything until toast notifications work again. And the working solution at that time was to reference from WPF C# project following packages:
  - Microsoft.Toolkit.Uwp.Notifications
  - Microsoft.Windows.SDK.Contracts
  - Microsoft.Windows.CsWinRT
  and set the `<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>`

and only reference `Microsoft.Windows.CsWinRT` from F# xunit project, so tests work again
5. But with update to 1.3.0 of CsWinRT this stopped working.
6. But looking at this hint
> net5.0-windows10.0.19041.0 TFM that you are already using has an implicit reference to the C#/WinRT

i understood that only ` <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>` is important and removed the dependencies
```
-    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.3.0" />
-    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />
```

and this helped.

Apologies for being dumb.
