### ISSUE TITLE
Building projection with 18362 SDK results in empty binary

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#892]
using cswinrt 1.3.0

Building a projection for Microsoft.ReactNative (see [Microsoft.ReactNative.ProjectReunion](https://github.com/microsoft/react-native-windows/pull/8064/checks?check_run_id=2880779519)).
If I set 
```
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
```

Then I get a working DLL, size 329216 bytes.

If I set
```
    <TargetFramework>net5.0-windows10.0.18362.0</TargetFramework>
```

Then the resulting DLL is 4 kB and has no information in it. 
Attaching bad DLL, deps.json and binlog: 
[Microsoft.ReactNative.ProjectReunion.zip](https://github.com/microsoft/CsWinRT/files/6692290/Microsoft.ReactNative.ProjectReunion.zip)

**Comment by asklar** [comment]
@Scottj1s @j0shuams does this sound familiar by chance?

**Comment by Scottj1s** [comment]
The binlog shows only Windows SDK and Project Reunion winmds as input, but no ReactNative winmds, which explains the output.  Is the solution missing a package/project reference in the interop project, to pick these winmds up?

https://github.com/microsoft/CsWinRT/blob/f3d14e5cac610f2251a8cabdddfc4570343ac997/docs/usage.mda

**Comment by asklar** [comment]
This worked when using 19041 for whatever reason (the only thing that I changed was the TFM). See PR linked in the original description if you're curious :)

**Comment by asklar** [comment]
@scottj1s I found something interesting: a warning that I had missed:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2526,6): 
warning MSB3851: This project targets "Windows, Version=10.0.18362.0", but it is attempting to reference "C:\rnw\vnext\target\x64\Release\Microsoft.ReactNative\Microsoft.ReactNative.winmd" targeting "UAP,Version=10.0.19041.0", which is invalid. [C:\rnw\vnext\Microsoft.ReactNative.ProjectReunion\Microsoft.ReactNative.ProjectReunion.csproj]
```

The native microsoft.reactnative project has:
```xml
    <WindowsTargetPlatformVersion Condition=" '$(WindowsTargetPlatformVersion)' == '' ">10.0.19041.0</WindowsTargetPlatformVersion>
    <WindowsTargetPlatformMinVersion>10.0.17134.0</WindowsTargetPlatformMinVersion>
```

We recently [moved WindowsTargetPlatformVersion from 18362 to 19041](microsoft/react-native-windows#7779), because 19041 became the default that's installed with VS, so new developers installing VS today would get 19041, not 18362.
It seems odd that we would get an error for targeting 19041 if min version is 17134. It sounds like that check should be done against min version, not target version. 

Thoughts?

**Comment by Scottj1s** [comment]
TPV/TPMV have always tripped up innocent souls like yourself.  TPV is the SDK version that you actually build against, and TPMV is the version that you promise you've tested down to.  That's a very brittle system IMO, and I've always advised to set them equal unless you have light-up code (ApiInformation checks) requiring otherwise.

Given that, I think your fix should be to change your projection to target 19041 as well (not 18362)

**Comment by Scottj1s** [comment]
After addressing Alex's concerns, opened a dedicated bug for the last bullet, closing.

**Comment by asklar** [comment]
Making the warning an error is tracked by #906
