### ISSUE TITLE
Update walkthrough

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#895]
@manodasanW had a number of comments about how we set up RNW's cswinrt projection, but we were following the walkthrough, so I'm filing this so that the cswinrt walkthrough can be updated with the most up to date guidance

https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component

--
Reunion packages have been for the most part leaving out the CsWinRT reference as dependency here as the dependencies from CsWinRT (WinRT.Runtime) also come from the TFM for consumers.

_Originally posted by @manodasanW in https://github.com/microsoft/react-native-windows/pull/8064#discussion_r656437476_

**Comment by angelazhangmsft** [comment]
I've updated the [walkthrough](https://docs.microsoft.com/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component) to modify our guidance. Let me know if there's any further feedback.
