### ISSUE TITLE
CsWinRT NuGet includes the buildTransitive folder but doesn't follow the NuGet conventions for it.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/CsWinRT#908]
**Describe the bug**
NuGet guidance says that if you have a buildTransitive folder, it should match the content of the build folder. However in this case I don't think the targets are intended to be transitive. 

Since the file from the buildTransitive folder is only used for generation of packages and is the same as the file in the build folder, it can probably just be removed.

**Comment by j0shuams** [comment]
What do you mean the targets aren't intended to be transitive? The targets file is important for any C#/WinRT component author, so that their component can be used naturally by any (C++ or C#) consuming app.

**Comment by jlaanstra** [comment]
For a props/targets file to be consumed by NuGet, it needs to have the name of the package. Other files are ignored, unless you manually import them. Given that the name here doesn't match, the file will never be used.

**Comment by j0shuams** [comment]
Yes that is true, but we change the name of the file when packaging it to the component's name. Notice here that for `PackagePath` we are not passing "Microsoft.Windows.CsWinRT.Authoring.Transitive.targets" but rather "$(AssemblyName).targets"

https://github.com/microsoft/CsWinRT/blob/92f671d2f6fffca6f4119f549a05225b6a0329a9/nuget/Microsoft.Windows.CsWinRT.Authoring.targets#L171-L175

**Comment by jlaanstra** [comment]
Right and so I update this to pick the file from the build folder as it has the same contents, so it should work as expected.
