### ISSUE TITLE
Question: Is it possible to run a background task in full trust?

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/CsWinRT#913]
I have a Project Reunion 0.8.1 desktop app (full trust) with a background task from CsWinRT component.

Is it possible to configure and run this task in full trust to perform few activities like copying files etc?

**Comment by Scottj1s** [comment]
Yes, but the background task package needs to be specifically manifested for full trust:
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-fulltrustprocess
