### ISSUE TITLE
Localization - move user facing strings into string table

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#917]
## Summary
For localizing CsWinRT tool errors and WinRT.Runtime errors, this will require moving all user-facing strings into a string table first.

## Rationale
Provide localized error messages from WinRT.Runtime.dll and the cswinrt tool.

## Important Notes
cswinrt.exe would require string table work, but [code_writers](https://github.com/microsoft/CsWinRT/blob/master/src/cswinrt/code_writers.h) is clean, so generated code should not be a problem.  WinRT.Host.dll has a [table of exception strings](https://github.com/microsoft/CsWinRT/blob/master/src/Authoring/WinRT.Host/WinRT.Host.cpp) that are user-facing, as does [WinRT.Runtime.dll](https://github.com/microsoft/CsWinRT/blob/master/src/WinRT.Runtime/ExceptionHelpers.cs#L385).  Those would need to be localized and most likely shipped in the CsWinRT package.

**Comment by j0shuams** [comment]
@angelazhangmsft Should we consider this for 1.4.1?
