### ISSUE TITLE
Generator crash on class that doesn't implement an interface correctly

### ISSUE THREAD

**Issue by asklar** [microsoft/CsWinRT#940]
The code below is incorrect (Class1 doesn't implement Interface1 correctly since f takes a float instead of a MyEnum).
However, the generator will crash, instead of emitting diagnostics.

```cs
namespace CppComponent
{
    public enum MyEnum
    {
        Value1 = 42,
        Value2 = 99
    }

    public interface Interface1
    {
        void f(int x, MyEnum y);
    }

    sealed public class Class1 : Interface1
    {
        public void f(int x, float y);
    }
}
```

**Comment by manodasanW** [comment]
We might need a diagnostic to check all the methods to ensure it correctly implements the interface, but I would also expect C# built-in diagnostics to catch it.  We should look at why it isn't.
