### ISSUE TITLE
error CS0122: 'Interface' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/CsWinRT#948]
**Describe the bug**
Compiling a CSWinRt projection results in error CS0122: 'Interface' is inaccessible due to its protection level, see attached repro.

**To Reproduce**
Compile attached repro.

**Expected behavior**
No compile error.
[CsWinRTInterfaceRepro.zip](https://github.com/microsoft/CsWinRT/files/6941679/CsWinRTInterfaceRepro.zip)

**Comment by asklar** [comment]
Gist of the repro:
```cs
namespace RuntimeComponent2
{
    interface Interface
    {
        String FileName{ get; };
        Int32 Item { get; };
    };
}
```

```cs
namespace RuntimeComponent1
{
    interface Interface2 requires RuntimeComponent2.Interface
    {
        Int64 Id { get; };
    };
}
```

**Comment by jlaanstra** [comment]
@asklar are you sure it repro's with this? I think the setter for the same property in a separate interface is needed.
