### ISSUE TITLE
Hosting C# user control results in errors with generated code

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/CsWinRT#956]
Hosting a C# WinUI user control is resulting in errors with the generated C++/WinRT code. See dump below:

<details>
D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\XamlTypeInfo.g.cpp(401,55): error C2039: 'MyLibrary_XamlTypeInfo': is not a member of 'winrt::MyLibrary'
1> D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\winrt\MyLibrary.h(118): message : see declaration of 'winrt::MyLibrary'
1> D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\XamlTypeInfo.g.cpp(401,55): error C3083: 'MyLibrary_XamlTypeInfo': the symbol to the left of a '::' must be a type
1> D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\XamlTypeInfo.g.cpp(401,79): error C2039: 'XamlMetaDataProvider': is not a member of 'winrt::MyLibrary'
1> D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\winrt\MyLibrary.h(118): message : see declaration of 'winrt::MyLibrary'
1> D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\XamlTypeInfo.g.cpp(401,99): error C2259: 'winrt::CppApp::implementation::XamlMetaDataProvider': cannot instantiate abstract class
1> D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\XamlMetaDataProvider.h(36): message : see declaration of 'winrt::CppApp::implementation::XamlMetaDataProvider'
1> D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\XamlTypeInfo.g.cpp(401,99): message : due to following members:
1> D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\XamlTypeInfo.g.cpp(401,99): message : 'void winrt::impl::root_implements<D,winrt::CppApp::XamlMetaDataProvider>::use_make_function_to_create_this_object(void)': is abstract
1> with
1> [
1> D=winrt::CppApp::implementation::XamlMetaDataProvider
1> ]
1> D:\repros\ReunionAuthoringSample\CppApp\CppApp\Generated Files\winrt\base.h(7197): message : see declaration of 'winrt::impl::root_implements<D,winrt::CppApp::XamlMetaDataProvider>::use_make_function_to_create_this_object'
1> with
1> [
1> D=winrt::CppApp::implementation::XamlMetaDataProvider
1> ]
</details>

**Comment by angelazhangmsft** [comment]
@j0shuams is this a fix in C#/WinRT, or do we need to make changes in C++/WinRT?

**Comment by j0shuams** [comment]
Closing as this no longer repro's
