### ISSUE TITLE
IIDOptimizer runs during DesignTimeBuild slowing down project load.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/CsWinRT#961]
**Describe the bug**
IIDOptimizer runs during DesignTimeBuild slowing down project load.

**To Reproduce**
Load a project using cswinrt and notice how IIDOptimizer runs during project load. You can check with task manager or with the Project System Tools: https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools

**Expected behavior**
IIDOptimizer should not run to make project load faster.

**Version Info**
CsWinRT 1.3.3

**Comment by j0shuams** [comment]
I merged a change last week that stopped the IIDOptimizer from running during DesignTimeBuild -- https://github.com/microsoft/CsWinRT/blob/1ad1a54214093aded57d5dae70242b2d91d68705/nuget/Microsoft.Windows.CsWinRT.IIDOptimizer.targets#L53
