### ISSUE TITLE
After created file async jump over the next command

### ISSUE THREAD

**Issue by KusiTec** [microsoft/CsWinRT#964]
Hi
I am migrating an UWP App to WinUi3 Desktop C# .Net5
After created file with StorageFolder.CreatedFileAsync jumps over the next command, whitch saves a string to this file by FileIO.WriteTextAsync. As next the related code, taken over by the UWP App:

```c#
public async Task WriteBundleToFileAsync(
            [NotNull] DataBundle bundle,
            CreationCollisionOption creationCollisionOption = CreationCollisionOption.ReplaceExisting)
        {
            if (bundle == null) throw new ArgumentNullException(nameof(bundle) + " by KusiTec");

            var fileNameBundle = bundle.Owner + "." + bundle.Key + ".json";
            var storageFolder = ApplicationData.Current.LocalFolder;

            try
            {
                // Serialize bundle and write to file.
                var jsonStr = JsonConvert.SerializeObject(
                    bundle,
                    Formatting.Indented,
                    new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.All });

                // The follow command over jumps the next after creating the file.                
                var storageFile = await storageFolder.CreateFileAsync(fileNameBundle, creationCollisionOption);
                await FileIO.WriteTextAsync(storageFile, jsonStr);
            }
            catch (Exception e)
            {
                bundle.ExceptionTask?.SniffsException.TreatException(e, this.parent);
            }
        }
```
So, my quesion is, what is wrong?

its every time reproducable. In the explorer under the folder package id, localState, an empty file is created. No exception occurs. The async functions are coded with the await instruction.
The expected behavior, like in Uwp, is, that the file contains the string.

Version:
VisualStudio Version 16.10.4
WinUi3 Desktop c# .Net5
NuGet package version: Microsoft.ProjectReunion 0.8.1
<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

Thanks for helping

**Comment by BenJKuhn** [comment]
It's possible that a failure of some sort is not propagating to / through the projection. This could also be some sort of flushing issue. Not sure which, but moving to C# WinRT to follow up more.

**Comment by angelazhangmsft** [comment]
@KusiTec, do you have a repro project that we could directly run to observe the issue? And also, what Windows OS version is your machine running? 

I was able to observe text is being written to my file with this code:
```csharp
var storageFolder = ApplicationData.Current.LocalFolder;
var storageFile = await storageFolder.CreateFileAsync("test.json", CreationCollisionOption.ReplaceExisting);
await FileIO.WriteTextAsync(storageFile, "test string");
```
I am wondering if the issue is with the specific string you are writing to the file.

**Comment by KusiTec** [comment]
@angelazhangmsft, sorry, it was my fault. The issue was created because of a wrong task control mechanism in the delegate of the closed event from a window. Now its solved. I figured out today...
