### ISSUE TITLE
Null string property gets marshaled as empty string

### ISSUE THREAD

**Issue by iablaauw-MS** [microsoft/CsWinRT#973]
**Describe the bug**
I have a WinRT library that I have written and there is a different project that is consuming that component using CsWinRT. One of the classes has a string property. When I assign `null` to that property the implementation sees the assigned value coming in as empty string. 

Either CsWinRT is coercing that value from null to empty string, or the marshaling is converting it.

This is easy to work around, but is this expected / known behavior? Or is this a bug in CsWinRT?

**Version Info**

* CsWinRT version: 1.3.0
* Using .NET 5, specific version is: net5.0-windows10.0.18362.0
* Windows SDK Projection version: 10.0.18362.18

**Comment by manodasanW** [comment]
Tried out this scenario in .NET core and .NET native.  In both, when a null string is passed, it throws an exception to indicate that it isn't allowed and doesn't marshal them as null.  From looking into it, the justification for that behavior is explained [here](https://stackoverflow.com/a/12981103).

C#/WinRT on the other hand currently converts it to an empty string which is different from the previous behavior of throwing an exception, but I am hesitant to go to that behavior in case any new app is using it and this change would end up breaking them.  Given this is a relaxing of policy compared to previous behavior, I am leaving it as is for now until we get any other reports indicating this is causing unexpected issues.
