### ISSUE TITLE
.NET 5: NullReferenceException thrown from WinRT.Runtime.dll calling GattCharacteristic.WriteValueAsync

### ISSUE THREAD

**Issue by AndyCW** [microsoft/CsWinRT#984]
**Describe the bug**
NullReferenceException thrown from WinRT.Runtime.dll using . TFM net5-windows10.0.19041.0 .
I have code that connects to a BluetoothLE device using Windows APIs and which writes to a GattCharacteristic. This code works in a .NET 4.7.2 console app, where the Windows SDK is referenced by adding a reference to the Microsoft.Windows.SDK.Contracts NuGet package.
Moving to .NET 5 and with the exact same code, the call to GattCharacteristic.WriteValueAsync now fails with a NullReferenceException thrown from WinRT.Runtime.dll. In this .NET 5 console app, the Windows SDK is referenced by setting the TargetFramework in the csproj file to <TargetFramework>net5-windows10.0.19041.0</TargetFramework>.

**To Reproduce**

1. Use the attached sample: [SDKBugRepro.zip](https://github.com/microsoft/CsWinRT/files/7111519/SDKBugRepro.zip)
2. This sample connects to the Microsoft Service you can setup using the Microsoft Bluetooth LE Explorer sample app: download from the Windows Store.
     i). Run the app, select "Virtual Peripheral" from the menu. Select Microsoft Service from the dropdown, then click Add Service. In the service configuration, select "Advertise as connectable", "Include service in advertisement", "Publish advertisement".
3. Now run the two projects in the supplied sample code - the .NET 4.7.2 app works and can write a string to the Microsoft Write characteristic of the virtual peripheral service. The .NET 5 sample - exact same code - throws the exception.

**Expected behavior**
The .NET 5 version should work the same as the version built for .NET Framework 4.7.2

**Version Info**
TFM net5-windows10.0.19041.0

**Additional context**

**Comment by manodasanW** [comment]
@AndyCW is this different from #975 that you previously opened?  We expect for bunch of the Bluetooth APIs to be affected by the bug that we duped #975 to and expect those to be resolved once our latest fixes go out and are available in the .NET SDK.

**Comment by AndyCW** [comment]
@manodasanW Apologies! Lost track of what I'd opened.
This is a dup. I will close it.
