### ISSUE TITLE
Question: Using ToastNotificationManagerCompat etc. with .NET 5

### ISSUE THREAD

**Issue by pr8x** [microsoft/CsWinRT#985]
Hey, I am trying to port some code to .NET 5 and I was previously just referencing Microsoft.Toolkit.Uwp.Notifications to get access to the `ToastNotificationManagerCompat` compat class. With .NET5 that doesn't seem to be possible anymore:

> NETSDK1130 - Referencing a Windows Metadata component directly when targeting .NETCoreApp,Version=v5.0 is not supported. Use the C#/WinRT projection tool (https://aka.ms/cswinrt) or a provided projection for this target.

So I am using the `net5.0-windows10.0.18362.0` TFM now. That however lacks some types such as `ToastNotificationManagerCompat `or `ToastContentBuilder`. Am I missing something here?

**Comment by manodasanW** [comment]
@pr8x to confirm, are you using both the `net5.0-windows10.0.18362.0` TFM and have a reference to the `Microsoft.Toolkit.Uwp.Notifications` package?  If so, I would expect you to see those types as they seem to come from the toolkit package.  Let me know if you don't see them with both of those.

**Comment by pr8x** [comment]
Hey, It's not possible to use this package when using `net5.0-windows10.0.18362.0`. It gives the following error:

> Microsoft.Toolkit.Uwp.Notifications.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.  An updated version of the component supporting .NET 5 is needed. For more information, see https://aka.ms/netsdk1149
