### ISSUE TITLE
CsWinRT doesn't work in a WPF .NET 5 project.

### ISSUE THREAD

**Issue by jlaanstra** [microsoft/CsWinRT#990]
**Describe the bug**
CsWinRT build targets don't generate projection code for WPF inner-builds failing the build.

**To Reproduce**
1. Create a new WPF app project targeting .NET 5
2. Reference a C++/WinRT project and set CsWinRTIncludes to the namespace of the project. 
3. Use a type from the C++/WinRT project in the WPF project.
4. Compile the WPF project.

**Expected behavior**
COmpiles successfully.

**Version Info**
1.3.3

**Comment by angelazhangmsft** [comment]
@jlaanstra, is this still an issue or can we close this? I recall not being able to repro the issue.

**Comment by jlaanstra** [comment]
I believe so as long as you set ```<IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>``` which should be set by default for the .NET 6 SDK.

**Comment by angelazhangmsft** [comment]
Closing as no repro (followed the steps above with the [SimpleMathComponent](https://github.com/microsoft/CsWinRT/tree/master/src/Samples/NetProjectionSample/SimpleMathComponent) example. Feel free to reopen if the issue occurs again.

**Comment by mmarczell-graphisoft** [comment]
I'm experiencing a weird situation where as long as I do not reference the WinRT component anywhere in my C# code, I can see the C# projection file of my library generated into `obj/Debug/net6.0-windows/Generated Files/CsWinRT`. But as soon as I add the using directive in my C# UI code and build the solution again, the same projection file does not exist anymore in that folder, and my build fails. What is happening here and what should I do?
