### ISSUE TITLE
Question: Disposal of out-of-process COM objects

### ISSUE THREAD

**Issue by trympet** [microsoft/CsWinRT#994]
My app uses CsWinRT for some custom projections and for the Windows SDK.

On application exit, my app does not explicitly dispose or clean up each and every out-of-process object. Will out-of-process objects _always_ be cleaned up by the OS? Could certain objects (e.g. the app package updates) be left in an invalid state if not properly destroyed?

**Comment by manodasanW** [comment]
@trympet it is going to depend on whether finalizers are ran during application exit.  Based on [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/destructors), it looks like .NET 5 no longer calls finalizers during application exit which means objects can have COM references which don't get released and thereby the out of process object staying alive if you haven't cleaned them up yourself.  After the client is gone, I think it depends on the specific class on whether it just continues to stay alive or not.  For app package updates, I am not sure as it would depend on that specific class / API.

**Comment by trympet** [comment]
Interesting! Thank you for the insight. Further reading here: https://github.com/dotnet/docs/issues/17463.

Attempting to download an app package update from a sideloaded app can leave the app package in a corrupted state (across all OS components, Microsoft Store, Start Menu, etc.). Reporting Windows API bugs is a pain in the behind though.

Anyways, not related to this repo :)
